"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "goal", label: "1) Objetivo", title: "Un entorno reproducible para desarrollar", subtitle: "TradeOps no debe depender de comandos improvisados ni de una instalacion que solo funciona en una maquina.", chip: "Setup", content: "Codigo Odoo 17\n       |\nPostgreSQL\n       |\ncustom_addons\n       |\nConfiguracion + logs\n       |\nDeveloper Mode\n\nEl entorno debe permitir instalar, actualizar, depurar y probar el modulo desde cero." },
  { id: "postgres", label: "2) PostgreSQL", title: "La base de datos forma parte del entorno", subtitle: "Odoo necesita PostgreSQL y el desarrollador debe conocer version, credenciales, puertos y persistencia.", chip: "Database", content: "PostgreSQL\n  +-- host\n  +-- port\n  +-- user\n  +-- password\n  +-- database\n  +-- volume\n\nNo usar una base de produccion para desarrollar. Cada entorno debe tener datos y credenciales aislados." },
  { id: "source", label: "3) Codigo fuente", title: "Tener Odoo visible y trazable", subtitle: "Trabajar con el codigo fuente permite depurar el framework, entender dependencias y revisar versiones.", chip: "Source", content: "odoo/\n├── odoo-bin\n├── odoo/\n├── addons/\n└── requirements.txt\n\nTradeOps debe vivir separado del core. Fijar la version de Odoo 17 y documentar como obtener dependencias y ejecutar el servidor." },
  { id: "addons-path", label: "4) addons_path", title: "Indicar donde buscar modulos", subtitle: "`addons_path` conecta el servidor con los addons estandar y el espacio de desarrollo propio.", chip: "Odoo", content: "addons_path =\n  /opt/odoo/addons,\n  /opt/odoo/custom_addons\n\nOdoo busca modulos en esas rutas. Un path incorrecto produce modulos que no aparecen, imports fallidos o upgrades que no cargan los archivos esperados." },
  { id: "workspace", label: "5) TradeOps", title: "Crear el espacio custom_addons", subtitle: "El codigo propio debe estar aislado del framework para facilitar Git, upgrades y despliegues.", chip: "Workspace", content: "custom_addons/\n└── tradeops/\n    ├── __init__.py\n    ├── __manifest__.py\n    ├── models/\n    ├── views/\n    ├── security/\n    └── tests/\n\nSeparar el modulo permite actualizar Odoo sin sobrescribir el trabajo propio." },
  { id: "config", label: "6) odoo.conf", title: "Centralizar la configuracion", subtitle: "Un archivo de configuracion evita comandos ambiguos y hace explicito como arranca cada entorno.", chip: "Config", content: "[options]\ndb_host = db\ndb_port = 5432\ndb_user = odoo\ndb_password = odoo\naddons_path = /opt/odoo/addons,/opt/odoo/custom_addons\nlog_level = info\nadmin_passwd = cambiar-en-local\n\nNo commitear secretos reales. Usar variables o plantillas para staging y produccion." },
  { id: "start", label: "7) Arranque", title: "Iniciar Odoo de forma repetible", subtitle: "El mismo procedimiento debe funcionar para el equipo y para CI con diferencias solo de configuracion.", chip: "Runtime", content: "python odoo-bin -c odoo.conf\n\nOdoo conecta PostgreSQL, carga el registry, descubre addons y expone la interfaz.\n\nComprobar:\n- puerto HTTP\n- base accesible\n- modulo visible\n- logs sin errores\n- modo desarrollador disponible" },
  { id: "logs", label: "8) Logs", title: "Los logs son parte del desarrollo", subtitle: "Un entorno sin logs utiles convierte cualquier error de import, XML, permisos o SQL en una investigacion lenta.", chip: "Debug", content: "Buscar en logs:\n- modulo cargado\n- dependencia ausente\n- error Python\n- error XML/XPath\n- constraint\n- acceso denegado\n- error de PostgreSQL\n\nAjustar log_level solo cuando aporte diagnostico. No ocultar fallos con configuraciones silenciosas." },
  { id: "developer", label: "9) Developer Mode", title: "Activar herramientas de desarrollo", subtitle: "Developer Mode permite inspeccionar vistas, campos, acciones, external IDs y metadatos del sistema.", chip: "Tools", content: "Con Developer Mode podemos:\n- ver external IDs\n- inspeccionar vistas\n- revisar campos\n- abrir metadata\n- depurar acciones\n- actualizar listas de aplicaciones\n\nEs una herramienta de desarrollo, no una solucion para saltarse seguridad o validar permisos de usuario final." },
  { id: "avoid", label: "10) Errores", title: "Que no debemos hacer", subtitle: "Las decisiones comodas del comienzo suelen convertirse en problemas de upgrade y seguridad.", chip: "Riesgos", content: "No editar el core.\nNo usar produccion como laboratorio.\nNo commitear credenciales.\nNo instalar modulos manualmente sin documentar.\nNo copiar bases sin entender datos y permisos.\nNo ignorar warnings del log.\nNo mezclar custom_addons con addons estandar.\nNo probar solo con administrador." },
  { id: "today", label: "11) TradeOps hoy", title: "Estado del proyecto", subtitle: "Al terminar esta clase existe una base operativa para comenzar la construccion incremental del modulo.", chip: "Milestone", content: "Odoo 17 fijado\nPostgreSQL disponible\nCodigo fuente localizado\ncustom_addons creado\naddons_path configurado\nodoo.conf documentado\nArranque repetible\nLogs accesibles\nDeveloper Mode activo\nTradeOps listo para instalar\n\nEl siguiente paso sera crear el manifest y el primer modelo." },
  { id: "qa", label: "12) QA", title: "Comprobar el entorno antes del modelo", subtitle: "La primera prueba de calidad verifica infraestructura y no logica de negocio.", chip: "QA", content: "1. Arrancar PostgreSQL.\n2. Arrancar Odoo.\n3. Crear o seleccionar base de desarrollo.\n4. Actualizar lista de aplicaciones.\n5. Encontrar TradeOps.\n6. Instalar o actualizar el modulo.\n7. Revisar logs.\n8. Confirmar que el cambio sobrevive un reinicio." },
  { id: "checklist", label: "13) Checklist", title: "Entorno profesional listo", subtitle: "Otra persona debe poder reconstruir este entorno siguiendo la documentacion del repositorio.", chip: "Checklist", content: "Odoo 17 identificado\nPostgreSQL aislado\nDependencias instaladas\nCodigo versionado\ncustom_addons separado\naddons_path correcto\nConfiguracion fuera de secretos\nArranque documentado\nLogs claros\nDeveloper Mode\nInstall/upgrade probado\nBackup y reset conocidos\nTradeOps visible" },
  { id: "closing", label: "14) Cierre", title: "El entorno tambien es arquitectura", subtitle: "Un backend senior prepara la forma de desarrollar antes de añadir funcionalidad sobre una base fragil.", chip: "Cierre", content: "Backend junior:\nInstalo Odoo y empiezo a tocar pantallas.\n\nBackend senior:\nFija versiones, aisla PostgreSQL, separa addons, centraliza configuracion, observa logs, prueba upgrades y documenta el arranque.\n\nUn entorno reproducible es la primera feature de TradeOps 360." },
];

export default function Daily158Client() {
  const [activeSection, setActiveSection] = useState("goal");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/157"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Entorno profesional Odoo 17</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/157"><span className={styles.kbd}>←</span> Dia 157</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>21/08/2026</div><div className={styles.badge}>Daily #158 • Odoo Setup</div><h2 className={styles.title}>Preparar un entorno profesional de desarrollo Odoo 17 para TradeOps 360</h2><p className={styles.lead}>PostgreSQL, codigo fuente, custom_addons, configuracion, logs y Developer Mode para construir sobre una base reproducible.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/157"><span className={styles.kbd}>←</span> Dia 157</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
