"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "problem", label: "1) Problema", title: "La entrega real puede ser parcial", subtitle: "El happy path entrega todo, pero una operación real necesita conservar lo entregado, lo pendiente y el motivo.", chip: "Contexto", content: "Esperado: 10 unidades\nEntregado: 7 unidades\nPendiente: 3 unidades\n\nPosibles incidencias:\n- cliente no recibió parte\n- vehículo averiado\n- mercancía dañada\n- dirección inaccesible\n- falta de documentación\n\nEntregado no significa necesariamente completado." },
  { id: "truth", label: "2) Source of Truth", title: "No inventar cantidades en TradeOps", subtitle: "La cantidad físicamente procesada debe seguir viniendo de Odoo Inventory.", chip: "Arquitectura", content: "TradeOps Distribution\n  -> coordina y explica\n\nOdoo Inventory\n  -> stock.move\n  -> stock.move.line\n  -> stock.picking\n  -> cantidad física\n\nNo duplicar delivered_quantity si Inventory ya es dueño del dato." },
  { id: "partial", label: "3) Parcial", title: "Detectar una entrega incompleta", subtitle: "La distribución puede calcular su situación comparando la cantidad esperada con el picking real.", chip: "Computed", content: "expected_quantity = 10\nprocessed_quantity = 7\npending_quantity = (\n    expected_quantity - processed_quantity\n)\n\nif pending_quantity > 0:\n    delivery_state = 'partial'\n\nEl valor derivado debe actualizarse desde los movimientos de stock." },
  { id: "states", label: "4) Estados", title: "No marcar Delivered demasiado pronto", subtitle: "Los estados de distribución deben distinguir parcial, completa, cancelada e incidencias.", chip: "Workflow", content: "draft\n  -> planned\n  -> dispatched\n  -> partial\n  -> delivered\n\nTambién puede existir:\nincident\n  -> revisión de la causa\n  -> replanificación o cierre\n\nUn estado debe representar un hecho verificable." },
  { id: "incident", label: "5) Incidencia", title: "Registrar por qué ocurrió", subtitle: "Una cantidad pendiente explica qué pasó; una incidencia conserva el contexto operativo y la decisión tomada.", chip: "Modelo", content: "trade.distribution.incident\n  +-- distribution_id\n  +-- incident_type\n  +-- description\n  +-- affected_quantity\n  +-- created_by\n  +-- created_at\n  +-- resolution\n\nNo esconder el motivo en una nota informal si afecta al proceso." },
  { id: "wizard", label: "6) Wizard", title: "Una decisión puntual merece un Wizard", subtitle: "Un Wizard captura datos temporales para resolver una acción sin convertir cada diálogo en un modelo permanente.", chip: "TransientModel", content: "class PartialDeliveryWizard(models.TransientModel):\n    _name = 'trade.partial.delivery.wizard'\n\n    distribution_id = fields.Many2one(\n        'trade.distribution', required=True)\n    delivered_quantity = fields.Float(required=True)\n    incident_type = fields.Selection([...])\n    notes = fields.Text()\n\nTransientModel representa una interacción temporal." },
  { id: "transient", label: "7) TransientModel", title: "Temporal no significa sin reglas", subtitle: "El Wizard puede validarse, usar permisos y ejecutar una operación atómica sobre la distribución.", chip: "Odoo", content: "El Wizard:\n- recibe la decisión del usuario\n- valida cantidades y estado\n- crea la incidencia si aplica\n- actualiza el flujo mediante acciones\n- devuelve feedback\n\nDespués de completar su propósito, sus datos temporales pueden limpiarse." },
  { id: "validation", label: "8) Validacion", title: "La cantidad parcial debe ser válida", subtitle: "No se puede confirmar una entrega negativa, superior a la esperada o incompatible con el picking.", chip: "Rules", content: "Validar:\n- delivered_quantity > 0\n- delivered_quantity <= expected_quantity\n- no superar lo procesado por Inventory\n- distribución en estado despachado\n- incidencia obligatoria si queda pendiente\n\nLas reglas críticas viven en servidor, no solo en la vista." },
  { id: "flow", label: "9) Flujo", title: "Aplicar la decisión sin falsear Inventory", subtitle: "El Wizard coordina el proceso, pero no escribe una cantidad física que contradiga los movimientos reales.", chip: "Proceso", content: "Usuario abre Wizard\n  -> selecciona cantidad/motivo\n  -> sistema valida picking\n  -> registra incidencia\n  -> recalcula pendiente\n  -> cambia estado derivado\n  -> muestra siguiente acción\n\nInventory sigue siendo la fuente física." },
  { id: "replan", label: "10) Replanificar", title: "Lo pendiente necesita una siguiente acción", subtitle: "Una entrega parcial no termina el proceso: puede requerir nueva ruta, otro vehículo o comunicación al cliente.", chip: "Operacion", content: "Pendiente = 3\n\nSiguientes opciones:\n- reintentar entrega\n- crear nueva distribución\n- devolver mercancía\n- cancelar saldo\n- escalar incidencia\n\nLa acción elegida debe quedar registrada y ser auditable." },
  { id: "atomic", label: "11) Atomicidad", title: "La resolución debe ser todo o nada", subtitle: "La incidencia, la decisión y el estado de la distribución no deben quedar parcialmente actualizados.", chip: "Transaccion", content: "Wizard confirma\n  -> validar estado\n  -> validar cantidades\n  -> crear incidencia\n  -> actualizar workflow\n  -> recalcular estado\n\nSi un paso falla, rollback.\nNo dejar una distribución cerrada con una incidencia perdida." },
  { id: "permissions", label: "12) Seguridad", title: "La decisión depende del usuario", subtitle: "No todos los usuarios deben poder modificar cantidades, cancelar saldos o cerrar incidencias.", chip: "Access", content: "Comprobar:\n- compañía de la distribución\n- permisos del usuario\n- rol operativo\n- acceso al picking relacionado\n- quién puede cerrar una incidencia\n\nEl Wizard hereda el contexto de seguridad; no debe saltárselo." },
  { id: "qa", label: "13) QA", title: "Probar el caso real, no solo el formulario", subtitle: "Las pruebas deben verificar cantidades, estados, incidencias, persistencia y ausencia de cambios parciales.", chip: "QA", content: "Casos mínimos:\n- entrega completa\n- entrega parcial\n- cantidad cero\n- cantidad negativa\n- cantidad mayor a la esperada\n- picking incompatible\n- motivo obligatorio\n- usuario sin permiso\n- fallo durante resolución\n- replanificación trazable\n- repetición del Wizard" },
  { id: "architecture", label: "14) Arquitectura", title: "Separar físico, empresarial y temporal", subtitle: "Cada concepto tiene un dueño claro y el Wizard solo coordina la decisión puntual.", chip: "Mapa", content: "stock.picking\n  -> realidad física\ntrade.distribution\n  -> coordinación empresarial\ntrade.incident\n  -> causa y resolución\nWizard\n  -> interacción temporal\n\nNo convertir un estado de UI en una mentira de inventario." },
  { id: "closing", label: "15) Cierre", title: "El sistema debe sobrevivir al mundo real", subtitle: "Las entregas parciales y las incidencias no son excepciones raras: forman parte del dominio logístico.", chip: "Cierre", content: "Regla mental:\n\nNo ocultar lo pendiente.\nNo duplicar la fuente física.\nRegistrar la causa.\nUsar Wizards para decisiones puntuales.\nValidar antes de cambiar estados.\nMantener trazabilidad y rollback.\n\nUn backend profesional modela el fallo sin romper la verdad." },
];

export default function Daily172Client() {
  const [activeSection, setActiveSection] = useState("problem");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/171"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Entregas parciales e incidencias en Odoo</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/171"><span className={styles.kbd}>←</span> Dia 171</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>09/09/2026</div><div className={styles.badge}>Daily #172 • Odoo Logistics</div><h2 className={styles.title}>Entregas parciales, incidencias y Wizards en Odoo 17</h2><p className={styles.lead}>Modelar entregas incompletas, registrar sus causas y capturar decisiones operativas sin falsear Inventory.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/171"><span className={styles.kbd}>←</span> Dia 171</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
