"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "idea", label: "1) Idea clave", title: "Quien coordina la compra", subtitle: "Orders, Inventory y Payments ya funcionan por separado, pero el proceso completo necesita un coordinador.", chip: "Idea", content: "Flujo esperado:\n\nConfirmar orden\n       |\n       v\nReservar inventario\n       |\n       v\nProcesar pago\n       |\n       v\nConfirmar consumo\n       |\n       v\nCompletar orden\n\nTambien debemos manejar stock insuficiente, pagos rechazados, timeouts, duplicados y eventos fuera de orden. Hoy implementamos una Saga." },
  { id: "distributed", label: "2) Transaccion distribuida", title: "No existe un unico rollback", subtitle: "OrdersDb, InventoryDb, PaymentsDb, RabbitMQ y el proveedor externo tienen transacciones distintas.", chip: "Limites", content: "En un monolito podriamos usar un DbContext y una transaccion ACID.\n\nEn microservicios tenemos:\nOrdersDb\nInventoryDb\nPaymentsDb\nRabbitMQ\nProveedor de pagos\n\nNo podemos hacer ROLLBACK del proveedor como si fuera una tabla SQL." },
  { id: "compensation", label: "3) Compensacion", title: "Rollback no es compensacion", subtitle: "Cuando una transaccion local ya fue confirmada, neutralizamos su efecto con otra operacion de negocio.", chip: "Concepto", content: "Rollback:\nLa transaccion aun no se confirmo y revierte cambios internos.\n\nCompensacion:\nLa operacion ya se confirmo y ejecutamos otra transaccion explicita.\n\nReserveInventory -> ReleaseInventory\nPaymentApproved -> RefundPayment\n\nUna compensacion puede fallar, tardar o quedar pendiente." },
  { id: "orchestration", label: "4) Dos estilos", title: "Coreografia y orquestacion", subtitle: "La coreografia distribuye decisiones entre consumidores; la orquestacion concentra el estado del proceso.", chip: "Diseño", content: "Coreografia:\nOrders publica -> Inventory reacciona -> Payments reacciona -> Orders reacciona.\n\nOrquestacion:\nUn OrderProcessingSaga mantiene el estado, decide el siguiente comando y solicita compensaciones.\n\nPara OrderFlow usaremos una Saga orquestada porque necesitamos visibilidad y control del proceso." },
  { id: "choreography", label: "5) Coreografia", title: "Ventajas y limites", subtitle: "La coreografia reduce un coordinador central, pero puede dispersar la logica hasta volverla dificil de seguir.", chip: "Comparacion", content: "Ventajas:\nmenos componente central\nservicios reaccionan a eventos\nnuevos consumidores faciles de añadir\n\nProblemas:\nquien conoce el estado global?\nque paso falta?\nquien compensa?\nque ocurre fuera de orden?\n\nEl flujo puede convertirse en una cadena dificil de visualizar." },
  { id: "saga", label: "6) OrderProcessing", title: "El coordinador de OrderFlow", subtitle: "OrderProcessing Worker vive separado del agregado Order y coordina servicios mediante comandos y eventos.", chip: "Saga", content: "Orders\n  | OrderConfirmed\n  v\nOrderProcessingSaga\n  | ReserveInventory\n  v\nInventory\n  | InventoryReserved\n  v\nPayments\n  | PaymentApproved\n  v\nInventory -> ConfirmConsumption\n  |\n  v\nOrders -> CompleteOrder" },
  { id: "aggregate", label: "7) Saga vs Aggregate", title: "No convertir Order en coordinador", subtitle: "Order protege consistencia local; la Saga coordina el proceso distribuido.", chip: "DDD", content: "Order protege:\nUna orden vacia no se confirma.\nUna orden completada no se edita.\nUna orden fallida no se completa directamente.\n\nSaga protege:\nNo pagar antes de reservar.\nNo completar antes de consumir inventario.\nLiberar si el pago es rechazado.\nReembolsar si falla despues del cobro." },
  { id: "states", label: "8) Estados", title: "Estados explicitos de la Saga", subtitle: "Un estado generico Failed no indica que ocurrio ni que compensacion falta.", chip: "Estados", content: "Started\nReservingInventory\nInventoryReservationFailed\nInventoryReserved\nProcessingPayment\nPaymentPendingVerification\nPaymentRejected\nPaymentApproved\nConfirmingInventory\nInventoryConfirmed\nCompletingOrder\nCompensatingInventory\nRefundingPayment\nCompleted\nCompensated\nManualInterventionRequired" },
  { id: "why-states", label: "9) Por que tantos estados", title: "Saber que paso y que sigue", subtitle: "La Saga debe distinguir pasos completados, acciones pendientes y compensaciones activas.", chip: "Modelo", content: "Necesitamos saber:\n\nQue ya ocurrio.\nQue estamos esperando.\nQue accion sigue.\nQue compensacion esta activa.\nSi el proceso termino.\nSi necesita intervencion humana.\n\nLos estados son la memoria durable del proceso distribuido." },
  { id: "entity", label: "10) Entidad Saga", title: "OrderProcessingSaga", subtitle: "La entidad guarda identidad, correlacion, monto, referencias, estado y fechas de operacion.", chip: "Domain", content: "OrderProcessingSaga:\nId\nOrderId\nCorrelationId\nAmount\nCurrency\nStatus\nReservationId\nPaymentId\nFailureCode\nFailureReason\nCreatedAt\nUpdatedAt\nCompletedAt\nCompensationStartedAt\nCompensationCompletedAt\nVersion\n\nVersion permite concurrencia optimista." },
  { id: "transitions", label: "11) Transiciones", title: "La Saga valida cada paso", subtitle: "No se puede iniciar pago si no existe una reserva ni completar antes del consumo.", chip: "Reglas", content: "StartInventoryReservation: Started -> ReservingInventory\nMarkInventoryReserved: ReservingInventory -> InventoryReserved\nStartPayment: InventoryReserved -> ProcessingPayment\nMarkPaymentApproved: ProcessingPayment -> PaymentApproved\nStartInventoryConfirmation: PaymentApproved -> ConfirmingInventory\nMarkInventoryConfirmed: ConfirmingInventory -> InventoryConfirmed\nStartOrderCompletion: InventoryConfirmed -> CompletingOrder\nComplete: CompletingOrder -> Completed\n\nEnsureStatus rechaza transiciones invalidas." },
  { id: "inventory-failed", label: "12) Stock insuficiente", title: "Compensar un fallo de Inventory", subtitle: "Si no hay reserva, Payments nunca debe ejecutarse.", chip: "Compensacion", content: "OrderConfirmed\n       |\n       v\nReserveInventory\n       |\n       v\nInventoryReservationFailed\n       |\n       v\nMarkOrderInventoryFailed\n\nNo hay reserva que liberar. La Saga termina en un estado de fallo de inventario." },
  { id: "payment-rejected", label: "13) Pago rechazado", title: "Liberar inventario reservado", subtitle: "El rechazo es un resultado de negocio y activa una compensacion explicita.", chip: "Compensacion", content: "OrderConfirmed\n -> ReserveInventory\n -> InventoryReserved\n -> ProcessPayment\n -> PaymentRejected\n -> ReleaseInventory\n -> InventoryReleased\n -> MarkOrderPaymentFailed\n\nReleaseInventory es otra operacion distribuida, no un rollback tecnico." },
  { id: "payment-uncertain", label: "14) Pago incierto", title: "No compensar demasiado pronto", subtitle: "Si el proveedor puede haber cobrado, primero debemos conciliar el estado.", chip: "Conciliacion", content: "PaymentPendingVerification\n\nNo debemos:\nliberar inventario inmediatamente\nvolver a cobrar con una operacion nueva\n\nPrimero consultamos el proveedor. Si se confirma, seguimos. Si se rechaza, compensamos. Si no responde, mantenemos pendiente." },
  { id: "refund", label: "15) Reembolso", title: "Fallo despues de cobrar", subtitle: "Si falla la confirmacion de inventario despues de un pago aprobado, la Saga puede solicitar un refund.", chip: "Refund", content: "PaymentApproved\n       |\n       v\nConfirmInventory falla\n       |\n       v\nRefundPayment\n       |\n       v\nRefunded o RefundPending\n\nEl cliente ya fue cobrado y el inventario no se consumio. La compensacion puede tardar o fallar." },
  { id: "manual", label: "16) Intervencion", title: "ManualInterventionRequired", subtitle: "Algunos estados necesitan una persona, alerta y una accion operativa segura.", chip: "Operacion", content: "Ejemplo:\nProveedor confirma el cobro.\nEl reembolso falla durante horas.\nInventory presenta datos inconsistentes.\n\nLa Saga debe generar:\nalerta critica\nticket operativo\ntrazabilidad completa\nposibilidad de reejecutar una accion segura\n\nNo ocultamos estos casos bajo Failed." },
  { id: "commands", label: "17) Comandos", title: "La Saga envia comandos", subtitle: "Los comandos tienen un destinatario logico y piden una accion concreta a un servicio.", chip: "Contratos", content: "ReserveInventoryCommand\nProcessPaymentCommand\nConfirmInventoryConsumptionCommand\nCompleteOrderCommand\nReleaseInventoryCommand\nRefundPaymentCommand\nMarkOrderPaymentFailedCommand\n\nCada comando lleva MessageId, CorrelationId, CausationId, CreatedAt, CommandType y Version." },
  { id: "events", label: "18) Eventos", title: "La Saga recibe resultados", subtitle: "Los eventos informan hechos que permiten avanzar o compensar el proceso.", chip: "Mensajeria", content: "OrderConfirmed\nInventoryReserved\nInventoryReservationFailed\nPaymentApproved\nPaymentRejected\nPaymentPendingVerification\nInventoryConsumptionConfirmed\nInventoryReleased\nPaymentRefunded\nOrderCompleted\n\nLa Saga nunca asume que el siguiente paso ocurrio: espera el evento correspondiente." },
  { id: "correlation", label: "19) Correlacion", title: "Relacionar mensajes con una Saga", subtitle: "CorrelationId y SagaId permiten encontrar todos los comandos, eventos y errores de una compra.", chip: "Trazabilidad", content: "CorrelationId = identificador del proceso.\nCausationId = mensaje que origino el actual.\nSagaId = instancia durable del coordinador.\n\nTodos los logs deben incluir estos identificadores para reconstruir una compra distribuida." },
  { id: "persistence", label: "20) Persistencia", title: "Guardar el estado de la Saga", subtitle: "El worker puede reiniciarse sin olvidar que una reserva ya fue realizada o que un pago esta pendiente.", chip: "Database", content: "OrderProcessingDb:\nSagas\nSagaMessages o Inbox\nOutbox de comandos\n\nGuardar estado y comando pendiente en la misma transaccion local evita avanzar en memoria y perder el siguiente paso al reiniciar." },
  { id: "worker", label: "21) Worker", title: "OrderProcessing.Worker", subtitle: "El worker consume eventos, carga la Saga, aplica una transicion y publica el comando siguiente.", chip: "Worker", content: "1. consumir evento\n2. comprobar idempotencia\n3. localizar Saga por CorrelationId\n4. validar estado esperado\n5. aplicar transicion\n6. guardar Saga\n7. publicar siguiente comando\n8. ACK despues del exito\n\nUn mensaje repetido no debe repetir una reserva ni un pago." },
  { id: "idempotency", label: "22) Idempotencia", title: "Eventos duplicados y fuera de orden", subtitle: "RabbitMQ entrega al menos una vez y la red no garantiza el orden global.", chip: "Resiliencia", content: "Antes de procesar:\n1. buscar MessageId en Inbox.\n2. si existe, ACK y salir.\n3. verificar CorrelationId y estado.\n4. aplicar solo la transicion valida.\n5. registrar mensaje procesado.\n\nUn PaymentApproved recibido dos veces no debe completar dos veces la orden." },
  { id: "concurrency", label: "23) Concurrencia", title: "Evitar dos workers sobre la misma Saga", subtitle: "Dos eventos simultaneos no deben sobrescribir el estado de la instancia.", chip: "Concurrencia", content: "Version optimista:\nWorker A carga Version 4.\nWorker B carga Version 4.\nA guarda y pasa a Version 5.\nB intenta guardar Version 4.\n\nEF Core detecta DbUpdateConcurrencyException.\n\nLa operacion se recarga, se reevalua o pasa a retry controlado." },
  { id: "timeouts", label: "24) Timeouts", title: "Pasos pendientes y reintentos", subtitle: "Si no llega InventoryReserved o PaymentApproved, la Saga necesita deadlines y recuperacion.", chip: "Operacion", content: "Cada paso puede guardar:\nStartedAt\nDeadlineAt\nRetryCount\nLastError\nNextRetryAt\n\nUn scheduler detecta sagas atascadas.\n\nNo reintentamos indefinidamente: despues del limite se compensa o requiere intervencion manual." },
  { id: "outbox", label: "25) Outbox de comandos", title: "Persistir el siguiente comando", subtitle: "Actualizar la Saga y publicar un comando tambien es un dual write.", chip: "Outbox", content: "Saga cambia a ReservingInventory\nGuardar Saga\nGuardar ReserveInventoryCommand en Outbox\nCOMMIT\n\nDespues el worker publica RabbitMQ.\n\nSi RabbitMQ falla, el estado y el comando siguen pendientes y pueden reintentarse." },
  { id: "monitoring", label: "26) Observabilidad", title: "Medir el proceso distribuido", subtitle: "El estado global debe poder consultarse sin leer logs de cinco servicios manualmente.", chip: "Observabilidad", content: "Metricas:\nSagas iniciadas\nSagas completadas\nSagas compensadas\nPaymentPendingVerification\nManualInterventionRequired\nEdad del paso actual\nRetries por comando\nTiempo total de compra\n\nDashboard por CorrelationId permite diagnosticar una orden." },
  { id: "testing", label: "27) Pruebas", title: "Escenarios que debemos probar", subtitle: "La Saga debe avanzar y compensar de forma determinista ante cada resultado.", chip: "Testing", content: "Flujo completo aprobado.\nInventario insuficiente no procesa pago.\nPago rechazado libera reserva.\nPago incierto espera conciliacion.\nInventario falla despues del pago -> refund.\nEvento duplicado no repite efectos.\nEvento fuera de orden se rechaza o espera.\nWorker reiniciado continua desde estado persistido.\nReintento no genera comandos duplicados.\nFallo de compensacion -> intervencion manual." },
  { id: "checklist", label: "28) Checklist", title: "Validacion de la Saga", subtitle: "La coordinacion es confiable cuando cada transicion y compensacion queda persistida y observable.", chip: "Checklist", content: "Saga separada de Order\nEstados explicitos\nEnsureStatus en transiciones\nComandos con destinatario\nEventos con correlacion\nEstado persistido\nInbox idempotente\nOutbox de comandos\nCompensaciones modeladas\nRefundPending soportado\nDeadlines y retries\nConcurrencia optimista\nAlertas de intervencion manual\nPruebas de duplicados y desorden" },
  { id: "closing", label: "29) Cierre", title: "Como piensa un backend senior", subtitle: "Una Saga no convierte microservicios en una transaccion ACID: coordina pasos y compensa cuando el mundo cambia.", chip: "Cierre", content: "Backend junior:\nUna Saga es una cadena de llamadas.\n\nBackend senior:\nUna Saga es una maquina de estados durable, con comandos, eventos, deadlines, idempotencia, compensaciones, observabilidad y una salida segura para los casos que requieren humanos.\n\nLa compra distribuida no se revierte: se coordina y se compensa." },
];

export default function Daily143Client() {
  const [activeSection, setActiveSection] = useState("idea");

  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement | null;
      if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return;
      if (event.key.toLowerCase() === "p") window.location.href = "/daily/142";
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, []);

  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);

  return (
    <div className={styles.page}>
      <header className={styles.topbar}><div className={styles.topbarInner}>
        <div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Saga para coordinar la compra</div></div></div>
        <nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav>
        <div className={styles.actions}><Link className={styles.btn} href="/daily/142"><span className={styles.kbd}>←</span> Dia 142</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div>
      </div></header>
      <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}>
        <div className={styles.dailyHero}><div className={styles.createdAt}>29/07/2026</div><div className={styles.badge}>Daily #143 • OrderProcessing Saga</div><h2 className={styles.title}>Implementar una Saga para coordinar la compra y sus compensaciones</h2><p className={styles.lead}>La Saga coordina transacciones locales, comandos, eventos y compensaciones sin intentar convertir todos los servicios en una sola transaccion distribuida.</p></div>
        <nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>
        {sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}
        <div className={styles.footerNav}><Link className={styles.btn} href="/daily/142"><span className={styles.kbd}>←</span> Dia 142</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div>
      </div></article></div></main>
    </div>
  );
}
