"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "problem", label: "1) Problema", title: "Extender antes que reconstruir", subtitle: "Odoo ya aporta contactos, productos, ventas e inventario: TradeOps debe añadir lo que necesita sobre esas bases.", chip: "Contexto", content: "Odoo ya tiene:\n- res.partner\n- product.product\n- stock.picking\n- sale.order\n\nEvitar crear trade.customer, trade.product o trade.inventory cuando solo necesitamos campos y comportamiento adicional." },
  { id: "inherit", label: "2) _inherit", title: "Extender un modelo existente", subtitle: "_inherit añade campos o comportamiento sin reemplazar el modelo estándar.", chip: "Modelo", content: "class ResPartner(models.Model):\n    _inherit = 'res.partner'\n\n    trade_code = fields.Char(\n        string='TradeOps Code',\n    )\n\nres.partner sigue siendo res.partner, ahora con trade_code." },
  { id: "name", label: "3) _name", title: "Crear no es extender", subtitle: "_name define un modelo nuevo; _inherit amplía uno existente. Elegir mal duplica conceptos y rompe integraciones.", chip: "Diseño", content: "_name = 'trade.import'\n  -> modelo nuevo\n\n_inherit = 'res.partner'\n  -> modelo estándar extendido\n\nUsar _inherit cuando el concepto ya pertenece a Odoo." },
  { id: "tradeops", label: "4) TradeOps", title: "Extensiones concretas para TradeOps", subtitle: "Contactos y productos pueden aportar datos de negocio sin crear copias de entidades estándar.", chip: "Aplicacion", content: "res.partner\n  +-- trade_code\n  +-- is_trade_supplier\n\nproduct.product\n  +-- customs_code\n  +-- country_of_origin_id\n\nEl resto de modulos de Odoo puede seguir usando los mismos registros." },
  { id: "view", label: "5) Views", title: "Una View define la interfaz", subtitle: "Las vistas XML indican qué campos se muestran y cómo se organiza la experiencia del usuario.", chip: "UI", content: "<form>\n  <sheet>\n    <group>\n      <field name='name'/>\n      <field name='trade_code'/>\n    </group>\n  </sheet>\n</form>\n\nEl modelo guarda comportamiento; la vista presenta datos." },
  { id: "form", label: "6) Form View", title: "Mostrar nuestros datos en un formulario", subtitle: "Un campo Python no será utilizable en la interfaz hasta que una vista lo incorpore.", chip: "XML", content: "<record id='view_partner_form_tradeops' model='ir.ui.view'>\n  <field name='name'>res.partner.form.tradeops</field>\n  <field name='model'>res.partner</field>\n  <field name='arch' type='xml'>\n    <form>...</form>\n  </field>\n</record>" },
  { id: "view-inherit", label: "7) Herencia", title: "Heredar una vista sin copiarla", subtitle: "La herencia de vistas agrega o modifica fragmentos de la interfaz estándar de forma mantenible.", chip: "View Inheritance", content: "<field name='inherit_id' ref='base.view_partner_form'/>\n\nCopiar una vista estándar crea deuda: las actualizaciones de Odoo ya no llegan a nuestra interfaz. Heredar mantiene el vínculo." },
  { id: "xpath", label: "8) XPath", title: "XPath localiza dónde insertar", subtitle: "La expresión selecciona un nodo de la vista base y define la posición del nuevo contenido.", chip: "XPath", content: "<xpath expr=\"//field[@name='vat']\" position='after'>\n  <field name='trade_code'/>\n</xpath>\n\nPosiciones habituales:\n- before\n- after\n- inside\n- replace\n- attributes" },
  { id: "partner", label: "9) Contactos", title: "Extender la vista de contactos", subtitle: "TradeOps puede añadir sus datos junto a los campos estándar, en vez de crear una pantalla paralela.", chip: "Integracion", content: "<record id='view_partner_form_tradeops' model='ir.ui.view'>\n  <field name='inherit_id' ref='base.view_partner_form'/>\n  <field name='arch' type='xml'>\n    <xpath expr=\"//field[@name='vat']\" position='after'>\n      <field name='trade_code'/>\n    </xpath>\n  </field>\n</record>" },
  { id: "action", label: "10) Actions", title: "Una acción abre la experiencia", subtitle: "Las window actions indican qué modelo y vistas se muestran cuando un usuario entra en una función.", chip: "Action", content: "<record id='action_trade_import' model='ir.actions.act_window'>\n  <field name='name'>Imports</field>\n  <field name='res_model'>trade.import</field>\n  <field name='view_mode'>tree,form</field>\n</record>\n\nUna action conecta navegación y modelo." },
  { id: "menu", label: "11) Menus", title: "El menú hace visible la funcionalidad", subtitle: "Los menús se organizan jerárquicamente y apuntan a acciones, no directamente a modelos.", chip: "Navegacion", content: "<menuitem id='menu_tradeops_root' name='TradeOps'/>\n<menuitem id='menu_trade_import'\n  name='Imports'\n  parent='menu_tradeops_root'\n  action='action_trade_import'/>\n\nMenu -> Action -> View -> Model" },
  { id: "super", label: "12) super()", title: "Ampliar comportamiento existente", subtitle: "super() conserva la lógica estándar y permite añadir nuestra regla antes o después de ella.", chip: "Python", content: "def write(self, vals):\n    result = super().write(vals)\n    if 'trade_code' in vals:\n        self._validate_trade_code()\n    return result\n\nNunca copiar la implementación base cuando puede extenderse." },
  { id: "qa", label: "13) QA", title: "Probar la integración completa", subtitle: "Una extensión correcta debe preservar la funcionalidad estándar y exponer la nueva sin regresiones.", chip: "QA", content: "Comprobar:\n- el modelo estándar sigue funcionando\n- el campo nuevo persiste\n- la vista carga sin XPath roto\n- el menú abre la acción correcta\n- permisos aplican\n- actualizar el addon no duplica datos\n- super() conserva el comportamiento base" },
  { id: "map", label: "14) Mapa", title: "El flujo mental para extender Odoo", subtitle: "Cada capa tiene una responsabilidad clara, desde el modelo hasta la navegación.", chip: "Mapa", content: "_inherit\n  -> añade datos o comportamiento\nView heredada\n  -> presenta los campos\nXPath\n  -> define la ubicación\nAction\n  -> abre el recurso\nMenu\n  -> lo hace accesible\nsuper()\n  -> amplía lógica estándar" },
  { id: "closing", label: "15) Cierre", title: "Extender es colaborar con Odoo", subtitle: "La integración más sólida reutiliza los conceptos estándar y agrega solo lo específico de TradeOps.", chip: "Cierre", content: "Regla mental:\n\nSi Odoo ya tiene el concepto, extenderlo.\nSi el concepto es propio del negocio, crearlo.\n\nAsí evitamos duplicación, mantenemos compatibilidad y construimos addons sostenibles." },
];

export default function Daily166Client() {
  const [activeSection, setActiveSection] = useState("problem");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/165"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Extender Odoo con _inherit y Views</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/165"><span className={styles.kbd}>←</span> Dia 165</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>02/09/2026</div><div className={styles.badge}>Daily #166 • Odoo Extensions</div><h2 className={styles.title}>_inherit, Views, XPath, Actions y Menus: empezar a extender Odoo</h2><p className={styles.lead}>Extender funcionalidad estándar de Odoo sin copiar ni modificar su código fuente.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/165"><span className={styles.kbd}>←</span> Dia 165</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
