"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "idea", label: "1) Idea clave", title: "Seguir una compra completa", subtitle: "Cuando una orden queda procesando, necesitamos saber exactamente en que servicio se detuvo.", chip: "Idea", content: "OrderFlow ya tiene:\nOrders\nInventory\nPayments\nRabbitMQ\nOutbox\nInbox\nSaga\n\nUn cliente dice: hice una compra hace 4 minutos y sigue procesando.\n\nNo queremos revisar manualmente logs de todos los servicios. Necesitamos seguir la orden como si fuera un paquete." },
  { id: "three-pillars", label: "2) Tres señales", title: "Logging, Metrics y Tracing", subtitle: "Observabilidad no es una sola herramienta: cada señal responde una pregunta diferente.", chip: "Conceptos", content: "Logs:\nQue ocurrio?\nEjemplo: Payment approved.\n\nMetrics:\nCon que frecuencia ocurre?\nEjemplo: 35 pagos por minuto.\n\nTracing:\nQue camino siguio una peticion?\nEjemplo: Gateway -> Orders -> Inventory -> Payments." },
  { id: "otel", label: "3) OpenTelemetry", title: "Un estandar abierto", subtitle: "OpenTelemetry genera señales sin atar la instrumentacion principal a un proveedor concreto.", chip: "OpenTelemetry", content: "OpenTelemetry puede exportar a:\n\nJaeger\nGrafana Tempo\nZipkin\nPrometheus\nGrafana\nAzure Monitor\nElastic\nDatadog\n\nLa aplicacion instrumenta una vez y el destino puede cambiar por configuracion." },
  { id: "trace", label: "4) Trace", title: "Una traza es la operacion completa", subtitle: "Una compra distribuida puede durar segundos o minutos, pero pertenece al mismo flujo tecnico.", chip: "Tracing", content: "Trace: Comprar producto\n\nPuede contener:\nHTTP POST /orders\nGuardar Order\nPublicar OrderConfirmed\nConsumir InventoryReserved\nProcesar Payment\nCompletar Order\n\nLa traza permite investigar el proceso entero." },
  { id: "span", label: "5) Span", title: "Cada trabajo es un span", subtitle: "Los spans representan unidades de trabajo con duracion, estado, tags y eventos propios.", chip: "Tracing", content: "Span:\nProcess Payment\n\nDuration: 312 ms\nStatus: OK\nOrderId: 5849\nCustomerId: 248\n\nLos spans forman un arbol padre-hijo y todos comparten el TraceId de la operacion." },
  { id: "ids", label: "6) IDs", title: "CorrelationId, TraceId y SpanId", subtitle: "El identificador funcional y los identificadores tecnicos cumplen funciones diferentes.", chip: "Trazabilidad", content: "CorrelationId = identidad funcional de la compra.\nTraceId = ejecucion tecnica completa.\nSpanId = trabajo concreto dentro de la traza.\n\nUna compra puede tener CorrelationId 5849 y un TraceId tecnico distinto. Cada paso tiene un SpanId propio." },
  { id: "instrumentation", label: "7) Instrumentacion", title: "Configurar trazas en .NET", subtitle: "ASP.NET, HttpClient, runtime y process pueden instrumentarse con OpenTelemetry.", chip: "NET", content: "Paquetes habituales:\nOpenTelemetry.Extensions.Hosting\nOpenTelemetry.Exporter.Otlp\nOpenTelemetry.Instrumentation.AspNetCore\nOpenTelemetry.Instrumentation.Http\nOpenTelemetry.Instrumentation.Runtime\nOpenTelemetry.Instrumentation.Process\n\nCon AddOpenTelemetry y AddTracing configuramos la exportacion OTLP." },
  { id: "activity-source", label: "8) ActivitySource", title: "Crear spans propios", subtitle: "Las operaciones de negocio necesitan spans manuales ademas de la instrumentacion automatica.", chip: "Instrumentation", content: "public static class Telemetry\n{\n    public const string ServiceName = \"OrderFlow\";\n    public static readonly ActivitySource ActivitySource =\n        new(ServiceName);\n}\n\nusing var activity =\n    Telemetry.ActivitySource.StartActivity(\"Confirm Order\");" },
  { id: "tags", label: "9) Tags", title: "Agregar contexto util", subtitle: "Los tags permiten filtrar y analizar trazas por orden, cliente, monto o servicio.", chip: "Tracing", content: "activity?.SetTag(\"order.id\", order.Id);\nactivity?.SetTag(\"customer.id\", order.CustomerId);\nactivity?.SetTag(\"order.total\", order.Total);\n\nNo agregamos datos sensibles. Los nombres deben ser estables para consultar desde Grafana o Jaeger." },
  { id: "errors", label: "10) Errores", title: "Registrar fallos en la traza", subtitle: "Una excepcion debe marcar el span como Error y conservar su detalle tecnico sin filtrar secretos.", chip: "Errores", content: "try\n{\n    await ProcessAsync();\n}\ncatch (Exception ex)\n{\n    activity?.SetStatus(ActivityStatusCode.Error);\n    activity?.RecordException(ex);\n    throw;\n}\n\nLa traza muestra donde fallo la compra y cuanto tiempo llevaba ejecutandose." },
  { id: "rabbit", label: "11) RabbitMQ", title: "Instrumentar mensajes", subtitle: "Publicar y consumir eventos tambien debe formar parte de la misma historia tecnica.", chip: "Messaging", content: "Al publicar OrderConfirmed:\n\nStartActivity(\"Publish OrderConfirmed\")\n\nmessaging.system = rabbitmq\nmessaging.destination = orders.events\n\nAl consumir ReserveInventory:\n\nStartActivity(\"Consume ReserveInventory\")\n\nCada span debe incluir MessageId y CorrelationId." },
  { id: "propagation", label: "12) Propagacion", title: "Continuar la misma traza", subtitle: "Orders y Inventory deben compartir TraceContext aunque se comuniquen por RabbitMQ.", chip: "Context", content: "Orders publica un mensaje.\nInventory lo consume.\n\nRabbitMQ transporta headers:\ntraceparent\ntracestate\n\nEl consumidor extrae el contexto y crea un span hijo o vinculado. Asi la traza cruza procesos y servicios." },
  { id: "logs", label: "13) Logs", title: "Logs estructurados", subtitle: "Los logs deben poder filtrarse por propiedades sin parsear textos manualmente.", chip: "Logging", content: "Evitar:\n_logger.LogInformation(\"Order confirmed.\");\n\nPreferir:\n_logger.LogInformation(\n    \"Order confirmed. OrderId {OrderId} Customer {CustomerId}\",\n    order.Id, order.CustomerId);\n\nLas propiedades quedan disponibles para buscar OrderId=5849." },
  { id: "sensitive", label: "14) Datos sensibles", title: "Que nunca registrar", subtitle: "La observabilidad no debe convertirse en una fuga de credenciales o datos financieros.", chip: "Seguridad", content: "Nunca registrar:\nPasswords\nJWT completos\nTarjetas\nCVV\nRefresh Tokens\nAPI Keys\nPaymentMethodToken\n\nAntes de serializar un objeto completo, revisamos que no contenga secretos ni datos personales innecesarios." },
  { id: "safe-logs", label: "15) Contexto seguro", title: "Que si registrar", subtitle: "Los identificadores tecnicos y funcionales permiten investigar sin exponer secretos.", chip: "Logging", content: "OrderId\nCustomerId\nCorrelationId\nTraceId\nSagaId\nPaymentId\nInventoryReservationId\nElapsedMilliseconds\nServiceName\nEventType\nMessageId\n\nEl mismo contexto debe aparecer en logs, spans y mensajes." },
  { id: "metrics", label: "16) Metricas", title: "Responder con numeros", subtitle: "Las metricas muestran frecuencia, duracion y volumen sin leer cada log individual.", chip: "Metrics", content: "Preguntas utiles:\nCuantas compras por minuto?\nCuantos pagos fallan?\nCuanto tarda Inventory?\nCuantas compensaciones ocurren?\nCuantos mensajes hay pendientes?\n\nLas metricas son series temporales agregadas y de bajo costo de consulta." },
  { id: "counter", label: "17) Counter", title: "Contar eventos", subtitle: "Un Counter mide cantidades acumuladas como ordenes creadas, pagos aprobados o fallos.", chip: "Metrics", content: "Meter meter = new(\"OrderFlow\");\nCounter<long> ordersCreated =\n    meter.CreateCounter<long>(\"orders.created\");\n\nordersCreated.Add(1);\n\nOtros counters:\norders.completed\npayments.approved\npayments.rejected\nsaga.compensated" },
  { id: "histogram", label: "18) Histogram", title: "Medir duraciones", subtitle: "Los histogramas permiten conocer promedio, percentiles y colas lentas.", chip: "Metrics", content: "Histogram<double> paymentTime =\n    meter.CreateHistogram<double>(\"payments.duration\");\n\npaymentTime.Record(stopwatch.ElapsedMilliseconds);\n\nMedir:\nHTTP\nSQL\nRabbitMQ\nPayment Provider\nSaga\nTiempo total de compra" },
  { id: "gauge", label: "19) Gauge", title: "Valores actuales", subtitle: "Un gauge representa una cantidad que sube y baja, como ordenes pendientes o stock reservado.", chip: "Metrics", content: "Ejemplos:\nOrdenes pendientes\nMensajes Outbox pendientes\nSagas activas\nReservas actuales\nWorkers disponibles\n\nA diferencia del Counter, el Gauge representa el valor observado en ese momento." },
  { id: "catalog-metrics", label: "20) Catalogo de metricas", title: "Metricas por servicio", subtitle: "Nombres consistentes permiten crear dashboards y alertas que sobreviven a nuevos despliegues.", chip: "Dashboard", content: "Orders:\norders.created\norders.completed\norders.failed\n\nInventory:\ninventory.reserved\ninventory.released\ninventory.failed\n\nPayments:\npayments.approved\npayments.rejected\npayments.pending\n\nSaga:\nsaga.completed\nsaga.compensated\nsaga.timeout\nsaga.manual" },
  { id: "dashboard", label: "21) Dashboard", title: "Ver el sistema de un vistazo", subtitle: "Grafana debe responder rapidamente si el problema es volumen, latencia, errores o compensaciones.", chip: "Grafana", content: "Paneles utiles:\nCompras por minuto\nTiempo promedio y p95\nCompensaciones\nErrores por servicio\nPagos rechazados\nStock reservado\nOutbox pendiente\nSagas atascadas\n\nUn dashboard orienta la investigacion antes de abrir trazas individuales." },
  { id: "alerts", label: "22) Alertas", title: "Convertir señales en acciones", subtitle: "Una alerta debe tener umbral, contexto, severidad y un runbook para responder.", chip: "Alerting", content: "Si payments.failed > 20% durante 5 minutos: alerta.\n\nSi Saga Timeout > 10: alerta.\n\nSi Outbox pendiente > 500 mensajes: alerta.\n\nTambien alertar por error rate, latencia p95, DLQ, RabbitMQ no disponible y crecimiento de ManualInterventionRequired." },
  { id: "health", label: "23) Health Checks", title: "Salud tecnica y salud funcional", subtitle: "El endpoint /health puede mostrar dependencias criticas y estados de infraestructura.", chip: "Health", content: "/health\n\nRabbitMQ: OK\nPostgreSQL: OK\nOutbox: OK\nSaga: Warning\nPayments: OK\n\nReadiness indica si el servicio puede recibir trafico. Liveness indica si el proceso sigue vivo. No confundimos ambos estados." },
  { id: "latency", label: "24) Duracion", title: "Encontrar el cuello de botella", subtitle: "La suma de spans permite explicar por que una compra tarda segundos o minutos.", chip: "Performance", content: "Trace completa: 1865 ms\n\nOrders: 15 ms\nInventory: 20 ms\nRabbitMQ: 5 ms\nPayments: 1820 ms\nComplete Order: 10 ms\n\nEl problema no esta en todas partes: esta en Payments. La observabilidad permite optimizar con evidencia." },
  { id: "correlation", label: "25) Correlacion", title: "Reconstruir una compra", subtitle: "Buscar un CorrelationId debe encontrar logs, spans, mensajes y estados de Saga relacionados.", chip: "Operabilidad", content: "CorrelationId = 5849\n\nBuscar 5849 encuentra:\nOrderConfirmed\nInventoryReserved\nPaymentApproved\nSaga state changes\nOutbox messages\nHTTP spans\nRabbitMQ spans\n\nLogs y traces juntos permiten contar la historia completa." },
  { id: "privacy", label: "26) Privacidad", title: "Observabilidad responsable", subtitle: "Más datos no siempre significa mejor observabilidad: debemos controlar retencion, acceso y cardinalidad.", chip: "Seguridad", content: "Evitar tags de alta cardinalidad sin necesidad.\nNo usar datos sensibles como labels.\nLimitar retencion de traces.\nProteger dashboards.\nRedactar errores.\nDefinir quien puede ver pagos y clientes.\n\nLa telemetria tambien es informacion del negocio." },
  { id: "testing", label: "27) Pruebas", title: "Verificar la instrumentacion", subtitle: "No basta con instalar paquetes: debemos comprobar que la traza realmente cruza servicios y mensajes.", chip: "Testing", content: "Crear una compra de prueba.\nComprobar TraceId en Orders.\nComprobar spans de SQL y HTTP.\nComprobar headers traceparent en RabbitMQ.\nComprobar que Inventory continua la traza.\nForzar fallo de Payment.\nVerificar span Error y excepcion.\nBuscar la compra por CorrelationId.\nValidar que no aparecen secretos." },
  { id: "checklist", label: "28) Checklist", title: "Validacion de observabilidad", subtitle: "La plataforma es observable cuando podemos explicar donde, cuanto y por que fallo una compra.", chip: "Checklist", content: "OpenTelemetry configurado\nActivitySource propio\nASP.NET y HttpClient instrumentados\nRabbitMQ instrumentado\nTraceContext propagado\nLogs estructurados\nSecretos excluidos\nCounters definidos\nHistograms de duracion\nGauges operativos\nDashboard Grafana\nAlertas con umbral\nHealth checks de dependencias\nCorrelationId consultable\nPruebas de flujo completo" },
  { id: "closing", label: "29) Cierre", title: "Como piensa un backend senior", subtitle: "Observabilidad no es agregar logs: es diseñar evidencia para entender sistemas distribuidos bajo presion.", chip: "Cierre", content: "Backend junior:\nMiro logs hasta encontrar algo raro.\n\nBackend senior:\nInstrumenta el flujo, propaga contexto, mide duraciones, define alertas y puede responder con evidencia donde se atasco una compra.\n\nSi no podemos seguir una orden, no sabemos realmente como esta funcionando el sistema." },
];

export default function Daily144Client() {
  const [activeSection, setActiveSection] = useState("idea");

  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement | null;
      if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return;
      if (event.key.toLowerCase() === "p") window.location.href = "/daily/143";
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, []);

  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);

  return (
    <div className={styles.page}>
      <header className={styles.topbar}><div className={styles.topbarInner}>
        <div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>OpenTelemetry, logs, metricas y trazas</div></div></div>
        <nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav>
        <div className={styles.actions}><Link className={styles.btn} href="/daily/143"><span className={styles.kbd}>←</span> Dia 143</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div>
      </div></header>
      <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}>
        <div className={styles.dailyHero}><div className={styles.createdAt}>30/07/2026</div><div className={styles.badge}>Daily #144 • Distributed Observability</div><h2 className={styles.title}>Observabilidad distribuida con OpenTelemetry, Logs, Métricas y Trazas</h2><p className={styles.lead}>La observabilidad permite seguir una compra completa, medir donde tarda y entender por que fallo sin revisar manualmente cada servicio.</p></div>
        <nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>
        {sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}
        <div className={styles.footerNav}><Link className={styles.btn} href="/daily/143"><span className={styles.kbd}>←</span> Dia 143</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div>
      </div></article></div></main>
    </div>
  );
}
