"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "goal", label: "1) Objetivo", title: "Un contrato tambien es codigo", subtitle: "Cuando los servicios se despliegan de forma independiente, el contrato es el acuerdo que permite evolucionarlos sin romper consumidores.", chip: "Contratos", content: "Orders -> Catalog\n\nOrders necesita:\nGET /products/{id}\n\nEl contrato define:\n- ruta y metodo\n- request\n- status codes\n- response body\n- campos obligatorios\n- errores\n\nNo es documentacion decorativa: es una dependencia ejecutable." },
  { id: "breaking", label: "2) Breaking changes", title: "Detectar cambios incompatibles", subtitle: "Un cambio rompe cuando un consumidor valido deja de poder interpretar o utilizar la respuesta.", chip: "Riesgo", content: "Breaking:\n- eliminar un campo usado\n- renombrar una propiedad\n- cambiar tipo\n- cambiar status code\n- hacer obligatorio un campo nuevo\n- modificar semantica\n\nCompatible:\n- agregar campo opcional\n- agregar endpoint\n- aceptar mas valores sin cambiar los existentes." },
  { id: "consumer", label: "3) Consumer-Driven", title: "El consumidor define lo que necesita", subtitle: "El contrato debe representar usos reales, no todos los detalles internos del proveedor.", chip: "CDC", content: "Consumer: Orders\n  | define expectativa\n  v\nContrato\n  | verifica\n  v\nProvider: Catalog\n\nEl consumidor expresa requests y respuestas relevantes. El proveedor verifica que su implementacion siga cumpliendolos." },
  { id: "minimal", label: "4) Contrato minimo", title: "Probar lo importante, no cada detalle", subtitle: "Un contrato demasiado amplio se vuelve frágil y dificulta evolucionar el servicio.", chip: "Diseño", content: "GET /products/{id}\n\nRequest:\nproductId valido\n\nResponse 200:\nid, sku, name, price\n\nResponse 404:\nerrorCode=PRODUCT_NOT_FOUND\n\nNo acoplarse a campos internos, timestamps variables o textos que no son parte del contrato." },
  { id: "pact", label: "5) Pact", title: "Automatizar Consumer-Driven Contracts", subtitle: "Pact permite que el consumidor publique expectativas y el proveedor las verifique en CI.", chip: "Pact", content: "1. Orders define interaccion.\n2. Se genera contrato.\n3. El contrato se publica en broker.\n4. Catalog ejecuta la verificacion.\n5. CI informa compatibilidad.\n\nSi Catalog elimina un campo necesario, el pipeline detecta el problema antes del deploy." },
  { id: "flow", label: "6) Flujo", title: "Orders y Catalog", subtitle: "El valor aparece cuando ambos equipos pueden desplegar con evidencia de compatibilidad.", chip: "Microservicios", content: "Orders consumer test\n  -> espera GET /products/{id}\n  -> guarda contrato\n\nCatalog provider verification\n  -> levanta API\n  -> ejecuta contrato\n  -> valida respuestas\n\nEl test no necesita que ambos servicios esten desplegados a la vez." },
  { id: "integration", label: "7) Diferencias", title: "Contract Test no es Integration Test", subtitle: "Cada tipo de prueba responde una pregunta distinta.", chip: "Testing", content: "Contract:\nEl servicio cumple el acuerdo esperado?\n\nIntegration:\nLas piezas reales funcionan juntas con infraestructura real?\n\nE2E:\nEl recorrido completo del negocio funciona?\n\nUsar los tres cuando el riesgo lo justifica, sin convertir uno en sustituto de todos." },
  { id: "dotnet", label: "8) .NET", title: "Contratos sobre DTOs, no entidades", subtitle: "Las entidades del dominio pueden evolucionar internamente sin romper el contrato publico.", chip: ".NET", content: "public sealed record ProductResponse(\n    Guid Id,\n    string Sku,\n    string Name,\n    decimal Price);\n\nEl contrato debe usar DTOs estables. No exponer entidades EF, proxies, relaciones internas ni detalles de persistencia." },
  { id: "shared", label: "9) Shared libraries", title: "Cuidado con compartir todos los DTOs", subtitle: "Una libreria comun puede ocultar cambios incompatibles y acoplar los ciclos de despliegue.", chip: "Acoplamiento", content: "Compartir contratos puede ser util para schemas estables, pero una libreria que contiene toda la implementacion obliga a actualizar consumidores juntos.\n\nPreferir contrato explicito, versionado y validacion automatica. Compartir solo lo que realmente representa un acuerdo." },
  { id: "events", label: "10) Eventos", title: "Los mensajes tambien tienen contrato", subtitle: "RabbitMQ no elimina la necesidad de versionar y validar payloads.", chip: "Mensajeria", content: "OrderConfirmed\n{\n  orderId,\n  occurredAt,\n  total\n}\n\nEl consumidor necesita conocer nombre, routing key, campos, tipos y semantica. Un evento es una API asincrona y merece el mismo rigor." },
  { id: "event-breaking", label: "11) Eventos versionados", title: "Evolucionar sin romper consumidores", subtitle: "Los eventos deben mantener compatibilidad hacia atras o introducir una version nueva.", chip: "Versionado", content: "OrderConfirmed.v1\nOrderConfirmed.v2\n\nOpciones:\n- agregar campos opcionales\n- mantener semantica anterior\n- publicar ambas versiones durante migracion\n- retirar v1 con fecha y consumidores conocidos\n\nNunca cambiar silenciosamente el significado de un campo." },
  { id: "schema", label: "12) Schema", title: "Validar estructura y escenarios", subtitle: "El schema comprueba tipos y forma; los escenarios comprueban comportamiento contractual.", chip: "Schema", content: "Producto existente -> 200 + campos esperados\nProducto inexistente -> 404 + error code\nProducto inactivo -> comportamiento acordado\nPayload invalido -> error contractual\n\nValidar tambien propiedades que no deben aparecer, seguridad y compatibilidad." },
  { id: "cicd", label: "13) CI/CD", title: "El contrato debe bloquear releases incompatibles", subtitle: "La verificacion ocurre antes del despliegue, no despues de que el consumidor falle en produccion.", chip: "CI/CD", content: "Commit consumer\n  -> generar contrato\n  -> publicar\n  -> provider verification\n  -> aprobar o bloquear\n  -> deploy independiente\n\nRegistrar provider version, consumer version, resultado y compatibilidad. Un contrato fallido requiere decision explicita." },
  { id: "third-party", label: "14) Externos", title: "Proteger integraciones de terceros", subtitle: "Los contratos tambien ayudan cuando dependemos de APIs externas, aunque no controlemos su despliegue.", chip: "Terceros", content: "Definir adaptador propio:\nProveedor externo -> Adapter -> OrderFlow\n\nProbar el contrato del adaptador y conservar fixtures de respuestas reales. Para cambios del proveedor, ejecutar verificaciones y revisar manualmente los casos que no pueden simularse." },
  { id: "checklist", label: "15) Checklist", title: "Contrato confiable", subtitle: "Un contrato es util cuando es pequeño, versionado, ejecutable y pertenece a consumidores reales.", chip: "Checklist", content: "Consumidor identificado\nRequest y response definidos\nStatus codes acordados\nErrores estructurados\nDTOs publicos separados\nCasos felices y fallos\nEventos versionados\nSchema validado\nProvider verification\nCI bloquea breaking changes\nCompatibilidad hacia atras\nPlan de retirada\nSin entidades internas expuestas" },
  { id: "closing", label: "16) Cierre", title: "Los contratos permiten desplegar sin miedo", subtitle: "La independencia entre microservicios existe cuando los cambios se validan contra las expectativas reales.", chip: "Cierre", content: "Backend junior:\nCambio el DTO y veo si algo falla.\n\nBackend senior:\nIdentifica consumidores, define el contrato, prueba escenarios relevantes, versiona eventos, verifica en CI y despliega de forma independiente.\n\nContract Testing convierte compatibilidad en evidencia automatica." },
];

export default function Daily154Client() {
  const [activeSection, setActiveSection] = useState("goal");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/153"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Contract Testing entre microservicios</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/153"><span className={styles.kbd}>←</span> Dia 153</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>17/08/2026</div><div className={styles.badge}>Daily #154 • Contract Testing</div><h2 className={styles.title}>Contract Testing entre microservicios</h2><p className={styles.lead}>Proteger APIs y eventos para que Orders, Catalog y el resto de servicios puedan evolucionar y desplegarse de forma independiente.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/153"><span className={styles.kbd}>←</span> Dia 153</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
