"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "goal", label: "1) Objetivo", title: "Dejar AWS local funcionando", subtitle: "Hoy construimos un laboratorio estable para practicar sin cuenta real, costes accidentales ni infraestructura olvidada.", chip: "Practica", content: "Terminal\n   |\n   v\nAWS CLI\n   |\n   v\nFloci\nlocalhost:4566\n   |\n   +-- S3\n   +-- SQS\n\nEl criterio es completar pruebas reales, no solo instalar la herramienta." },
  { id: "requirements", label: "2) Requisitos", title: "Docker, AWS CLI y curl", subtitle: "Comprobar las herramientas antes de iniciar evita diagnosticar problemas equivocados.", chip: "Preparacion", content: "docker --version\ndocker compose version\naws --version\ncurl --version\ndocker ps\n\nDocker debe responder sin errores. El laboratorio vivira en:\n\nmkdir -p ~/aws-local\ncd ~/aws-local" },
  { id: "install", label: "3) Instalacion", title: "Instalar la CLI oficial de Floci", subtitle: "La CLI inicia el runtime, consulta su estado y genera la configuracion del entorno.", chip: "CLI", content: "curl -fsSL https://floci.io/install.sh | sh\nfloci version\n\nLa herramienta tambien puede actualizarse con:\nfloci update\n\nRevisar siempre el instalador y la documentacion del proyecto antes de usarlo en un equipo nuevo." },
  { id: "start", label: "4) Arranque", title: "Iniciar Floci con Docker", subtitle: "La CLI descarga la imagen, crea el contenedor y espera a que el endpoint este preparado.", chip: "Runtime", content: "docker ps\nfloci start\n\nEndpoint por defecto:\nhttp://localhost:4566\n\nLa configuracion puede seleccionar servicios, cambiar el puerto y activar persistencia." },
  { id: "status", label: "5) Estado", title: "Comprobar que el entorno esta sano", subtitle: "Status, doctor y logs permiten distinguir un fallo de Floci de un fallo del cliente.", chip: "Diagnostico", content: "floci status\nfloci doctor\nfloci logs\n\nPrimero comprobar el runtime, despues la conectividad y finalmente el servicio concreto que estamos probando." },
  { id: "env", label: "6) Entorno", title: "Apuntar AWS CLI a localhost", subtitle: "Las variables evitan que los comandos creen recursos en AWS real durante el aprendizaje.", chip: "Configuracion", content: "eval \"$(floci env)\"\nenv | grep AWS\n\nVariables esperadas:\nAWS_ENDPOINT_URL\nAWS_ACCESS_KEY_ID\nAWS_SECRET_ACCESS_KEY\nAWS_DEFAULT_REGION\n\nLas credenciales son de prueba y solo sirven para el laboratorio local." },
  { id: "smoke", label: "7) Smoke test", title: "Verificar la comunicacion", subtitle: "Una respuesta de STS confirma que el AWS CLI esta hablando con el emulador.", chip: "Validacion", content: "aws sts get-caller-identity\n\nSi recibimos JSON, el camino esta activo:\nAWS CLI -> Floci\n\nEste test debe formar parte de la rutina de arranque y del diagnostico de CI." },
  { id: "s3", label: "8) S3", title: "Crear, subir y descargar un archivo", subtitle: "La primera prueba real valida almacenamiento de objetos de principio a fin.", chip: "S3", content: "aws s3 mb s3://orderflow-local\naws s3 ls\necho \"Hola desde Floci\" > prueba.txt\naws s3 cp prueba.txt s3://orderflow-local/prueba.txt\naws s3 cp s3://orderflow-local/prueba.txt ./descargado.txt\ncat descargado.txt\n\nDebe coincidir el contenido local y remoto." },
  { id: "sqs", label: "9) SQS", title: "Crear una cola y recorrer un mensaje", subtitle: "La segunda prueba conecta producer, cola y consumer en el entorno local.", chip: "SQS", content: "aws sqs create-queue --queue-name orderflow-orders\naws sqs list-queues\n\nEnviar:\naws sqs send-message --queue-url <QUEUE_URL> --message-body \"order-created\"\n\nLeer:\naws sqs receive-message --queue-url <QUEUE_URL>\n\nEliminar despues de procesar correctamente:\naws sqs delete-message --queue-url <QUEUE_URL> --receipt-handle <HANDLE>" },
  { id: "persistence", label: "10) Persistencia", title: "Conservar el estado del laboratorio", subtitle: "La persistencia permite reiniciar Floci sin perder recursos creados durante las practicas.", chip: "Docker", content: "Persistir el directorio o volumen que soporte el runtime local.\n\nPrueba:\n1. Crear bucket y cola.\n2. Detener Floci.\n3. Iniciarlo de nuevo.\n4. Comprobar que siguen existiendo.\n\nSi el entorno se destruye siempre, el laboratorio no representa un flujo de trabajo diario real." },
  { id: "routine", label: "11) Rutina", title: "Arrancar, comprobar, trabajar y detener", subtitle: "Una rutina corta y repetible reduce errores y hace que el laboratorio sea util de verdad.", chip: "Operacion", content: "Arrancar:\nfloci start\n\nComprobar:\nfloci status\nfloci doctor\n\nTrabajar:\naws s3 ...\naws sqs ...\n\nLogs:\nfloci logs\n\nDetener cuando corresponda:\nfloci stop" },
  { id: "scripts", label: "12) Automatizacion", title: "Crear scripts de arranque y smoke test", subtitle: "Los comandos importantes deben poder ejecutarse de forma automatica y documentada.", chip: "Scripts", content: "start-local.sh:\n- arrancar Floci\n- esperar readiness\n- cargar variables\n- ejecutar doctor\n\nsmoke-test.sh:\n- ejecutar STS\n- crear o localizar bucket\n- subir y descargar archivo\n- crear cola\n- enviar y recibir mensaje\n- devolver codigo distinto de cero si falla" },
  { id: "success", label: "13) Exito", title: "Criterio de terminado", subtitle: "El laboratorio esta listo cuando otra persona puede repetirlo desde una maquina limpia.", chip: "QA", content: "Docker responde\nFloci inicia\nEndpoint localhost:4566 disponible\nAWS CLI usa el endpoint local\nSTS devuelve JSON\nS3 crea bucket\nS3 sube y descarga archivo\nSQS crea cola\nSQS envia y recibe mensaje\nMensaje se elimina tras procesarlo\nPersistencia verificada\nSmoke test automatizado" },
  { id: "limits", label: "14) Limites", title: "El emulador no es AWS real", subtitle: "Floci acelera el desarrollo, pero no reproduce todas las propiedades de una nube distribuida.", chip: "Realidad", content: "Pueden existir diferencias en:\n- rendimiento\n- networking\n- IAM real\n- limites\n- disponibilidad\n- comportamiento bajo carga\n\nUsar Floci para desarrollo y testing. Validar en staging real las caracteristicas propias de AWS." },
  { id: "troubleshooting", label: "15) Problemas", title: "Troubleshooting rapido", subtitle: "Los fallos mas comunes suelen estar en la CLI, Docker, el puerto o el endpoint activo.", chip: "Soporte", content: "floci: command not found -> revisar instalacion y PATH.\nDocker no responde -> comprobar docker ps y el daemon.\nPuerto ocupado -> revisar el proceso o configurar otro puerto.\nAWS conecta a real -> ejecutar floci env y revisar AWS_ENDPOINT_URL.\nAlgo falla -> usar floci status, doctor y logs.\nReinicio completo -> detener y volver a iniciar el runtime." },
  { id: "not-yet", label: "16) Siguiente", title: "Que no hacemos todavia", subtitle: "Primero estabilizamos el laboratorio antes de convertirlo en una plataforma compleja.", chip: "Alcance", content: "Todavia no:\n- reproducir toda AWS\n- medir equivalencia de rendimiento\n- reemplazar staging real\n- desplegar Kubernetes local\n- crear una arquitectura innecesaria\n\nPrimero: S3, SQS, persistencia, scripts y tests repetibles." },
  { id: "closing", label: "17) Cierre", title: "Un laboratorio reproducible acelera el aprendizaje", subtitle: "La practica cloud empieza cuando podemos levantar el entorno, probarlo y destruirlo con confianza.", chip: "Cierre", content: "El flujo completo:\nDocker -> Floci -> AWS CLI -> S3/SQS -> smoke tests\n\nLa misma aplicacion puede cambiar de local a AWS real mediante configuracion. El contrato de negocio permanece y el entorno deja de ser una barrera para experimentar." },
];

export default function Daily151Client() {
  const [activeSection, setActiveSection] = useState("goal");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/149"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Montar Floci desde cero</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/149"><span className={styles.kbd}>←</span> Dia 149</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>12/08/2026</div><div className={styles.badge}>Daily #151 • AWS Local Lab</div><h2 className={styles.title}>Montar Floci desde cero y dejar AWS local funcionando</h2><p className={styles.lead}>Docker, Floci, AWS CLI, S3 y SQS: un laboratorio local reproducible para practicar cloud y preparar integration tests.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/149"><span className={styles.kbd}>←</span> Dia 149</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
