"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "pause", label: "1) Pausa", title: "Cambiar temporalmente de contexto", subtitle: "La ruta .NET queda en pausa para estudiar otra plataforma empresarial con el mismo rigor de backend.", chip: "Transicion", content: "Hasta ahora:\n.NET, Docker, Kubernetes, AWS, testing y microservicios.\n\nAhora:\nOdoo 17, PostgreSQL, ORM, modelos, seguridad, vistas, integraciones y tests.\n\nLa meta no es abandonar lo aprendido, sino entender otro ecosistema empresarial desde sus capas internas." },
  { id: "odoo", label: "2) Odoo", title: "Que es Odoo", subtitle: "Odoo es una plataforma ERP extensible donde los modulos implementan procesos de negocio completos.", chip: "Odoo 17", content: "Usuarios\n  |\nOdoo Server\n  |\nRegistry + Environment + ORM\n  |\nPostgreSQL\n  |\nAddons\n\nUn desarrollador backend trabaja con modelos, permisos, transacciones, datos, vistas y extensiones del sistema." },
  { id: "app-module", label: "3) Aplicacion y modulo", title: "No confundir una aplicacion con un modulo", subtitle: "Una aplicacion agrupa una capacidad de negocio; un modulo es la unidad tecnica instalable y extensible.", chip: "Arquitectura", content: "Aplicacion: Field Service\n  |\nModulo: fieldops\n  +-- models\n  +-- views\n  +-- security\n  +-- data\n  +-- reports\n  +-- tests\n\nEl modulo debe tener manifest, dependencias, modelos y una instalacion reproducible." },
  { id: "backend", label: "4) Perspectiva backend", title: "Como pensar dentro de Odoo", subtitle: "El framework resuelve parte de la infraestructura, pero las reglas de dominio siguen siendo responsabilidad del desarrollador.", chip: "Backend", content: "Modelo = entidad y comportamiento\nField = dato y metadato\nORM = persistencia y recordsets\nEnvironment = contexto de ejecucion\nSecurity = ACL + Record Rules\nViews = presentacion del modelo\n\nNo editar el core: extender mediante herencia, composicion y contratos del framework." },
  { id: "fieldops", label: "5) Proyecto", title: "FieldOps 360", subtitle: "Un modulo empresarial para vender equipos y prestar instalacion, mantenimiento y reparacion.", chip: "FieldOps", content: "Clientes\n   |\n   v\nEquipos instalados\n   |\n   v\nTickets de servicio\n   |\n   v\nOrdenes de trabajo\n   |\n   +-- tecnico\n   +-- materiales\n   +-- horas\n   +-- coste\n   |\n   v\nCierre e informe PDF" },
  { id: "problem", label: "6) Problema", title: "El dominio antes que la pantalla", subtitle: "FieldOps debe representar el proceso real y sus responsabilidades antes de crear vistas bonitas.", chip: "Dominio", content: "La empresa vende equipos.\nLos equipos se instalan en clientes.\nLos clientes reportan problemas.\nUn supervisor asigna trabajo.\nUn tecnico diagnostica y repara.\nEl sistema registra materiales, horas y coste.\nEl trabajo se cierra con informe.\n\nCada frase puede convertirse en modelo, relacion, estado o regla." },
  { id: "actors", label: "7) Actores", title: "Definir quien hace que", subtitle: "Los actores ayudan a diseñar permisos, estados, acciones y experiencia operativa.", chip: "Roles", content: "Tecnico:\nconsulta equipos y ejecuta trabajos.\n\nSupervisor:\nasigna tecnicos, revisa tickets y controla ordenes.\n\nAdministrador FieldOps:\nconfigura catalogos, seguridad, companias y reglas globales.\n\nEstos roles seran parte del modelo de autorizacion, no solo etiquetas de interfaz." },
  { id: "flow", label: "8) Flujo", title: "El flujo funcional principal", subtitle: "La primera version debe recorrer un proceso completo y medible de servicio.", chip: "Workflow", content: "Cliente reporta problema\n        |\n        v\nTicket\n        |\n        v\nSupervisor asigna tecnico\n        |\n        v\nOrden de trabajo\n        |\n        v\nDiagnostico -> Reparacion\n        |\n        v\nCierre -> Informe PDF" },
  { id: "domain", label: "9) Dominio", title: "Primeros conceptos de dominio", subtitle: "Antes de programar hay que decidir entidades, relaciones, estados y reglas invariantes.", chip: "Modelado", content: "Cliente: res.partner extendido.\nEquipo: numero de serie, estado, garantia y cliente.\nTicket: problema reportado, prioridad y estado.\nWork Order: tecnico, horas, materiales, coste y cierre.\n\nPreguntas:\n- puede existir un equipo sin cliente?\n- puede cerrarse una orden sin diagnostico?\n- quien puede reasignar tecnico?\n- como se calcula el coste?" },
  { id: "first-change", label: "10) Primera mejora", title: "Empezar por equipos instalados", subtitle: "El primer incremento sera un modelo pequeno pero conectado con una necesidad real.", chip: "Milestone", content: "fieldops.equipment\n\nCampos iniciales:\n- name\n- serial_number\n- partner_id\n- installation_date\n- state\n- warranty_until\n- notes\n\nDespues añadiremos tecnicos, intervenciones, computed fields, constraints, vistas y seguridad." },
  { id: "scope", label: "11) Alcance", title: "Lo que no haremos todavia", subtitle: "Un proyecto profesional tambien sabe decir que queda fuera de la primera iteracion.", chip: "Scope", content: "Todavia no:\n- construir todo el ERP\n- modificar el core de Odoo\n- crear pantallas sin dominio\n- añadir integraciones prematuras\n- ignorar permisos\n- copiar un ejemplo de todo.task\n\nPrimero: un flujo FieldOps pequeno, coherente, testeable y ampliable." },
  { id: "qa", label: "12) QA", title: "Calidad desde el primer modelo", subtitle: "Cada incremento debe poder demostrarse con reglas, permisos, tests y una ruta de instalacion clara.", chip: "QA", content: "Modelo valido\nSerie duplicada bloqueada\nFecha consistente\nPermisos por rol\nVista instalable\nDatos reproducibles\nUpgrade comprobado\nTest de dominio\nDocumentacion actualizada\n\nNo esperar al dia 27 para empezar a comprobar calidad." },
  { id: "roadmap", label: "13) Ruta", title: "Los siguientes pasos", subtitle: "La ruta de 30 dias llevara FieldOps desde el primer modelo hasta un modulo demostrable de portfolio.", chip: "Roadmap", content: "ORM y recordsets\nFields y relaciones\nComputed y constraints\nHerencia de res.partner\nViews, XML y XPath\nTickets y Work Orders\nSeguridad y multi-company\nChatter, wizard y cron\nQWeb, controller y tests\nDocker, upgrade y release" },
  { id: "checklist", label: "14) Checklist", title: "Definicion de la primera fase", subtitle: "La fase inicial termina cuando el modelo de equipos puede instalarse y representar el negocio.", chip: "Checklist", content: "Modulo fieldops creado\nManifest valido\nDependencias declaradas\nModelo equipment\nCliente relacionado\nEstados definidos\nConstraint de serie\nVistas iniciales\nMenu operativo\nPermisos basicos\nTest principal\nDocumentacion de instalacion" },
  { id: "closing", label: "15) Cierre", title: "Un ERP tambien es backend", subtitle: "Odoo cambia las herramientas, pero mantiene las preguntas esenciales sobre dominio, datos, seguridad y operacion.", chip: "Cierre", content: "Backend junior:\nCreo un modelo y una pantalla.\n\nBackend senior:\nEntiende el proceso, define invariantes, controla permisos, prueba transacciones, extiende sin romper el core y prepara el modulo para evolucionar.\n\nFieldOps 360 sera nuestra pieza de trabajo acumulativa." },
];

export default function Daily156Client() {
  const [activeSection, setActiveSection] = useState("pause");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/155"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Odoo 17 desde la perspectiva backend</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/155"><span className={styles.kbd}>←</span> Dia 155</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>19/08/2026</div><div className={styles.badge}>Daily #156 • Odoo 17</div><h2 className={styles.title}>Odoo 17 desde la perspectiva de un desarrollador backend</h2><p className={styles.lead}>Una pausa temporal en la ruta .NET para iniciar FieldOps 360, un modulo empresarial que crecera durante 30 dias.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/155"><span className={styles.kbd}>←</span> Dia 155</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
