"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "problem", label: "1) Problema", title: "El costo real no es solo la factura", subtitle: "Flete, nacionalizacion y transporte tambien son necesarios para vender la mercancia.", chip: "Contexto", content: "Productos comprados     $10,000\nFlete                     2,000\nNacionalizacion           1,000\nTransportacion              500\nGastos adicionales        $3,500\n\nCosto real de la importacion = $13,500" },
  { id: "lines", label: "2) Lineas", title: "Cada linea necesita su valor de compra", subtitle: "La cantidad y el precio unitario permiten conocer cuanto pesa cada producto en la importacion.", chip: "Modelo", content: "unit_purchase_price = fields.Monetary(\n    required=True,\n    currency_field='currency_id',\n)\n\npurchase_subtotal = quantity * unit_purchase_price" },
  { id: "currency", label: "3) Moneda", title: "La moneda debe ser explicita", subtitle: "Importacion, lineas y gastos deben compartir una moneda bien definida.", chip: "Datos", content: "currency_id = fields.Many2one(\n    'res.currency',\n    required=True,\n    default=lambda self: self.env.company.currency_id,\n)\n\nLos Monetary fields deben apuntar a currency_id." },
  { id: "expenses", label: "4) Gastos", title: "Modelar los gastos como registros", subtitle: "Una entidad separada permite agregar tipos, importes y trazabilidad sin sobrecargar la cabecera.", chip: "ORM", content: "class TradeImportExpense(models.Model):\n    _name = 'trade.import.expense'\n\n    import_id = fields.Many2one(\n        'trade.import', required=True, ondelete='cascade')\n    expense_type = fields.Selection([...], required=True)\n    amount = fields.Monetary(currency_field='currency_id')" },
  { id: "relation", label: "5) Relacion", title: "Importacion, productos y gastos", subtitle: "La relacion One2many hace visible el costo completo de una operacion.", chip: "Relaciones", content: "trade.import\n  +-- line_ids\n  |   +-- Producto A\n  |   +-- Producto B\n  +-- expense_ids\n      +-- Flete\n      +-- Nacionalizacion\n      +-- Transporte" },
  { id: "totals", label: "6) Totales", title: "Calcular los totales de la cabecera", subtitle: "El total de compra y los gastos deben actualizarse cuando cambien lineas o gastos.", chip: "Computed", content: "purchase_total = sum(line.purchase_subtotal\n                      for line in record.line_ids)\nadditional_cost = sum(expense.amount\n                      for expense in record.expense_ids)\ntotal_landed_cost = purchase_total + additional_cost" },
  { id: "ratio", label: "7) Prorrateo", title: "Distribuir por proporcion del valor", subtitle: "Cada linea recibe una parte de los gastos equivalente a su peso sobre la mercancia.", chip: "Formula", content: "line_ratio = line.purchase_subtotal / purchase_total\nline.additional_cost = (\n    line_ratio * additional_cost\n)\nline.real_cost = line.purchase_subtotal + line.additional_cost" },
  { id: "example", label: "8) Ejemplo", title: "La suma debe cuadrar", subtitle: "El prorrateo conserva el total y hace visible el costo final de cada producto.", chip: "Calculo", content: "Producto A = $8,000 -> 80% -> $2,800\nProducto B = $2,000 -> 20% ->   $700\n\nCosto A = $10,800\nCosto B =  $2,700\nTotal    = $13,500" },
  { id: "depends", label: "9) Dependencias", title: "Computed fields con dependencias completas", subtitle: "Odoo solo puede recalcular de forma fiable si @api.depends incluye todos los campos usados.", chip: "Odoo", content: "@api.depends(\n    'line_ids.quantity',\n    'line_ids.unit_purchase_price',\n    'expense_ids.amount',\n)\ndef _compute_landed_cost(self):\n    for record in self:\n        # calcular totales y distribuir gastos\n        ..." },
  { id: "validation", label: "10) Validaciones", title: "Evitar prorrateos imposibles", subtitle: "Una importacion sin valor de compra no puede distribuir gastos proporcionalmente.", chip: "Constraints", content: "Validar en servidor:\n- quantity > 0\n- unit_purchase_price >= 0\n- expense amount >= 0\n- purchase_total > 0 antes de prorratear\n- currency_id consistente\n\nRechazar datos invalidos con ValidationError." },
  { id: "rounding", label: "11) Redondeo", title: "El redondeo tambien es una regla", subtitle: "Los centavos pueden provocar diferencias; el sistema debe decidir donde ajustar el residuo.", chip: "Precision", content: "La suma de additional_cost por linea\ndebe coincidir con additional_cost total.\n\nOpciones:\n- ajustar la ultima linea\n- asignar el residuo a la linea mayor\n- usar precision monetaria de Odoo\n\nLa decision debe ser determinista." },
  { id: "edge", label: "12) Fronteras", title: "Casos que deben probarse", subtitle: "Los casos pequenos y extremos descubren errores de division, precision y atomicidad.", chip: "QA", content: "- Una sola linea\n- Varias lineas con mismo valor\n- Gastos en cero\n- Precio cero si el negocio lo permite\n- Importacion vacia\n- Purchase total cero\n- Importes con muchos decimales\n- Eliminacion de una linea o gasto" },
  { id: "storage", label: "13) Persistencia", title: "Guardar el costo calculado con criterio", subtitle: "store=True facilita buscar y reportar, pero exige dependencias correctas y una estrategia de recalcule.", chip: "Persistencia", content: "purchase_subtotal = fields.Monetary(\n    compute='_compute_purchase_subtotal',\n    store=True,\n)\n\nreal_cost y additional_cost pueden almacenarse\nsi se usan en inventario, reportes o busquedas." },
  { id: "flow", label: "14) Flujo", title: "El costo acompana al proceso operativo", subtitle: "El costo real debe estar listo antes de recibir y valorar la mercancia.", chip: "TradeOps", content: "Crear importacion\n  -> agregar lineas y precios\n  -> registrar gastos\n  -> calcular costo real\n  -> validar totales\n  -> recibir mercancia\n  -> valorar inventario" },
  { id: "closing", label: "15) Cierre", title: "El costo real convierte datos en decisiones", subtitle: "Un backend profesional conserva el total, explica el reparto y protege las reglas financieras.", chip: "Cierre", content: "Checklist:\n- precio y moneda en lineas\n- gastos como entidad propia\n- totales calculados\n- prorrateo proporcional\n- redondeo determinista\n- constraints de servidor\n- pruebas de persistencia\n- total por linea = total de importacion" },
];

export default function Daily164Client() {
  const [activeSection, setActiveSection] = useState("problem");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/163"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Gastos de importacion y costo real</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/163"><span className={styles.kbd}>←</span> Dia 163</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>31/08/2026</div><div className={styles.badge}>Daily #164 • Odoo Costing</div><h2 className={styles.title}>Gastos de importacion y prorrateo del costo real</h2><p className={styles.lead}>Calcular cuanto cuesta realmente cada producto despues de distribuir proporcionalmente los gastos adicionales.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/163"><span className={styles.kbd}>←</span> Dia 163</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
