"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "problem", label: "1) Problema", title: "La venta necesita llegar al cliente", subtitle: "Tras convertir una preventa en venta, TradeOps debe organizar quién, cómo y desde dónde saldrá la entrega.", chip: "Contexto", content: "sale.order\n  -> entrega física\nstock.picking\n  -> movimiento de inventario\ntrade.distribution\n  -> planificación logística\n\nNo basta con vender: hay que coordinar almacén, chofer, vehículo y entrega." },
  { id: "boundary", label: "2) Frontera", title: "TradeOps planifica; Stock ejecuta", subtitle: "El módulo custom expresa el workflow empresarial sin duplicar el movimiento físico que ya resuelve Odoo.", chip: "Arquitectura", content: "TradeOps Distribution:\n- asigna chofer\n- asigna vehículo\n- define planificación\n- controla estados operativos\n\nOdoo Stock:\n- reserva productos\n- mueve existencias\n- confirma picking\n- registra entrega física" },
  { id: "distribution", label: "3) Distribution", title: "La distribución es una entidad propia", subtitle: "Representa la operación logística que conecta una venta con los recursos necesarios para entregarla.", chip: "Modelo", content: "class TradeDistribution(models.Model):\n    _name = 'trade.distribution'\n\n    sale_order_id = fields.Many2one(\n        'sale.order', required=True, ondelete='restrict')\n    warehouse_id = fields.Many2one('stock.warehouse')\n    driver_id = fields.Many2one('res.partner')\n    vehicle_id = fields.Many2one('fleet.vehicle')\n    state = fields.Selection([...])" },
  { id: "sale-order", label: "4) Venta", title: "sale.order conserva el contexto comercial", subtitle: "Vincular la distribución con la venta permite identificar cliente, líneas, origen y documentos relacionados.", chip: "Relaciones", content: "trade.distribution\n  -> sale_order_id\n      -> partner_id\n      -> order_line\n      -> picking_ids\n      -> origin\n\nLa distribución no necesita volver a copiar cliente ni productos." },
  { id: "warehouse", label: "5) Almacen", title: "El almacén determina desde dónde sale", subtitle: "stock.warehouse representa la estructura logística estándar y debe ser el origen de verdad para ubicaciones y operaciones.", chip: "Odoo Stock", content: "warehouse_id = fields.Many2one(\n    'stock.warehouse',\n    required=True,\n)\n\nEl almacén proporciona:\n- ubicaciones\n- tipos de operación\n- rutas\n- compañía\n- configuración de entregas" },
  { id: "driver", label: "6) Chofer", title: "Reutilizar res.partner con semántica", subtitle: "Un chofer puede ser un contacto estándar con una marca o rol específico para la operación logística.", chip: "Reutilizacion", content: "res.partner\n  +-- nombre\n  +-- teléfono\n  +-- compañía\n  +-- is_trade_driver\n\nNo crear trade.driver si no existen datos o comportamiento que justifiquen un agregado independiente." },
  { id: "vehicle", label: "7) Vehiculo", title: "Los vehículos también son recursos", subtitle: "El módulo Fleet de Odoo puede aportar la entidad estándar para asignar el transporte real.", chip: "Fleet", content: "vehicle_id = fields.Many2one(\n    'fleet.vehicle',\n    required=True,\n)\n\nTradeOps puede extender fleet.vehicle con campos propios, pero evita duplicar matrícula, mantenimiento y datos operativos." },
  { id: "workflow", label: "8) Workflow", title: "Estados claros para la distribución", subtitle: "La distribución necesita expresar planificación y ejecución sin confundirlas con el estado físico de stock.", chip: "Workflow", content: "draft\n  -> planned\n  -> dispatched\n  -> delivered\n\nAcciones:\n- planificar\n- despachar\n- marcar entregada\n- cancelar\n\nCada transición requiere precondiciones explícitas." },
  { id: "states", label: "9) Estados", title: "Qué significa cada estado", subtitle: "Los nombres son contratos del negocio y deben tener efectos y condiciones definidos.", chip: "Semantica", content: "Draft: creada, aún incompleta.\nPlanned: recursos válidos asignados.\nDispatched: salida operativa confirmada.\nDelivered: entrega finalizada.\n\nUn estado no es una etiqueta visual; comunica una garantía sobre el proceso." },
  { id: "source", label: "10) Source of Truth", title: "Cada dato tiene un dueño", subtitle: "El modelo de distribución no puede inventar ni sobrescribir estados que pertenecen a ventas o inventario.", chip: "Diseño", content: "Venta -> sale.order\nInventario físico -> stock.picking\nAlmacén -> stock.warehouse\nVehículo -> fleet.vehicle\nPlanificación de reparto -> trade.distribution\n\nConsultar y relacionar no es duplicar ni reemplazar el origen de verdad." },
  { id: "picking", label: "11) Picking", title: "Vincular la distribución al movimiento físico", subtitle: "La relación con stock.picking permite seguir la entrega sin crear líneas de stock custom.", chip: "Integracion", content: "picking_id = fields.Many2one(\n    'stock.picking',\n    required=True,\n    ondelete='restrict',\n)\n\nDistribution\n  -> sale.order\n  -> stock.picking\n  -> entrega física\n\nLa distribución observa y coordina el picking." },
  { id: "no-stock-copy", label: "12) Stock", title: "No duplicar líneas de inventario", subtitle: "Crear nuestras propias líneas para productos entregados dividiría el estado de inventario y generaría inconsistencias.", chip: "Boundary", content: "No crear:\ntrade.distribution.line\n  -> producto\n  -> cantidad entregada\n\ncuando stock.move ya es dueño de esa información.\n\nTradeOps añade workflow; Odoo Stock mantiene cantidades y movimientos." },
  { id: "business-vs-physical", label: "13) Dos flujos", title: "Workflow empresarial y estado físico no son iguales", subtitle: "Un reparto puede estar planificado aunque el picking no esté listo, o entregado comercialmente mientras se valida un detalle físico.", chip: "Modelo", content: "Distribución: planned / dispatched / delivered\nPicking: waiting / assigned / done / cancelled\n\nRelacionar ambos permite detectar contradicciones.\nNo forzar que tengan los mismos nombres ni las mismas transiciones." },
  { id: "preconditions", label: "14) Precondiciones", title: "Validar antes de planificar", subtitle: "Una planificación debe confirmar recursos y contexto correctos antes de cambiar el estado.", chip: "Reglas", content: "def action_plan(self):\n    self.ensure_one()\n    if not self.driver_id:\n        raise UserError('Debe asignar un chofer.')\n    if not self.vehicle_id:\n        raise UserError('Debe asignar un vehículo.')\n    if not self.warehouse_id:\n        raise UserError('Debe asignar un almacén.')\n    self.state = 'planned'" },
  { id: "risk", label: "15) Riesgo", title: "Evitar la mentira logística", subtitle: "No se debe marcar una distribución como despachada o entregada si el contexto físico y los recursos no respaldan la afirmación.", chip: "Integridad", content: "Errores a evitar:\n- dispatched sin chofer\n- dispatched sin vehículo\n- delivered con picking no realizado\n- almacén de otra compañía\n- resources inactivos\n\nEl workflow debe representar hechos verificables, no aspiraciones." },
  { id: "qa", label: "16) QA", title: "Probar reglas y consistencia entre modelos", subtitle: "La suite debe comprobar el resultado de la acción y el estado de los recursos relacionados.", chip: "QA", content: "Casos mínimos:\n- planificación correcta\n- sin chofer falla\n- sin vehículo falla\n- sin almacén falla\n- multi-company rechaza recursos ajenos\n- picking incompatible bloquea despacho\n- una acción fallida no cambia el estado\n- trazabilidad hacia venta y picking" },
  { id: "closing", label: "17) Cierre", title: "La logística se integra, no se inventa", subtitle: "TradeOps agrega el workflow de reparto sobre modelos estándar que ya conocen ventas, stock, almacenes y vehículos.", chip: "Cierre", content: "Regla mental:\n\nCrear el concepto empresarial propio.\nReutilizar los conceptos físicos estándar.\nDefinir quién es dueño de cada dato.\nValidar precondiciones antes de prometer una acción logística.\n\nAsí el reparto es operable y auditable." },
];

export default function Daily171Client() {
  const [activeSection, setActiveSection] = useState("problem");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/170"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Distribucion y workflow logistico</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/170"><span className={styles.kbd}>←</span> Dia 170</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>08/09/2026</div><div className={styles.badge}>Daily #171 • Odoo Logistics</div><h2 className={styles.title}>Distribución, choferes y workflow logístico</h2><p className={styles.lead}>Diseñar la planificación de entregas reutilizando ventas, almacenes, flota y movimientos de inventario de Odoo.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/170"><span className={styles.kbd}>←</span> Dia 170</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
