"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "problem", label: "1) Problema", title: "Una preventa necesita saber cuanto debe", subtitle: "Precios, pagos y disponibilidad deben producir información fiable sin depender de valores editados a mano.", chip: "Contexto", content: "Preventa\n  +-- lineas y precios\n  +-- total\n  +-- pagos registrados\n  +-- pendiente\n  +-- porcentaje pagado\n  +-- advertencia de sobrepreventa\n  +-- estado derivado\n\nEl modelo debe explicar su situación financiera y operativa." },
  { id: "source", label: "2) Fuente", title: "Dato fuente frente a dato derivado", subtitle: "Guardamos hechos de negocio; calculamos resultados que se pueden obtener de esos hechos.", chip: "Diseño", content: "Datos fuente:\n- cantidad de linea\n- precio unitario\n- pagos\n- stock importado\n\nDatos derivados:\n- subtotal\n- total\n- importe pagado\n- pendiente\n- porcentaje\n- estado\n\nNo guardar manualmente lo que el sistema puede calcular." },
  { id: "price", label: "3) Precio", title: "Cada linea debe expresar su valor", subtitle: "Cantidad y precio unitario permiten calcular el subtotal de forma determinista.", chip: "Monetary", content: "unit_price = fields.Monetary(\n    required=True,\n    currency_field='currency_id',\n)\n\nsubtotal = fields.Monetary(\n    compute='_compute_subtotal',\n    store=True,\n)\n\nsubtotal = quantity * unit_price" },
  { id: "total", label: "4) Total", title: "El total sale de sus lineas", subtitle: "La cabecera agrega subtotales y no acepta que alguien escriba un total independiente.", chip: "Computed", content: "@api.depends('line_ids.subtotal')\ndef _compute_total_amount(self):\n    for presale in self:\n        presale.total_amount = sum(\n            presale.line_ids.mapped('subtotal')\n        )\n\nEl total cambia cuando cambian cantidad, precio o lineas." },
  { id: "payment", label: "5) Payment", title: "Los pagos son registros, no un contador", subtitle: "Cada pago conserva importe, fecha, referencia y trazabilidad propia.", chip: "Modelo", content: "class TradePresalePayment(models.Model):\n    _name = 'trade.presale.payment'\n\n    presale_id = fields.Many2one(\n        'trade.presale', required=True, ondelete='cascade')\n    amount = fields.Monetary(required=True)\n    payment_date = fields.Date(required=True)\n    reference = fields.Char()\n\nPreventa -> payment_ids" },
  { id: "paid", label: "6) Pagado", title: "paid_amount agrega los pagos", subtitle: "El importe pagado se calcula desde las líneas de pago activas.", chip: "Aggregate", content: "paid_amount = fields.Monetary(\n    compute='_compute_payment_amounts',\n    store=True,\n)\n\npaid_amount = sum(\n    presale.payment_ids.mapped('amount')\n)\n\nMultiples pagos siguen produciendo una sola cifra confiable." },
  { id: "pending", label: "7) Pendiente", title: "Lo pendiente se deriva del total", subtitle: "El saldo no debe editarse: es la diferencia entre lo comprometido y lo pagado.", chip: "Formula", content: "pending_amount = total_amount - paid_amount\n\nSin pagos:      pendiente = total\nPago parcial:   pendiente > 0\nPago completo:  pendiente = 0\n\nUn pendiente negativo revela sobrepago o una regla faltante." },
  { id: "percentage", label: "8) Porcentaje", title: "El porcentaje comunica progreso", subtitle: "Una métrica derivada permite entender rápidamente el estado financiero de la preventa.", chip: "Indicador", content: "if total_amount:\n    paid_percentage = (\n        paid_amount / total_amount\n    ) * 100\nelse:\n    paid_percentage = 0\n\nEvitar división por cero y decidir cómo presentar valores redondeados." },
  { id: "pattern", label: "9) Patron", title: "Un unico origen de verdad", subtitle: "Los cálculos se encadenan desde datos base, lo que evita inconsistencias y actualizaciones olvidadas.", chip: "Patron", content: "Lineas + precios\n  -> total_amount\nPagos\n  -> paid_amount\nTotal - pagado\n  -> pending_amount\nPagado / total\n  -> paid_percentage\n\nCada resultado tiene una dependencia explícita." },
  { id: "oversale", label: "10) Sobrepreventa", title: "Detectar reservas mayores a la importacion", subtitle: "La disponibilidad se calcula contra las preventas activas de cada producto e importación.", chip: "Negocio", content: "Importado:        100 TV\nPreventas activas:  90 TV\nNueva reserva:      20 TV\n\nResultado: sobrepreventa de 10 TV.\n\nLa advertencia o bloqueo depende de la política comercial definida." },
  { id: "warning", label: "11) Warning", title: "Warning no equivale a Constraint", subtitle: "Un warning informa una situación; una constraint impide persistir un dato inválido.", chip: "Reglas", content: "Warning:\n- informa riesgo\n- puede permitir continuar\n- ayuda a decidir\n\nConstraint:\n- bloquea persistencia\n- funciona fuera de la UI\n- protege invariantes\n\nElegir según el costo de permitir la operación." },
  { id: "state", label: "12) Estado", title: "Los estados también pueden derivarse", subtitle: "El estado financiero puede responder a pagos y total en vez de depender de una asignación manual.", chip: "Derived State", content: "Sin pagos       -> unpaid\nPago parcial    -> partially_paid\nPago completo   -> paid\nSobrepago       -> review\n\nEl workflow comercial y el estado financiero pueden ser dimensiones separadas." },
  { id: "manual", label: "13) Manual", title: "Separar intención y resultado", subtitle: "Una acción manual expresa una decisión; un estado derivado expresa una consecuencia de los datos actuales.", chip: "Modelo", content: "Manual:\n- confirmar preventa\n- cancelar preventa\n- convertir a venta\n\nDerivado:\n- importe pendiente\n- porcentaje pagado\n- estado de pago\n- indicador de sobrepreventa\n\nNo mezclar ambos tipos de estado." },
  { id: "example", label: "14) Ejemplo", title: "Un caso completo", subtitle: "Las métricas se actualizan automáticamente al añadir pagos y modificar las líneas.", chip: "Flujo", content: "Preventa: 10 TV x $100 = $1,000\nPago 1: $300\nPago 2: $500\n\npaid_amount:    $800\npending_amount: $200\npaid_percentage: 80%\npayment_state: partially_paid\n\nAl registrar $200 más, pasa a paid." },
  { id: "overpayment", label: "15) Sobrepago", title: "El sobrepago exige una política", subtitle: "No es un detalle de interfaz: hay que definir si se bloquea, se acepta como crédito o se envía a revisión.", chip: "Decision", content: "Opciones de negocio:\n- bloquear pagos que exceden el total\n- permitir crédito a favor\n- marcar review y requerir aprobación\n\nLa regla debe documentarse y probarse. No ocultar un saldo negativo." },
  { id: "qa", label: "16) QA", title: "Probar hechos y resultados", subtitle: "Cada combinación de líneas, pagos y reservas debe producir el estado esperado sin cambios parciales.", chip: "QA", content: "Casos mínimos:\n- sin pagos\n- pago parcial\n- pago completo\n- pagos múltiples\n- sobrepago\n- sobrepreventa\n- total cero\n- edición de precio\n- eliminación de pago\n- cambio de estado comercial\n\nVerificar respuesta, persistencia y valores derivados." },
  { id: "closing", label: "17) Cierre", title: "Los estados derivados reflejan la realidad", subtitle: "El modelo se vuelve confiable cuando sus indicadores provienen de datos observables y reglas explícitas.", chip: "Cierre", content: "Regla mental:\n\nRegistrar hechos.\nCalcular consecuencias.\nBloquear invariantes.\nAdvertir riesgos.\nSeparar acciones humanas de estados derivados.\n\nTradeOps puede así explicar qué se vendió, qué se pagó y qué requiere revisión." },
];

export default function Daily169Client() {
  const [activeSection, setActiveSection] = useState("problem");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/168"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Pagos y estados derivados en TradeOps</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/168"><span className={styles.kbd}>←</span> Dia 168</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>04/09/2026</div><div className={styles.badge}>Daily #169 • Odoo TradeOps</div><h2 className={styles.title}>Sobrepreventa, pagos y estados derivados</h2><p className={styles.lead}>Construir indicadores financieros y operativos a partir de líneas, pagos y reglas de negocio.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/168"><span className={styles.kbd}>←</span> Dia 168</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
