"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "problem", label: "1) Problema", title: "Cerrar financieramente la operación", subtitle: "Después de importación, preventa, venta, distribución y entrega, TradeOps necesita agrupar operaciones para conciliarlas.", chip: "Contexto", content: "Importación\n  ↓\nPreventa\n  ↓\nsale.order\n  ↓\nDistribución\n  ↓\nEntrega\n  ↓\nConciliación\n\nSupplier A\nVenta 001 → $20,000\nVenta 002 → $30,000\nVenta 003 → $10,000\n\nRECON-001 → $60,000" },
  { id: "model", label: "2) Conciliación", title: "Agrupar registros relacionados", subtitle: "Una conciliación es una operación empresarial que procesa conjuntamente varias líneas asociadas a un proveedor, compañía y fecha.", chip: "Dominio", content: "trade.reconciliation\n  +-- supplier_id\n  +-- company_id\n  +-- reconciliation_date\n  +-- line_ids\n  +-- total_amount\n  +-- state\n\nUna línea conciliable debe poder identificarse y seguirse sin duplicar la fuente original." },
  { id: "invariant", label: "3) Invariante", title: "Una línea no puede conciliarse dos veces", subtitle: "La regla principal del dominio debe cumplirse desde cualquier entrada: interfaz, RPC, importación, cron o código.", chip: "Regla", content: "SALE-001 → RECON-001  ✓\nSALE-001 → RECON-002  ✗\n\nSi reconciliation_id ya existe:\n    rechazar la operación\n\nEl mensaje debe ser accionable y la conciliación anterior debe permanecer intacta." },
  { id: "race", label: "4) Race condition", title: "Validar antes de escribir no basta", subtitle: "Dos usuarios pueden leer el mismo valor vacío antes de que cualquiera guarde el cambio.", chip: "Concurrencia", content: "SALE-001: reconciliation = NULL\n\nCarlos                  Ana\n  READ NULL               READ NULL\n  CHECK válido            CHECK válido\n  WRITE RECON-001        WRITE RECON-002\n\nEl resultado depende del orden temporal entre CHECK y WRITE: es una Race Condition." },
  { id: "dotnet", label: "5) Paralelo", title: "El problema existe en cualquier backend", subtitle: "Odoo y ASP.NET Core enfrentan la misma ventana entre leer, comprobar y persistir.", chip: ".NET", content: "var order = await db.Orders.FindAsync(id);\n\nif (!order.Processed)\n{\n    order.Processed = true;\n    await db.SaveChangesAsync();\n}\n\nDos requests pueden leer Processed = false.\nLa comprobación en memoria no es por sí sola una garantía concurrente." },
  { id: "transaction", label: "6) Transacción", title: "La operación debe ser una unidad", subtitle: "Crear la conciliación, asociar líneas, calcular el total y cambiar estados deben confirmarse juntas.", chip: "Atomicidad", content: "BEGIN\n  crear RECON-001\n  asociar SALE-001\n  asociar SALE-002\n  asociar SALE-003\n  calcular total\nCOMMIT\n\nSi un paso falla:\nROLLBACK\n\nNo debe quedar la conciliación creada a medias." },
  { id: "odoo-transaction", label: "7) Odoo", title: "Respetar la transacción del request", subtitle: "Odoo trabaja con PostgreSQL y normalmente administra la transacción alrededor de la operación.", chip: "ORM", content: "ORM\n ↓\nenv\n ↓\nenv.cr\n ↓\nPostgreSQL\n\nNo hacer commits manuales dentro de una acción de negocio:\n\nself.env.cr.commit()  # evitarlo aquí\n\nUn commit intermedio impediría deshacer la primera mitad si la segunda falla." },
  { id: "business-action", label: "8) Acción", title: "Validar la acción de conciliación", subtitle: "La validación Python mejora el feedback y cubre los casos normales, pero necesita una defensa más fuerte.", chip: "Servicio", content: "def action_reconcile(self):\n    self.ensure_one()\n    if not self.line_ids:\n        raise UserError('No hay líneas.')\n    for line in self.line_ids:\n        if line.reconciliation_id:\n            raise UserError('Línea ya conciliada.')\n    # continuar dentro de la transacción actual\n\nValidación de negocio ≠ garantía contra concurrencia." },
  { id: "constraint", label: "9) Constraint", title: "Proteger la invariante cerca de los datos", subtitle: "La base de datos debe impedir que una línea aparezca dos veces aunque falle una capa de aplicación.", chip: "PostgreSQL", content: "Tabla de relación\n  reconciliation_id\n  sale_line_id\n\nUNIQUE(sale_line_id)\n\nRECON-001 → SALE-001  ✓\nRECON-002 → SALE-001  ✗\n\nLa decisión final la toma PostgreSQL, incluso si dos operaciones llegaron casi simultáneamente." },
  { id: "defense", label: "10) Defensa", title: "Defense in Depth", subtitle: "La validación de negocio comunica mejor el error y la constraint aporta la garantía final.", chip: "Diseño", content: "Usuario\n   ↓\nValidación Python\n   ↓\nAlready reconciled\n   ↓\nConstraint de base de datos\n   ↓\nIntegridad final\n\nNo se elimina una capa para confiar ciegamente en otra." },
  { id: "referential", label: "11) Relaciones", title: "Eliminar no es deshacer automáticamente", subtitle: "La política de relación debe respetar el significado empresarial y evitar líneas atrapadas en un estado inconsistente.", chip: "Integridad", content: "restrict → impedir eliminar dependencias\ncascade  → eliminar dependientes\nset null → conservar el registro y quitar relación\n\nSi una conciliación se elimina válidamente, sus líneas deben volver a estar disponibles o la operación debe conservarse como cancelada para auditoría. La decisión definitiva queda pendiente." },
  { id: "states", label: "12) Estados", title: "Borrar y cancelar son decisiones distintas", subtitle: "En sistemas empresariales suele ser más seguro conservar el documento y modelar Draft, Confirmed y Cancelled.", chip: "Workflow", content: "Draft\n  ↓\nConfirmed\n  ↓\nCancelled\n\nNo inventamos hoy una política definitiva de eliminación. Sí exigimos que ninguna acción deje referencias huérfanas o líneas bloqueadas sin explicación." },
  { id: "qa", label: "13) QA", title: "Probar el resultado y la ausencia de cambios parciales", subtitle: "La prueba debe comprobar el estado final, la persistencia, el total y el rollback, no solo que se pulsó un botón.", chip: "Pruebas", content: "Happy path → 3 líneas, total correcto, confirmed\nLínea ya conciliada → error y cero cambios parciales\nFallo en mitad → rollback completo\nDoble clic → una conciliación\nConcurrencia real → uno gana y uno falla\n\nLa suite debe demostrar que el registro nunca queda en dos conciliaciones." },
  { id: "challenge", label: "14) Reto", title: "Pensar en la ventana entre CHECK y WRITE", subtitle: "El escenario concurrente permite distinguir una validación superficial de una garantía de integridad real.", chip: "Ejercicio", content: "Request A                 Request B\nREAD SALE-500              READ SALE-500\nNULL                       NULL\nif !reconciled ✓           if !reconciled ✓\nWRITE RECON-1              WRITE RECON-2\n\nPregunta: ¿por qué el if no es suficiente?\nPorque otro proceso puede cambiar el dato entre la comprobación y la escritura." },
  { id: "map", label: "15) Arquitectura", title: "El nuevo concepto de TradeOps", subtitle: "La clase define el modelo y su invariante; la estrategia concreta de locking y relación final se implementará cuando el dominio esté preparado.", chip: "TradeOps", content: "trade_reconciliation/\n  __init__.py\n  __manifest__.py\n  models/\n    __init__.py\n    trade_reconciliation.py\n  views/\n  security/\n\ntrade.reconciliation\n  → supplier_id\n  → company_id\n  → reconciliation_date\n  → line_ids\n  → total_amount\n  → state\n\nInvariante: una línea conciliable tiene como máximo una conciliación activa." },
  { id: "closing", label: "16) Cierre", title: "Backend correcto incluso bajo operaciones simultáneas", subtitle: "La pregunta deja de ser solo si el dato es válido: también importa qué ocurre cuando dos usuarios hacen algo válido al mismo tiempo.", chip: "Resumen", content: "Validar antes de escribir no elimina una Race Condition.\n\nUna operación crítica debe ser atómica: todo o nada.\n\nLas invariantes críticas deben protegerse lo más cerca posible de los datos.\n\nCommit conceptual del día:\nfeat(trade-reconciliation): define atomic reconciliation workflow" },
];

export default function Daily173Client() {
  const [activeSection, setActiveSection] = useState("problem");

  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/172"; };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, []);

  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);

  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Conciliaciones y concurrencia en Odoo 17</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/172"><span className={styles.kbd}>←</span> Dia 172</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>10/09/2026</div><div className={styles.badge}>Daily #173 • Odoo Transactions</div><h2 className={styles.title}>Conciliaciones, transacciones y concurrencia en Odoo 17</h2><p className={styles.lead}>Diseñar una operación crítica de TradeOps para que una línea no pueda procesarse dos veces y para que el flujo sea completamente atómico.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/172"><span className={styles.kbd}>←</span> Dia 172</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
