"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "problem", label: "1) Problema", title: "Una importacion no es solo una carga de datos", subtitle: "Cada fila debe cumplir reglas de negocio y la cabecera debe mostrar un estado calculado que ayude a operar.", chip: "Contexto", content: "Importacion\n  +-- lineas validas\n  +-- lineas con error\n  +-- origen\n  +-- destino\n  +-- cantidad\n  +-- estado\n\nEl modelo debe calcular informacion util y bloquear datos imposibles aunque no exista una interfaz." },
  { id: "computed", label: "2) Computed", title: "Calcular informacion derivada", subtitle: "Un computed field expresa un valor que depende de otros campos y no debe duplicarse manualmente.", chip: "Computed", content: "valid_line_count = fields.Integer(\n    compute='_compute_valid_line_count'\n)\n\n@api.depends('line_ids.status')\ndef _compute_valid_line_count(self):\n    for record in self:\n        record.valid_line_count = len(\n            record.line_ids.filtered(\n                lambda line: line.status == 'valid'))\n\nEl valor siempre se recalcula cuando cambia la dependencia." },
  { id: "self", label: "3) Recordsets", title: "Por que iteramos self", subtitle: "Un metodo puede recibir cero, uno o muchos registros; escribir para recordsets evita supuestos incorrectos.", chip: "ORM", content: "for record in self:\n    record.total_lines = len(record.line_ids)\n\nNo asumir:\nself es un solo registro\n\nRespetar la semantica del ORM permite llamadas desde listas, acciones masivas, cron y codigo interno." },
  { id: "store", label: "4) store=True", title: "Cuando almacenar el computed", subtitle: "Guardar el resultado permite buscar y ordenar por el valor calculado, a cambio de mantener dependencias correctas.", chip: "Persistencia", content: "valid_line_count = fields.Integer(\n    compute='_compute_valid_line_count',\n    store=True,\n)\n\nUsar store=True cuando el campo se filtra, ordena o consulta con frecuencia. Revisar @api.depends para que los cambios en lineas actualicen la cabecera." },
  { id: "origin", label: "5) Invariante", title: "Origen y destino no pueden ser iguales", subtitle: "Una operacion que mueve datos al mismo lugar no representa una transferencia valida.", chip: "Constraint", content: "@api.constrains('origin_id', 'destination_id')\ndef _check_different_locations(self):\n    for record in self:\n        if record.origin_id == record.destination_id:\n            raise ValidationError(\n                'Origen y destino deben ser distintos.')\n\nLa constraint vive en servidor y se aplica desde UI, shell, importacion y API." },
  { id: "quantity", label: "6) Invariante", title: "La cantidad debe ser positiva", subtitle: "Cero y valores negativos no describen una importacion de unidades valida.", chip: "Constraint", content: "@api.constrains('quantity')\ndef _check_positive_quantity(self):\n    for line in self:\n        if line.quantity <= 0:\n            raise ValidationError(\n                'La cantidad debe ser mayor que cero.')\n\nValidar tambien tipo, precision y limites funcionales cuando el dominio los requiera." },
  { id: "server", label: "7) Servidor", title: "Constraint no es validacion de interfaz", subtitle: "Ocultar una opcion en una vista mejora la experiencia, pero no protege el modelo por si solo.", chip: "Seguridad", content: "Vista: filtra opciones\n  |\n  v\nConstraint: protege datos\n  |\n  v\nORM: aplica regla\n\nUn usuario puede usar importacion, shell, RPC o un modulo diferente. La regla critica siempre debe ejecutarse en servidor." },
  { id: "onchange", label: "8) onchange", title: "Ayudar sin confundir", subtitle: "`@api.onchange` reacciona en el formulario; sirve para feedback, pero no sustituye constraints.", chip: "UX", content: "onchange:\n- completa valores\n- muestra advertencias\n- mejora el formulario\n\nconstraint:\n- bloquea datos invalidos\n- funciona fuera de la UI\n- protege persistencia\n\nUna advertencia no debe usarse cuando el negocio exige impedir la operacion." },
  { id: "block", label: "9) Decisiones", title: "Bloquear o advertir", subtitle: "La severidad depende del impacto de permitir el dato incorrecto.", chip: "Reglas", content: "Bloquear:\nOrigen igual a destino.\nCantidad menor o igual a cero.\nCliente obligatorio ausente.\nSerie duplicada.\n\nAdvertir:\nFormato poco habitual.\nFecha futura permitida pero sospechosa.\nDato incompleto que puede corregirse despues.\n\nDocumentar cada decision de negocio." },
  { id: "number", label: "10) Identidad", title: "El numero real de importacion", subtitle: "El nombre visible y el identificador tecnico deben ser estables, unicos y compatibles con concurrencia.", chip: "Sequence", content: "Una importacion puede necesitar:\n- numero humano: IMP/2026/0001\n- id tecnico de PostgreSQL\n- external ID si se integra\n\nNo generar numeros contando registros existentes: dos transacciones pueden obtener el mismo valor. Usar secuencias o el mecanismo transaccional de Odoo." },
  { id: "status", label: "11) Estado", title: "TradeOps con reglas ejecutables", subtitle: "Los computed fields permiten operar y las constraints protegen el dominio en cada punto de entrada.", chip: "Milestone", content: "Importacion\n  +-- total de lineas (computed)\n  +-- lineas validas (computed)\n  +-- estado operativo\n  +-- origen != destino\n  +-- cantidad > 0\n  +-- numero unico\n\nLa importacion puede informar progreso sin aceptar datos imposibles." },
  { id: "qa", label: "12) QA", title: "Probar reglas y valores derivados", subtitle: "Cada regla debe comprobarse desde ORM y desde los flujos que la consumen.", chip: "QA", content: "Computed refleja lineas actuales\nComputed almacenado se actualiza\nRecordset multiple funciona\nOrigen igual a destino falla\nCantidad cero falla\nCantidad negativa falla\nOnchange no sustituye constraint\nNumero no se duplica\nImportacion valida persiste\nFila invalida no deja cambios parciales\nShell y UI respetan reglas" },
  { id: "checklist", label: "13) Checklist", title: "Reglas de importacion listas", subtitle: "El modelo debe proteger el negocio incluso cuando la entrada no procede de una pantalla.", chip: "Checklist", content: "Dependencies de computed completas\nstore=True solo donde aporta\nself iterado correctamente\nConstraints en servidor\nWarnings solo para UX\nBloqueos documentados\nSecuencias transaccionales\nMensajes accionables\nTests de limites\nTests de persistencia\nImportacion atomica definida" },
  { id: "closing", label: "14) Cierre", title: "El modelo debe defenderse solo", subtitle: "Un backend Odoo profesional calcula lo derivado y rechaza estados invalidos en cualquier punto de entrada.", chip: "Cierre", content: "Backend junior:\nValido lo que llega desde el formulario.\n\nBackend senior:\nDefine computed fields, dependencias, constraints, severidad, secuencias y pruebas para que el dominio sea correcto desde UI, shell, importaciones, RPC y cron.\n\nTradeOps ahora puede crecer sobre reglas ejecutables." },
];

export default function Daily162Client() {
  const [activeSection, setActiveSection] = useState("problem");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/161"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Computed Fields y Constraints en Odoo</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/161"><span className={styles.kbd}>←</span> Dia 161</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>26/08/2026</div><div className={styles.badge}>Daily #162 • Odoo Business Rules</div><h2 className={styles.title}>Computed Fields, Constraints y reglas de negocio en Importaciones</h2><p className={styles.lead}>Calcular progreso, proteger invariantes y distinguir feedback de interfaz de reglas reales del servidor.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/161"><span className={styles.kbd}>←</span> Dia 161</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
