"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "idea", label: "1) Idea clave", title: "La primera extraccion debe ser pequena", subtitle: "Catalog es el primer microservicio porque tiene limites claros y pocas dependencias criticas.", chip: "Idea", content: "En la clase anterior preparamos la estructura base.\n\nAhora comenzamos la primera extraccion real:\n\nCatalog Service\n\nNo migraremos Orders, Payments e Inventory al mismo tiempo. Primero separaremos Catalog y comprobaremos que el sistema sigue funcionando.\n\nLa primera extraccion debe ser pequena, controlada y facil de validar." },
  { id: "responsibility", label: "2) Responsabilidad", title: "Que responsabilidad tendra Catalog", subtitle: "Catalog administra la informacion comercial de los productos y es dueno de sus reglas.", chip: "Limites", content: "Catalog controla:\n\nProductos\nCategorias\nMarcas\nDescripciones\nPrecios actuales\nEstado activo o inactivo\n\nCatalog responde:\nExiste este producto?\nEsta activo?\nCual es su precio actual?\nA que categoria pertenece?\n\nNo responde por stock, reservas, pagos ni notificaciones." },
  { id: "extract", label: "3) Extraer del monolito", title: "Que vamos a mover", subtitle: "La funcionalidad de productos pasara a una solucion con capas y responsabilidades separadas.", chip: "Migracion", content: "Monolito actual:\n\nControllers/ProductsController.cs\nEntities/Product.cs\nEntities/Category.cs\nEntities/Brand.cs\nServices/ProductService.cs\nRepositories/ProductRepository.cs\nDTOs/ProductResponse.cs\nData/OrderFlowDbContext.cs\n\nDestino:\nCatalog.API\nCatalog.Application\nCatalog.Domain\nCatalog.Infrastructure" },
  { id: "strategy", label: "4) Estrategia", title: "Migracion gradual", subtitle: "La implementacion nueva debe funcionar antes de retirar la anterior.", chip: "Seguridad", content: "1. Crear Catalog Service.\n2. Copiar y adaptar la logica.\n3. Crear su propia base de datos.\n4. Probarlo de forma independiente.\n5. Redirigir las peticiones.\n6. Verificar que funciona.\n7. Eliminar la implementacion antigua.\n\nPrimero hacemos que la nueva implementacion funcione. Despues retiramos la anterior." },
  { id: "structure", label: "5) Estructura", title: "La estructura del nuevo servicio", subtitle: "Cada capa tendra una responsabilidad concreta dentro de Catalog.", chip: "Arquitectura", content: "Catalog\n|-- Catalog.API\n|   |-- Controllers\n|   |-- Middleware\n|   |-- Extensions\n|   |-- Program.cs\n|-- Catalog.Application\n|   |-- Products/Commands\n|   |-- Products/Queries\n|   |-- Products/DTOs\n|   |-- Products/Validators\n|-- Catalog.Domain\n|   |-- Products\n|   |-- Categories\n|   |-- Brands\n|-- Catalog.Infrastructure\n    |-- Persistence\n    |-- Repositories\n    |-- Configurations\n    |-- Migrations" },
  { id: "domain", label: "6) Dominio", title: "Catalog.Domain protege las reglas", subtitle: "La entidad Product no debe permitir estados invalidos.", chip: "Domain", content: "public sealed class Product\n{\n    public Guid Id { get; private set; }\n    public string Name { get; private set; }\n    public decimal Price { get; private set; }\n    public Guid CategoryId { get; private set; }\n    public bool Active { get; private set; }\n\n    public void Update(...) { SetName(name); SetPrice(price); }\n    public void Activate() { Active = true; }\n    public void Deactivate() { Active = false; }\n}\n\nEl dominio valida nombre, precio, id y categoria. La entidad debe proteger sus invariantes." },
  { id: "invariants", label: "7) Invariantes", title: "Por que la entidad tiene comportamiento", subtitle: "Un modelo anemico permite crear productos imposibles y desplaza reglas a cualquier capa.", chip: "Reglas", content: "Una implementacion debil permite:\n\nvar product = new Product\n{\n    Name = \"\",\n    Price = -500\n};\n\nUna entidad rica controla la creacion y la actualizacion mediante metodos como:\n\nUpdate\nActivate\nDeactivate\n\nEl dominio no debe permitir que una entidad exista en un estado invalido." },
  { id: "dtos", label: "8) DTOs", title: "DTOs fuera del dominio", subtitle: "Los contratos de entrada y salida pertenecen a Application o API.", chip: "Contratos", content: "public sealed record CreateProductRequest(\n    string Name,\n    string? Description,\n    decimal Price,\n    Guid CategoryId);\n\npublic sealed record ProductResponse(\n    Guid Id, string Name, string? Description,\n    decimal Price, Guid CategoryId, bool Active);\n\nEl dominio no conoce requests HTTP ni respuestas de transporte." },
  { id: "repository", label: "9) Repositorio", title: "La abstraccion del repositorio", subtitle: "Application define lo que necesita y Infrastructure decide como persistirlo.", chip: "Persistencia", content: "public interface IProductRepository\n{\n    Task<Product?> GetByIdAsync(Guid id, CancellationToken ct = default);\n    Task<IReadOnlyList<Product>> GetAllAsync(CancellationToken ct = default);\n    Task AddAsync(Product product, CancellationToken ct = default);\n    void Update(Product product);\n}\n\npublic interface IUnitOfWork\n{\n    Task<int> SaveChangesAsync(CancellationToken ct = default);\n}" },
  { id: "application", label: "10) Caso de uso", title: "Crear un producto", subtitle: "El servicio de aplicacion orquesta el caso de uso sin absorber las reglas profundas del dominio.", chip: "Application", content: "public async Task<ProductResponse> CreateAsync(\n    CreateProductRequest request, CancellationToken ct)\n{\n    var product = new Product(\n        Guid.NewGuid(), request.Name, request.Description,\n        request.Price, request.CategoryId);\n\n    await _repository.AddAsync(product, ct);\n    await _unitOfWork.SaveChangesAsync(ct);\n    return Map(product);\n}\n\nLa aplicacion carga, coordina y guarda. El dominio valida." },
  { id: "constructor", label: "11) Mejora del dominio", title: "Un constructor completo", subtitle: "La creacion debe expresar todos los datos necesarios en una unica operacion valida.", chip: "Refactor", content: "public Product(Guid id, string name, string? description, decimal price, Guid categoryId)\n{\n    if (id == Guid.Empty) throw new ArgumentException();\n    Id = id;\n    SetName(name);\n    Description = description?.Trim();\n    SetPrice(price);\n    if (categoryId == Guid.Empty) throw new ArgumentException();\n    CategoryId = categoryId;\n    Active = true;\n    CreatedAt = DateTimeOffset.UtcNow;\n}\n\nAsi la creacion no necesita un Update posterior." },
  { id: "dbcontext", label: "12) DbContext", title: "Persistencia independiente", subtitle: "Catalog necesita su propio DbContext y su propia unidad de trabajo.", chip: "EF Core", content: "public sealed class CatalogDbContext : DbContext, IUnitOfWork\n{\n    public DbSet<Product> Products => Set<Product>();\n\n    protected override void OnModelCreating(ModelBuilder modelBuilder)\n    {\n        modelBuilder.ApplyConfigurationsFromAssembly(\n            typeof(CatalogDbContext).Assembly);\n    }\n}\n\nLa persistencia de Catalog no debe depender del DbContext del monolito." },
  { id: "configuration", label: "13) EF Core", title: "Configuracion de Entity Framework", subtitle: "La configuracion define limites, precision, indices y restricciones de la tabla Products.", chip: "Database", content: "builder.ToTable(\"Products\");\nbuilder.HasKey(product => product.Id);\nbuilder.Property(product => product.Name).HasMaxLength(200).IsRequired();\nbuilder.Property(product => product.Description).HasMaxLength(2000);\nbuilder.Property(product => product.Price).HasPrecision(18, 2).IsRequired();\nbuilder.Property(product => product.CategoryId).IsRequired();\nbuilder.HasIndex(product => product.Name);\nbuilder.HasIndex(product => product.CategoryId);" },
  { id: "repository-implementation", label: "14) Implementacion", title: "El repositorio concreto", subtitle: "Infrastructure implementa la interfaz usando CatalogDbContext y EF Core.", chip: "Infrastructure", content: "public async Task<Product?> GetByIdAsync(Guid id, CancellationToken ct)\n{\n    return await _dbContext.Products\n        .FirstOrDefaultAsync(product => product.Id == id, ct);\n}\n\npublic async Task<IReadOnlyList<Product>> GetAllAsync(CancellationToken ct)\n{\n    return await _dbContext.Products\n        .AsNoTracking()\n        .OrderBy(product => product.Name)\n        .ToListAsync(ct);\n}\n\nAddAsync agrega y Update marca la entidad para persistir cambios." },
  { id: "di", label: "15) Dependency Injection", title: "Registrar Infrastructure", subtitle: "La composicion conecta DbContext, repositorio y Unit of Work sin acoplar Application a EF Core.", chip: "DI", content: "services.AddDbContext<CatalogDbContext>(options =>\n    options.UseNpgsql(connectionString));\n\nservices.AddScoped<IProductRepository, ProductRepository>();\nservices.AddScoped<IUnitOfWork>(sp =>\n    sp.GetRequiredService<CatalogDbContext>());\n\nLa cadena CatalogDatabase debe ser propia y configurable por entorno." },
  { id: "api", label: "16) API", title: "Exponer Catalog", subtitle: "El API debe ofrecer endpoints simples, health check, Swagger y respuestas consistentes.", chip: "HTTP", content: "GET    /products\nGET    /products/{id}\nPOST   /products\nPUT    /products/{id}\nPATCH  /products/{id}/activate\nPATCH  /products/{id}/deactivate\n\nCatalog.API recibe DTOs, llama Application y no contiene reglas de negocio profundas." },
  { id: "checklist", label: "17) Checklist", title: "Validar antes de redirigir trafico", subtitle: "La primera extraccion termina cuando Catalog puede ejecutarse y probarse de forma independiente.", chip: "Checklist", content: "Catalog.API creado\nCatalog.Application creado\nCatalog.Domain creado\nCatalog.Infrastructure creado\nProduct con invariantes\nDTOs separados\nRepositorio y Unit of Work\nCatalogDbContext propio\nMigracion de base creada\nSwagger funcionando\nGET /health funcionando\nDocker Compose actualizado\nPruebas independientes\n\nPrimero funciona la nueva implementacion. Despues se retira la antigua." },
];

export default function Daily137Client() {
  const [activeSection, setActiveSection] = useState("idea");

  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement | null;
      if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return;
      if (event.key.toLowerCase() === "p") window.location.href = "/daily/136";
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, []);

  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);

  return (
    <div className={styles.page}>
      <header className={styles.topbar}><div className={styles.topbarInner}>
        <div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Extraer Catalog como primer microservicio</div></div></div>
        <nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav>
        <div className={styles.actions}><Link className={styles.btn} href="/daily/136"><span className={styles.kbd}>←</span> Dia 136</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div>
      </div></header>
      <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}>
        <div className={styles.dailyHero}><div className={styles.createdAt}>21/07/2026</div><div className={styles.badge}>Daily #137 • Catalog Service</div><h2 className={styles.title}>Extraer Catalog como el primer microservicio de OrderFlow</h2><p className={styles.lead}>La primera migracion real sera pequena, controlada y facil de validar: separar Catalog sin romper el monolito.</p></div>
        <nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>
        {sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}
        <div className={styles.footerNav}><Link className={styles.btn} href="/daily/136"><span className={styles.kbd}>←</span> Dia 136</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div>
      </div></article></div></main>
    </div>
  );
}
