"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "idea", label: "1) Idea clave", title: "Inventory es la fuente de verdad del stock", subtitle: "Orders puede confirmar una compra, pero Inventory decide si las unidades existen y pueden reservarse.", chip: "Idea", content: "Orders ya puede crear, modificar y confirmar ordenes.\n\nPero confirmar no significa que podamos vender.\n\nAntes del pago debemos responder:\n\nExisten unidades suficientes?\n\nEsa decision no pertenece a Orders. Pertenece a Inventory Service.\n\nCatalog describe el producto. Orders gestiona la compra. Inventory decide la disponibilidad." },
  { id: "responsibility", label: "2) Responsabilidad", title: "Que responsabilidad tendra Inventory", subtitle: "Inventory controla stock, reservas, consumos y movimientos sin conocer precios ni pagos.", chip: "Limites", content: "Inventory controla:\n\nregistrar existencias\nincrementar y disminuir stock\nreservar unidades\nliberar reservas\nconfirmar consumos\nregistrar movimientos\nimpedir inventario negativo\ncontrolar concurrencia\n\nNo responde por precio, total de orden, pago ni notificaciones." },
  { id: "stock", label: "3) Stock", title: "Fisico, reservado y disponible", subtitle: "Un unico campo Stock no representa correctamente el estado real del almacen.", chip: "Modelo", content: "PhysicalStock = 20\nReservedStock = 6\nAvailableStock = PhysicalStock - ReservedStock\n\nAvailableStock = 20 - 6 = 14\n\nUna reserva no elimina fisicamente unidades. Solo impide que puedan venderse a otra orden." },
  { id: "example", label: "4) Ejemplo", title: "Por que necesitamos reservas", subtitle: "Consultar disponibilidad y reservar inventario son operaciones de negocio distintas.", chip: "Flujo", content: "Stock fisico: 10\nReservado: 0\nDisponible: 10\n\nOrden A reserva 4:\nReservado: 4\nDisponible: 6\n\nOrden B solicita 7:\nDisponible: 6\nSolicitado: 7\n\nLa operacion se rechaza. Nunca debemos terminar con AvailableStock = -1." },
  { id: "race", label: "5) Carrera", title: "Consultar no protege la compra", subtitle: "Dos clientes pueden observar el mismo stock si solo hacemos una lectura antes de pagar.", chip: "Riesgo", content: "1. Verificamos cinco unidades.\n2. Iniciamos el pago.\n3. Otro cliente compra esas cinco.\n4. Nuestro pago es aprobado.\n5. Ya no existe el producto.\n\nConsultar disponibilidad es una lectura. Reservar inventario cambia el estado y protege la compra." },
  { id: "structure", label: "6) Estructura", title: "La estructura del servicio", subtitle: "Inventory separa API, casos de uso, dominio e infraestructura.", chip: "Arquitectura", content: "Inventory\n|-- Inventory.API\n|   |-- Controllers\n|   |-- Program.cs\n|-- Inventory.Application\n|   |-- Stock\n|   |-- Reservations\n|   |-- DTOs\n|   |-- Abstractions\n|-- Inventory.Domain\n|   |-- Stock\n|   |-- Reservations\n|   |-- Movements\n|-- Inventory.Infrastructure\n    |-- Persistence\n    |-- Repositories\n    |-- Configurations\n    |-- Migrations" },
  { id: "item", label: "7) InventoryItem", title: "El modelo de stock", subtitle: "Cada producto tendra una entidad InventoryItem con sus propias invariantes.", chip: "Domain", content: "InventoryItem:\nProductId\nPhysicalStock\nReservedStock\nAvailableStock\nCreatedAt\nUpdatedAt\n\nAvailableStock => PhysicalStock - ReservedStock\n\nEl constructor rechaza ids vacios y stock inicial negativo. Las propiedades tienen private set." },
  { id: "operations", label: "8) Operaciones", title: "Modificar stock mediante comportamiento", subtitle: "Las operaciones de inventario protegen cantidades y consistencia.", chip: "Reglas", content: "AddStock(quantity): quantity > 0\nReserve(quantity): disponible suficiente\nRelease(quantity): no libera mas de lo reservado\nConfirmConsumption(quantity): descuenta reservado y fisico\n\nNo permitimos:\ninventoryItem.ReservedStock += 500\n\nToda modificacion pasa por metodos del dominio." },
  { id: "invariants", label: "9) Invariantes", title: "Reglas que nunca deben romperse", subtitle: "El modelo debe impedir inventario negativo incluso ante operaciones invalidas.", chip: "Consistencia", content: "PhysicalStock >= 0\nReservedStock >= 0\nReservedStock <= PhysicalStock\nAvailableStock >= 0\n\nSi cualquiera de estas reglas falla, el agregado queda en un estado invalido." },
  { id: "reservation", label: "10) Reserva", title: "Registrar quien reservó", subtitle: "ReservedStock no basta: necesitamos saber que orden posee cada unidad reservada.", chip: "Trazabilidad", content: "ReservationStatus:\nActive = 1\nReleased = 2\nConfirmed = 3\nFailed = 4\n\nInventoryReservation contiene:\nId\nOrderId\nStatus\nItems\nCreatedAt\nReleasedAt\nConfirmedAt\nFailureReason" },
  { id: "reservation-rules", label: "11) Reglas de reserva", title: "InventoryReservation protege su ciclo", subtitle: "Una reserva activa puede modificarse; una liberada o confirmada ya no.", chip: "Domain", content: "AddItem(productId, quantity):\n- exige Active\n- rechaza ids vacios\n- rechaza cantidades invalidas\n- evita productos duplicados\n\nRelease(): Active -> Released\nConfirm(): Active -> Confirmed\nMarkAsFailed(reason): Active -> Failed\n\nEnsureActive protege las transiciones." },
  { id: "atomicity", label: "12) Atomicidad", title: "Reservar todos o ninguno", subtitle: "Una orden no puede dejar productos parcialmente reservados.", chip: "Transaccion", content: "Cuando Orders confirma:\n\n1. verificar reserva existente\n2. cargar todos los productos\n3. validar disponibilidad de todos\n4. reservar todas las cantidades\n5. crear InventoryReservation\n6. guardar todo en una transaccion\n\nNunca:\nProducto A reservado\nProducto B sin stock\nProducto C no procesado" },
  { id: "dtos", label: "13) DTOs", title: "Contratos de Inventory", subtitle: "Los requests expresan registrar stock, agregar unidades y reservar una orden.", chip: "API", content: "CreateInventoryItemRequest(ProductId, InitialStock)\nAddStockRequest(Quantity)\n\nReserveInventoryRequest:\nOrderId\nItems\n\nReserveInventoryItemRequest:\nProductId\nQuantity\n\nInventoryReservationResponse:\nReservationId\nOrderId\nStatus\nCreatedAt" },
  { id: "repositories", label: "14) Repositorios", title: "Abstracciones de persistencia", subtitle: "Application define como buscar inventario y reservas sin conocer EF Core.", chip: "Persistencia", content: "IInventoryItemRepository:\nGetByProductIdAsync\nGetByProductIdsAsync\nAddAsync\n\nIInventoryReservationRepository:\nGetByOrderIdAsync\nAddAsync\n\nIUnitOfWork:\nSaveChangesAsync\n\nGetByProductIdsAsync permite validar el conjunto de la orden." },
  { id: "create", label: "15) Crear inventario", title: "Registrar existencias", subtitle: "Cada producto debe tener un unico InventoryItem antes de poder reservarse.", chip: "Application", content: "CreateAsync:\n1. buscar inventario existente\n2. rechazar duplicado\n3. crear InventoryItem\n4. agregar al repositorio\n5. guardar cambios\n6. devolver id\n\nAddStockAsync carga el item, llama AddStock y persiste.\n\nLa unicidad por ProductId es una regla del servicio." },
  { id: "reserve", label: "16) Reservar", title: "Caso de uso de reserva", subtitle: "El servicio coordina validacion, disponibilidad, dominio y transaccion.", chip: "Application", content: "ReserveAsync:\n1. validar OrderId e items\n2. devolver reserva existente si ya existe\n3. obtener ProductIds sin duplicados\n4. cargar InventoryItems\n5. validar disponibilidad de todos\n6. llamar Reserve en cada item\n7. crear la reserva\n8. guardar cambios\n9. devolver respuesta\n\nLa operacion es idempotente por OrderId." },
  { id: "exception", label: "17) Excepcion", title: "Inventario insuficiente es negocio", subtitle: "No todo debe convertirse en InvalidOperationException generico.", chip: "Errores", content: "InsufficientInventoryException:\nProductId\nRequested\nAvailable\n\nPermite devolver un error claro:\n\n409 Conflict\n\n{\n  \"code\": \"inventory.insufficient_stock\",\n  \"message\": \"There is not enough inventory.\",\n  \"details\": { \"requested\": 5, \"available\": 2 }\n}\n\nNo es un error tecnico; es un resultado valido del negocio." },
  { id: "release", label: "18) Liberar", title: "Liberar una reserva", subtitle: "Si el pago falla, las unidades reservadas vuelven a estar disponibles.", chip: "Compensacion", content: "ReleaseAsync(orderId):\n1. cargar reserva\n2. si ya Released, retornar\n3. exigir estado Active\n4. cargar sus InventoryItems\n5. llamar Release por cantidad\n6. marcar reserva Released\n7. guardar\n\nPhysicalStock permanece igual. ReservedStock disminuye. AvailableStock aumenta." },
  { id: "confirm", label: "19) Confirmar consumo", title: "Convertir reserva en venta", subtitle: "Cuando el pago se aprueba, la reserva se convierte en consumo fisico.", chip: "Consumo", content: "ConfirmAsync(orderId):\n1. cargar reserva\n2. si ya Confirmed, retornar\n3. exigir estado Active\n4. cargar inventario\n5. llamar ConfirmConsumption\n6. marcar reserva Confirmed\n7. guardar\n\nPhysicalStock disminuye. ReservedStock disminuye. AvailableStock permanece coherente." },
  { id: "comparison", label: "20) Liberar vs confirmar", title: "Dos resultados diferentes", subtitle: "Liberar deshace una reserva; confirmar representa que las unidades se vendieron.", chip: "Estados", content: "Antes:\nPhysical = 10\nReserved = 4\nAvailable = 6\n\nLiberar:\nPhysical = 10\nReserved = 0\nAvailable = 10\n\nConfirmar:\nPhysical = 6\nReserved = 0\nAvailable = 6" },
  { id: "db", label: "21) Persistencia", title: "InventoryDbContext propio", subtitle: "Stock, reservas y sus items viven en una base de datos independiente.", chip: "EF Core", content: "InventoryDbContext:\nDbSet<InventoryItem> InventoryItems\nDbSet<InventoryReservation> Reservations\nDbSet<InventoryReservationItem> ReservationItems\n\nApplyConfigurationsFromAssembly conecta el mapeo sin mezclar CatalogDb ni OrdersDb." },
  { id: "concurrency", label: "22) Concurrencia", title: "El problema de dos reservas simultaneas", subtitle: "Validar en memoria no alcanza cuando varias operaciones escriben al mismo tiempo.", chip: "Concurrencia", content: "Dos operaciones leen:\nAvailableStock = 5\n\nAmbas intentan reservar 4.\n\nSin control:\nA reserva 4\nB reserva 4\nResultado: 8 reservadas con 5 disponibles\n\nNecesitamos concurrencia optimista en la base de datos." },
  { id: "version", label: "23) RowVersion", title: "Versionar la fila de inventario", subtitle: "Una columna de version permite detectar que otra operacion guardo primero.", chip: "EF Core", content: "builder.Property<uint>(\"Version\")\n    .IsRowVersion();\n\nA guarda primero y cambia Version.\nB intenta guardar una version antigua.\nEF Core lanza DbUpdateConcurrencyException.\n\nPodemos recargar y reintentar pocas veces, pero nunca indefinidamente." },
  { id: "controller", label: "24) API", title: "Endpoints de Inventory", subtitle: "La API expone operaciones de stock y reservas con respuestas de negocio claras.", chip: "Endpoints", content: "POST /api/inventory\nPOST /api/inventory/{productId}/stock\nGET  /api/inventory/{productId}\nPOST /api/inventory/reservations\nPOST /api/inventory/reservations/{orderId}/release\nPOST /api/inventory/reservations/{orderId}/confirm\n\n409 para stock insuficiente.\n404 para inventario o reserva inexistente." },
  { id: "integration", label: "25) Integracion", title: "Orders y Inventory", subtitle: "Orders inicia el proceso y Inventory es propietario de la decision de disponibilidad.", chip: "Flujo", content: "Orders confirma\n       |\n       v\nInventory reserva\n       |\n       +--> insuficiente: 409\n       |\n       +--> reservada: continuar pago\n       |\n       +--> pago falla: liberar\n       |\n       +--> pago aprobado: confirmar consumo" },
  { id: "failures", label: "26) Casos de fallo", title: "Que debemos probar", subtitle: "Las reglas deben resistir cantidades invalidas, duplicados, falta de stock y concurrencia.", chip: "Testing", content: "Stock inicial negativo -> rechazado\nCantidad cero o negativa -> rechazado\nProducto sin inventario -> rechazado\nStock insuficiente -> 409\nProductos duplicados -> rechazado\nReserva repetida -> devuelve la existente\nLiberar reserva confirmada -> rechazado\nConfirmar reserva liberada -> rechazado\nDos reservas simultaneas -> una gana y otra reintenta o falla" },
  { id: "result", label: "27) Resultado", title: "Que hemos conseguido", subtitle: "Inventory ya puede custodiar stock y coordinar reservas sin depender de otras bases.", chip: "Resultado", content: "Catalog describe productos.\nOrders gestiona compras.\nInventory controla disponibilidad.\n\nInventory tiene:\ndominio propio\nbase propia\nreservas trazables\noperaciones atomicas\nconcurrencia optimista\nrespuestas de negocio\n\nEl stock ya no vive dentro de Orders ni Catalog." },
  { id: "checklist", label: "28) Checklist", title: "Validacion de Inventory", subtitle: "El servicio esta listo cuando ninguna operacion puede producir inventario negativo o reservas parciales.", chip: "Checklist", content: "PhysicalStock y ReservedStock separados\nAvailableStock calculado\nNo stock negativo\nOrderId asociado a reserva\nReserva idempotente\nTodos los items o ninguno\nLiberar devuelve disponibilidad\nConfirmar reduce stock fisico\n409 para insuficiencia\nDbContext propio\nRowVersion configurado\nOrders no accede a InventoryDb\n\nEl siguiente paso sera conectar pagos y compensaciones." },
  { id: "closing", label: "29) Cierre", title: "Como piensa un backend senior", subtitle: "Inventario no es un numero: es un agregado con concurrencia, reservas, trazabilidad y reglas.", chip: "Cierre", content: "Backend junior:\nStock es un int en la tabla Product.\n\nBackend senior:\nInventory es la unica fuente de verdad sobre existencias, reservas, consumos y movimientos.\n\nNo basta con preguntar si hay stock. Hay que reservarlo correctamente, proteger la concurrencia y saber liberarlo cuando el proceso falla." },
];

export default function Daily139Client() {
  const [activeSection, setActiveSection] = useState("idea");

  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement | null;
      if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return;
      if (event.key.toLowerCase() === "p") window.location.href = "/daily/138";
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, []);

  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);

  return (
    <div className={styles.page}>
      <header className={styles.topbar}><div className={styles.topbarInner}>
        <div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Inventory Service y reservas de stock</div></div></div>
        <nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav>
        <div className={styles.actions}><Link className={styles.btn} href="/daily/138"><span className={styles.kbd}>←</span> Dia 138</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div>
      </div></header>
      <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}>
        <div className={styles.dailyHero}><div className={styles.createdAt}>24/07/2026</div><div className={styles.badge}>Daily #139 • Inventory Service</div><h2 className={styles.title}>Crear Inventory Service: gestionar stock y reservar unidades correctamente</h2><p className={styles.lead}>Inventory sera la fuente de verdad sobre existencias, reservas y consumos, protegiendo el proceso de compra frente a stock insuficiente y concurrencia.</p></div>
        <nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>
        {sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}
        <div className={styles.footerNav}><Link className={styles.btn} href="/daily/138"><span className={styles.kbd}>←</span> Dia 138</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div>
      </div></article></div></main>
    </div>
  );
}
