"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "idea", label: "1) Idea clave", title: "Diseñar para cuando algo falle", subtitle: "OrderFlow depende de varios servicios y debe continuar funcionando aunque parte de la infraestructura falle.", chip: "Idea", content: "Orders\n  |\n  v\nInventory\n  |\n  v\nPayments\n  |\n  v\nProveedor externo\n\nQue ocurre si un servicio no responde?\nQue ocurre si responde muy lento?\nQue ocurre si falla durante cinco minutos?\n\nLa resiliencia asume que los fallos ocurriran y prepara al sistema para sobrevivirlos." },
  { id: "availability", label: "2) Resiliencia", title: "Disponibilidad no es resiliencia", subtitle: "Disponibilidad pregunta si el servicio funciona; resiliencia pregunta que hace cuando deja de funcionar.", chip: "Concepto", content: "Disponibilidad:\nEl servicio esta funcionando?\n\nResiliencia:\nQue ocurre cuando deja de funcionar?\n\nUn sistema resiliente no intenta evitar todos los fallos. Los detecta, limita su impacto y recupera el flujo de forma controlada." },
  { id: "network", label: "3) Red", title: "La red no es perfecta", subtitle: "Timeouts, latencia, reinicios, DNS, RabbitMQ y Kubernetes forman parte de la realidad operativa.", chip: "Distribuido", content: "No asumir:\n\nLa red siempre funciona.\nLa latencia es cero.\nEl ancho de banda es infinito.\nLa red es segura.\nLa topologia nunca cambia.\nEl transporte cuesta cero.\nLa red es homogenea.\n\nEstas son algunas de las Eight Fallacies of Distributed Computing." },
  { id: "timeout", label: "4) Timeout", title: "Toda llamada remota necesita limite", subtitle: "Esperar indefinidamente bloquea threads, conexiones y finalmente la aplicacion completa.", chip: "Timeout", content: "Orders llama Payments.\n\nRespuesta normal: 200 ms.\nRespuesta degradada: 40 segundos.\n\nSi no existe timeout, los recursos quedan bloqueados.\n\nToda llamada HTTP, base de datos, Redis, RabbitMQ o proveedor externo necesita un limite explicito." },
  { id: "timeout-config", label: "5) Configuracion", title: "Elegir el timeout correcto", subtitle: "No existe un numero universal: depende del comportamiento y del contrato de cada dependencia.", chip: "Config", content: "Inventory: 300 ms\nPayments: 5 segundos\nProveedor bancario: 15 segundos\n\nUn timeout muy corto genera falsos fallos. Uno demasiado largo retiene recursos y retrasa la recuperacion. Se define con datos y presupuesto de latencia." },
  { id: "timeout-action", label: "6) Despues del timeout", title: "Decidir que hacer", subtitle: "Un timeout puede requerir retry, fallback, compensacion, respuesta asincrona o espera de conciliacion.", chip: "Decision", content: "Timeout\n  |\n  +--> retry seguro\n  +--> fallback\n  +--> compensacion\n  +--> continuar asincrono\n  +--> marcar estado incierto\n\nLa decision depende del negocio. En pagos, timeout no significa rechazo." },
  { id: "retry", label: "7) Retry", title: "Reintentar solo fallos temporales", subtitle: "Retry sirve para timeouts, 503, errores de red o un broker reiniciandose.", chip: "Retry", content: "Reintentar:\nTimeout\n503 Service Unavailable\nHttpRequestException\nRabbitMQ reiniciando\n\nNo reintentar automaticamente:\n400 Bad Request\n401 Unauthorized\n404 Not Found\n\nRepetir un error permanente solo aumenta la carga y retrasa la respuesta." },
  { id: "backoff", label: "8) Backoff", title: "Retry ingenuo vs exponencial", subtitle: "Esperar entre intentos evita golpear de nuevo un servicio que sigue saturado.", chip: "Backoff", content: "Incorrecto:\nIntento -> falla -> inmediato\nIntento -> falla -> inmediato\n\nExponential Backoff:\n1 segundo\n2 segundos\n4 segundos\n8 segundos\n\nEl numero de intentos debe ser limitado y observable." },
  { id: "jitter", label: "9) Jitter", title: "Evitar el thundering herd", subtitle: "La aleatoriedad distribuye los retries de miles de clientes que fallaron juntos.", chip: "Jitter", content: "Sin jitter:\n1000 clientes reintentan a los 1000 ms.\n\nCon jitter:\n950 ms\n1100 ms\n870 ms\n1250 ms\n\nLa carga se reparte en el tiempo y el servicio tiene mas posibilidades de recuperarse." },
  { id: "polly", label: "10) Polly", title: "Aplicar politicas de retry", subtitle: "Una politica centralizada evita repetir la misma logica de resiliencia en cada cliente.", chip: ".NET", content: "AddHttpClient<PaymentsClient>()\n  .Handle<HttpRequestException>()\n  .OrResult(response => (int)response.StatusCode >= 500)\n  .WaitAndRetryAsync(3, retry =>\n      TimeSpan.FromSeconds(Math.Pow(2, retry)));\n\nLa politica debe clasificar errores y respetar idempotencia." },
  { id: "circuit", label: "11) Circuit Breaker", title: "Dejar de llamar a un servicio caido", subtitle: "Despues de muchos fallos, el circuito se abre y evita consumir recursos en llamadas inutiles.", chip: "Circuit", content: "Payments esta caido.\nOrders -> timeout\nOrders -> timeout\nOrders -> timeout\n\nSin breaker, Orders tambien colapsa.\n\nCon Circuit Breaker:\nse abre el circuito\nlas llamadas fallan rapido\nse protege el servicio llamador\nse puede usar fallback o estado pendiente." },
  { id: "circuit-states", label: "12) Estados", title: "Closed, Open y Half Open", subtitle: "El breaker prueba la recuperacion sin volver a saturar la dependencia.", chip: "Estados", content: "Closed:\nLas llamadas pasan normalmente.\n\nOpen:\nNo se hacen llamadas. Se responde rapido.\n\nHalf Open:\nDespues de esperar, permite algunas llamadas de prueba.\n\nSi funcionan -> Closed.\nSi fallan -> Open otra vez." },
  { id: "circuit-config", label: "13) Configuracion", title: "Definir umbrales", subtitle: "Los umbrales deben representar el comportamiento real del servicio y no ser numeros arbitrarios.", chip: "Config", content: "Ejemplo:\n5 errores -> abrir circuito.\n1 minuto -> permanecer abierto.\nDespues -> Half Open.\n\nMedir antes de ajustar:\nerror rate\nlatencia\nvolumen\ntiempo de recuperacion\n\nUn circuito abierto debe generar metricas y logs claros." },
  { id: "bulkhead", label: "14) Bulkhead", title: "Aislar recursos por dependencia", subtitle: "Si Payments consume todos los threads, Inventory no debe quedar sin capacidad.", chip: "Bulkhead", content: "Un barco tiene compartimentos: si uno se inunda, no se hunde entero.\n\nEn software:\nPayments tiene limites propios.\nInventory tiene limites propios.\nPools y conexiones se separan.\n\nPayments puede colapsar mientras Inventory sigue respondiendo." },
  { id: "ratelimit", label: "15) Rate Limiting", title: "Controlar el volumen", subtitle: "Cuando llegan mas peticiones de las que podemos atender, rechazamos de forma explicita.", chip: "Traffic", content: "10000 clientes llegan juntos.\n\nLimite: 100 peticiones por segundo.\n\nEl resto recibe:\n429 Too Many Requests\n\nRate limiting protege APIs, proveedores externos, base de datos y recursos compartidos." },
  { id: "fallback", label: "16) Fallback", title: "Degradacion elegante", subtitle: "Cuando una capacidad secundaria falla, el flujo principal puede seguir funcionando con una respuesta limitada.", chip: "Fallback", content: "Inventory no responde.\n\nEn vez de ocultar el fallo con un 500 generico:\nStock temporalmente no disponible.\n\nLa compra puede continuar si Inventory no era necesario para esa vista. La degradacion debe ser explicita y segura." },
  { id: "where", label: "17) Aplicacion", title: "Donde aplicar resiliencia", subtitle: "Cada frontera remota debe tener limites, pero no todas las politicas son iguales.", chip: "Diseño", content: "HTTP\nRabbitMQ\nRedis\nBase de datos\nServicios externos\nProveedor de pagos\n\nConfigurar timeout, retry, breaker, bulkhead y observabilidad de acuerdo con el contrato de cada dependencia." },
  { id: "no-retry", label: "18) No reintentar sin idempotencia", title: "Crear una orden puede duplicar efectos", subtitle: "Retry y una clave de idempotencia deben diseñarse juntos.", chip: "Idempotencia", content: "Crear orden\n  | retry automatico\n  v\nCrear otra orden\n\nSolo es seguro repetir si existe una Idempotency-Key estable.\n\nRetry + Idempotency Key = repeticion sin duplicar efectos." },
  { id: "saga", label: "19) Resiliencia en Saga", title: "Compensar y reintentar", subtitle: "La Saga no abandona una compensacion porque el primer intento haya fallado.", chip: "Saga", content: "ReleaseInventory falla.\n        |\n        v\nRetry con backoff\n        |\n        v\nAlerta\n        |\n        v\nIntervencion manual\n\nEl estado de la Saga debe conservar la accion pendiente, el error, el retry count y el proximo intento." },
  { id: "outbox", label: "20) Outbox e Inbox", title: "Patrones que ya aportan resiliencia", subtitle: "Outbox evita perder eventos e Inbox evita repetir sus efectos.", chip: "Mensajeria", content: "Outbox:\nRabbitMQ falla -> mensaje permanece -> retry.\n\nInbox:\nMensaje llega dos veces -> MessageId ya procesado -> una sola operacion.\n\nJuntos protegen la entrega al menos una vez y la idempotencia del consumidor." },
  { id: "health", label: "21) Health Checks", title: "Usar salud para decidir", subtitle: "El estado de una dependencia puede alimentar decisiones de circuitos, readiness y alertas.", chip: "Health", content: "/health\n\nPayments: Unhealthy\nRabbitMQ: Healthy\nPostgreSQL: Healthy\n\nSi Payments esta unhealthy, no iniciamos llamadas nuevas sin necesidad.\n\nHealth Check informa estado; no sustituye timeout ni reemplaza el manejo de errores." },
  { id: "metrics", label: "22) Medicion", title: "Que medir", subtitle: "Sin metricas no sabremos si la resiliencia esta protegiendo o escondiendo el problema.", chip: "Metrics", content: "Numero de retries\nCircuitos abiertos\nTimeouts\nErrores 5xx\nLatencia promedio\nLatencia p95 y maxima\nFallbacks ejecutados\nBulkhead rechazando\nSagas pendientes\nCompensaciones\n\nCada politica debe ser observable." },
  { id: "alerts", label: "23) Alertas", title: "Alertar sobre degradacion", subtitle: "Una alerta debe señalar una condicion accionable y contar con contexto operativo.", chip: "Alerting", content: "Circuit Breaker abierto durante mas de 5 minutos.\n\nTimeouts por encima de 20%.\n\nRetries creciendo continuamente.\n\nFallbacks superando el umbral.\n\nLa alerta debe incluir servicio, dependencia, CorrelationId cuando aplique y runbook." },
  { id: "flow", label: "24) Flujo completo", title: "Cuando Payments deja de responder", subtitle: "El sistema combina timeout, retry, breaker, fallback y recuperacion gradual.", chip: "Flujo", content: "Orders llama Payments\n        |\n        v\nTimeout\n        |\n        v\nRetry 1 -> falla\nRetry 2 -> falla\nRetry 3 -> falla\n        |\n        v\nCircuit Open\n        |\n        v\nFallback / Saga espera\n        |\n        v\nPayments vuelve\n        |\n        v\nHalf Open -> Closed" },
  { id: "anti-patterns", label: "25) Errores", title: "Errores comunes", subtitle: "Una politica mal configurada puede convertir un fallo local en una caida general.", chip: "Riesgos", content: "Retry infinito.\nSin timeout.\nTimeout enorme.\nRetry sobre 400.\nSin Circuit Breaker.\nSin idempotencia.\nTodos los clientes compartiendo recursos.\nFallback que oculta perdida de datos.\nBreaker sin metricas.\nCompensaciones sin deadline." },
  { id: "testing", label: "26) Pruebas", title: "Casos que debemos verificar", subtitle: "La resiliencia debe demostrarse bajo fallos temporales, permanentes y recuperaciones.", chip: "Testing", content: "Timeout devuelve respuesta contractual.\n503 activa retry.\n400 no activa retry.\nBackoff espera entre intentos.\nJitter distribuye llamadas.\nCircuit abre tras el umbral.\nHalf Open prueba la recuperacion.\nBulkhead protege otra dependencia.\nRate limit devuelve 429.\nFallback no crea cambios parciales.\nRetry de pago usa misma clave.\nSaga reintenta compensaciones." },
  { id: "checklist", label: "27) Checklist", title: "Validacion de resiliencia", subtitle: "El servicio esta preparado cuando puede fallar sin bloquear recursos ni duplicar efectos.", chip: "Checklist", content: "Timeouts definidos\nRetry limitado\nExponential Backoff\nJitter\nCircuit Breaker\nClosed/Open/Half Open\nBulkheads\nRate Limiting\nFallback\nHealth Checks\nMetricas\nAlertas\nIdempotencia\nCompensaciones con retry\nPruebas de recuperacion" },
  { id: "closing", label: "28) Cierre", title: "Como piensa un backend senior", subtitle: "No se trata de reintentar todo: se trata de fallar rapido, recuperarse con criterio y proteger el negocio.", chip: "Cierre", content: "Backend junior:\nSi falla, vuelvo a intentarlo.\n\nBackend senior:\nDefine timeout, clasifica el error, reintenta solo si es seguro, usa backoff y jitter, abre circuitos, aisla recursos, degrada con elegancia y mide cada decision.\n\nLa resiliencia es una propiedad del sistema, no una llamada a Polly aislada." },
];

export default function Daily145Client() {
  const [activeSection, setActiveSection] = useState("idea");

  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement | null;
      if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return;
      if (event.key.toLowerCase() === "p") window.location.href = "/daily/144";
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, []);

  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);

  return (
    <div className={styles.page}>
      <header className={styles.topbar}><div className={styles.topbarInner}>
        <div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Resiliencia avanzada en microservicios</div></div></div>
        <nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav>
        <div className={styles.actions}><Link className={styles.btn} href="/daily/144"><span className={styles.kbd}>←</span> Dia 144</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div>
      </div></header>
      <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}>
        <div className={styles.dailyHero}><div className={styles.createdAt}>31/07/2026</div><div className={styles.badge}>Daily #145 • Advanced Resilience</div><h2 className={styles.title}>Resiliencia avanzada: reintentos, Circuit Breaker, Timeouts y Bulkheads en microservicios</h2><p className={styles.lead}>Los servicios fallan, se ralentizan y se recuperan. La arquitectura debe limitar el impacto, evitar duplicados y continuar de forma controlada.</p></div>
        <nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>
        {sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}
        <div className={styles.footerNav}><Link className={styles.btn} href="/daily/144"><span className={styles.kbd}>←</span> Dia 144</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div>
      </div></article></div></main>
    </div>
  );
}
