"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "goal", label: "1) Objetivo", title: "Medir como se comporta el sistema bajo presion", subtitle: "Una API puede funcionar con una peticion y degradarse por completo cuando aumenta la concurrencia.", chip: "Performance", content: "Una peticion\n  -> funciona\n\n100 peticiones\n  -> puede funcionar\n\n1000 peticiones\n  -> aparecen colas, latencia, errores y consumo de recursos\n\nLas pruebas de carga buscan conocer limites, capacidad y forma de degradacion antes de que lo descubra produccion." },
  { id: "load", label: "2) Load Testing", title: "Carga esperada", subtitle: "Verificar que el sistema soporta el trafico normal y los picos razonables del negocio.", chip: "Load", content: "Usuarios esperados: 1000\nRequests por segundo: 100\nDuracion: 30 minutos\n\nMedir:\n- latencia\n- errores\n- throughput\n- CPU y memoria\n- base de datos\n- colas\n\nEl objetivo no es romper el sistema, sino demostrar que cumple su SLO bajo carga conocida." },
  { id: "stress", label: "3) Stress Testing", title: "Buscar el punto de ruptura", subtitle: "Aumentar la carga hasta encontrar cuando el sistema deja de cumplir el contrato.", chip: "Stress", content: "100 req/s -> estable\n200 req/s -> estable\n400 req/s -> latencia sube\n800 req/s -> aparecen 5xx\n\nPreguntas:\n- donde esta el cuello de botella?\n- falla rapido o se bloquea?\n- se recupera al retirar carga?\n- quedan cambios parciales?\n\nEl limite debe ser conocido y observable." },
  { id: "spike", label: "4) Spike Testing", title: "Un aumento brusco e inesperado", subtitle: "Simular campañas, eventos o reintentos masivos que elevan el trafico en segundos.", chip: "Spike", content: "10 req/s\n    | salto inmediato\n1000 req/s\n    |\nrecuperacion\n\nObservar autoscaling, colas, timeouts, circuit breakers, rate limiting y capacidad de la base de datos. Un sistema resiliente puede degradarse sin colapsar completamente." },
  { id: "soak", label: "5) Soak Testing", title: "Resistencia durante horas", subtitle: "Una prueba prolongada descubre fugas de memoria, conexiones sin liberar y degradacion acumulada.", chip: "Soak", content: "Carga estable durante 8 horas\n\nBuscar:\n- memoria creciendo\n- handles abiertos\n- conexiones agotadas\n- colas que crecen\n- logs excesivos\n- latencia que empeora\n- tareas que dejan de responder\n\nQue funcione cinco minutos no demuestra resistencia operativa." },
  { id: "metrics", label: "6) Metricas", title: "Que medir durante la prueba", subtitle: "Sin metricas de aplicacion e infraestructura, una carga solo produce numeros dificiles de interpretar.", chip: "Metricas", content: "Aplicacion:\n- requests por segundo\n- errores 4xx/5xx\n- latencia\n- timeouts\n- retries\n- circuitos abiertos\n\nInfraestructura:\n- CPU\n- memoria\n- conexiones\n- locks\n- I/O\n- profundidad de colas\n\nRelacionar siempre la metrica con el escenario ejecutado." },
  { id: "percentiles", label: "7) Percentiles", title: "La media puede ocultar el problema", subtitle: "Los percentiles muestran como experimentan la latencia los usuarios mas lentos.", chip: "Latencia", content: "Promedio: 120 ms\np50: 90 ms\np95: 300 ms\np99: 1.8 s\n\nEl promedio puede parecer saludable mientras un porcentaje importante sufre respuestas lentas. Reportar p50, p95, p99 y maxima junto al volumen y error rate." },
  { id: "throughput", label: "8) Throughput", title: "Cuanto trabajo procesa el sistema", subtitle: "Throughput es la cantidad de operaciones completadas por unidad de tiempo.", chip: "Capacidad", content: "Requests recibidas no siempre son requests completadas.\n\nMedir:\n- requests completadas por segundo\n- ordenes creadas\n- pagos procesados\n- mensajes consumidos\n- trabajos fallidos\n\nSi entran 1000 mensajes y solo se procesan 200, la cola y la latencia futura forman parte del problema." },
  { id: "orderflow", label: "9) OrderFlow", title: "Escenario de compra", subtitle: "El flujo de negocio debe probarse con sus dependencias y efectos secundarios relevantes.", chip: "OrderFlow", content: "POST /orders\n  -> agregar items\n  -> confirmar\n  -> reservar inventory\n  -> pagar\n  -> publicar evento\n\nMedir cada frontera: API, PostgreSQL, Redis, RabbitMQ, Payments y consumidores. El cuello de botella puede estar fuera del endpoint visible." },
  { id: "bottleneck", label: "10) Cuello de botella", title: "No optimizar a ciegas", subtitle: "El resultado debe explicar que recurso limita la capacidad y que cambio puede mejorarla.", chip: "Diagnostico", content: "CPU alta -> revisar computo o escalado.\nMemoria creciente -> buscar fuga o cache.\nBD lenta -> query plan, indices o locks.\nRabbitMQ acumulado -> consumidores o throughput.\nLatencia externa -> timeout, pool o dependencia.\n\nPrimero observar. Despues formular hipotesis. Finalmente repetir la prueba." },
  { id: "tools", label: "11) Herramientas", title: "Elegir una herramienta adecuada", subtitle: "La herramienta importa menos que el escenario, los datos y la interpretacion de resultados.", chip: "Tools", content: "k6: scripts y carga HTTP.\nJMeter: escenarios visuales y protocolos.\nGatling: escenarios programables.\nLocust: usuarios en Python.\nArtillery: pruebas simples y CI.\n\nElegir segun protocolo, equipo, reporting, integracion CI y capacidad de reproducir el escenario." },
  { id: "safe", label: "12) Seguridad", title: "No probar produccion a ciegas", subtitle: "Una prueba de carga puede crear datos, cobrar pagos, saturar dependencias o activar alertas reales.", chip: "Riesgo", content: "Antes de ejecutar:\n- usar entorno aislado\n- datos de prueba\n- proveedores mock o sandbox\n- limites de gasto\n- rate limits acordados\n- ventana comunicada\n- rollback preparado\n- observadores y alertas\n\nNunca lanzar un spike contra produccion sin autorizacion y plan de abortar." },
  { id: "analysis", label: "13) Analisis", title: "Leer el resultado", subtitle: "El informe debe distinguir capacidad, degradacion, error productivo y problema del entorno.", chip: "QA", content: "Preguntar:\n- se cumplio el SLO?\n- cual fue el maximo throughput sostenible?\n- cuando subio p95/p99?\n- que errores aparecieron?\n- el sistema se recupero?\n- hubo datos duplicados o parciales?\n- que dependencia domino la latencia?\n\nGuardar script, configuracion, version, datos, graficas y conclusion." },
  { id: "checklist", label: "14) Checklist", title: "Prueba de performance completa", subtitle: "Una prueba util es repetible, segura, observable y produce una decision tecnica.", chip: "Checklist", content: "Escenario definido\nCarga esperada conocida\nStress incremental\nSpike controlado\nSoak prolongado\nSLO y percentiles\nThroughput medido\nErrores y timeouts\nCPU y memoria\nBD y colas\nDependencias externas\nDatos aislados\nAbortar y recuperar\nInforme versionado\nAcciones posteriores" },
  { id: "closing", label: "15) Cierre", title: "Performance es comportamiento bajo presion", subtitle: "Un backend senior no pregunta solo si funciona: pregunta hasta donde funciona y como falla.", chip: "Cierre", content: "Load: soporta la carga esperada?\nStress: donde rompe?\nSpike: sobrevive al salto?\nSoak: resiste durante horas?\n\nLa meta no es obtener un numero impresionante. Es conocer limites, proteger el negocio y convertir mediciones en decisiones de arquitectura." },
];

export default function Daily155Client() {
  const [activeSection, setActiveSection] = useState("goal");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/154"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Pruebas de carga y resistencia</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/154"><span className={styles.kbd}>←</span> Dia 154</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>18/08/2026</div><div className={styles.badge}>Daily #155 • Performance Testing</div><h2 className={styles.title}>Pruebas de carga, estrés, spike y resistencia</h2><p className={styles.lead}>Conocer los limites de OrderFlow, medir su degradacion y saber si se recupera antes de enfrentarlo a trafico real.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/154"><span className={styles.kbd}>←</span> Dia 154</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
