"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "goal", label: "1) Objetivo", title: "Probar con infraestructura real y temporal", subtitle: "Un unit test puede pasar aunque falle el mapeo, la migracion, el broker o el wiring de la aplicacion.", chip: "Integration", content: "API\n  |\n  +-- PostgreSQL real\n  +-- RabbitMQ real\n  +-- WebApplicationFactory\n  +-- Testcontainers\n\nEl objetivo es aislar el entorno, no reemplazar con mocks aquello que queremos integrar." },
  { id: "containers", label: "2) Testcontainers", title: "Contenedores temporales para tests", subtitle: "Testcontainers levanta dependencias reales durante la suite y las elimina al terminar.", chip: "Docker", content: "Test\n  -> crear contenedor\n  -> esperar readiness\n  -> ejecutar escenario\n  -> limpiar\n\nEl test controla imagen, puerto, variables y ciclo de vida. El puerto puede ser dinamico y no debe asumirse uno fijo." },
  { id: "postgres", label: "3) PostgreSQL", title: "Una base real, pero temporal", subtitle: "Probar contra PostgreSQL real detecta errores de SQL, tipos, constraints, transacciones y configuracion.", chip: "PostgreSQL", content: "PostgreSQLContainer\n  |\n  v\nConnectionString dinamica\n  |\n  v\nDbContext de pruebas\n\nNo usar la base de desarrollo del equipo. Cada suite debe conocer exactamente que datos crea y como los limpia." },
  { id: "migrations", label: "4) Migrations", title: "Aplicar el esquema real", subtitle: "Una prueba de integracion debe levantar el mismo modelo que la aplicacion espera en produccion.", chip: "Persistencia", content: "Arranque del test:\n1. iniciar PostgreSQL\n2. construir connection string\n3. aplicar migrations\n4. inicializar datos minimos\n5. crear WebApplicationFactory\n\nEsto descubre migrations rotas, columnas incompatibles y diferencias entre provider local y real." },
  { id: "first-test", label: "5) Primer test", title: "Verificar persistencia de una orden", subtitle: "El caso feliz debe comprobar respuesta HTTP y estado final de la base de datos.", chip: "Happy path", content: "POST /orders\n  -> status esperado\n  -> DTO valido\n  -> Order persistida\n  -> Items relacionados\n  -> total correcto\n  -> estado inicial correcto\n\nNo basta con comprobar que la API devuelve 200: verificar el estado que queda en PostgreSQL." },
  { id: "constraints", label: "6) Restricciones", title: "Probar reglas que la base debe proteger", subtitle: "Las constraints y relaciones reales forman parte del comportamiento observable del sistema.", chip: "Integridad", content: "Casos:\n- SKU duplicado\n- foreign key inexistente\n- campo requerido ausente\n- orden sin items\n- estado invalido\n- eliminacion con dependencias\n\nComprobar codigo HTTP, error contractual y ausencia de cambios parciales." },
  { id: "concurrency", label: "7) Concurrencia", title: "Detectar carreras reales", subtitle: "Dos operaciones simultaneas pueden revelar problemas que ningun test secuencial encuentra.", chip: "Concurrencia", content: "Dos solicitudes reservan el mismo stock\n        |\n        v\nPostgreSQL aplica transaccion y aislamiento\n        |\n        v\nSolo una operacion debe ganar\n\nProbar optimistic concurrency, locks, unique constraints y resultado final, evitando tests no deterministas." },
  { id: "rabbit", label: "8) RabbitMQ", title: "Levantar un broker real", subtitle: "El broker temporal permite probar exchanges, colas, routing, acknowledgements y mensajes reales.", chip: "RabbitMQ", content: "RabbitMQContainer\n  |\n  v\nExchange -> Queue -> Consumer\n\nVerificar que el mensaje se publica, llega a la cola correcta, se procesa y se confirma. No usar sleeps arbitrarios: esperar condiciones observables con timeout." },
  { id: "events", label: "9) Eventos", title: "Probar publicación y consumo", subtitle: "Los eventos necesitan assertions sobre contrato, entrega, duplicados y efectos secundarios.", chip: "Mensajeria", content: "OrderConfirmed\n  -> exchange\n  -> queue Inventory\n  -> consumer\n  -> reserva de stock\n\nComprobar nombre, payload, correlation id, routing key, reintentos y que el consumidor produzca un solo efecto cuando corresponda." },
  { id: "outbox", label: "10) Outbox e Inbox", title: "Validar entrega e idempotencia", subtitle: "La infraestructura real permite comprobar los patrones que protegen eventos y consumidores.", chip: "Resiliencia", content: "Outbox:\ntransaccion de negocio + evento pendiente\n\nWorker:\npublica -> marca enviado\n\nInbox:\nmensaje duplicado -> MessageId ya procesado -> no repetir efecto\n\nVerificar tambien el fallo entre persistir y publicar." },
  { id: "factory", label: "11) WebApplicationFactory", title: "Arrancar la API completa en memoria", subtitle: "WebApplicationFactory permite probar el pipeline HTTP real con configuracion de test.", chip: ".NET", content: "Factory personalizada:\n- reemplazar connection string\n- conectar PostgreSQL del contenedor\n- conectar RabbitMQ de prueba\n- configurar environment Testing\n- crear HttpClient\n\nLa solicitud pasa por routing, middleware, autenticacion, validacion, servicios y persistencia." },
  { id: "organization", label: "12) Organizacion", title: "Separar proyectos y responsabilidades", subtitle: "La suite debe ser legible, repetible y compatible con la infraestructura oficial del repositorio.", chip: "Estructura", content: "IntegrationTests\n  +-- Fixtures\n  +-- Factories\n  +-- Containers\n  +-- Orders\n  +-- Payments\n  +-- Messaging\n\nReutilizar fixtures. No crear una segunda base, autenticacion o mecanismo de limpieza paralelo sin necesidad demostrada." },
  { id: "isolation", label: "13) Aislamiento", title: "Infraestructura compartida no es datos compartidos", subtitle: "Podemos compartir contenedores para acelerar, pero cada test debe aislar sus datos y no depender del orden.", chip: "Determinismo", content: "Correcto:\n- nombres unicos\n- cleanup explicito\n- transacciones cuando aplique\n- fixtures controladas\n- tests independientes\n\nIncorrecto:\n- depender del test anterior\n- asumir orden de ejecucion\n- reutilizar IDs fijos\n- dejar mensajes o filas contaminadas." },
  { id: "ci", label: "14) CI", title: "Ejecutar la misma infraestructura en CI", subtitle: "El pipeline debe poder iniciar Docker, levantar dependencias, ejecutar tests y limpiar siempre.", chip: "CI/CD", content: "Commit\n  -> build\n  -> Docker disponible\n  -> PostgreSQL/RabbitMQ temporales\n  -> integration tests\n  -> logs y reportes\n  -> cleanup\n\nRegistrar imagenes, versiones, duracion y causa de fallos. Un test bloqueado por entorno no es un test verde." },
  { id: "floci", label: "15) Floci", title: "Cuando el servicio es AWS", subtitle: "Floci puede complementar Testcontainers para probar contratos AWS localmente, sin ocultar las diferencias con cloud real.", chip: "AWS", content: "API -> Floci -> S3/SQS\n\nUsar Floci para desarrollo e integracion local. Validar en staging real las propiedades especificas de AWS: IAM, limites, networking, rendimiento y disponibilidad." },
  { id: "limits", label: "16) Limites", title: "Que no debemos probar con Testcontainers", subtitle: "No todo riesgo se resuelve levantando otro contenedor dentro de cada test.", chip: "Criterio", content: "No sustituye:\n- pruebas de carga prolongadas\n- disponibilidad multi-zona\n- fallos de hardware cloud\n- IAM real de produccion\n- contratos de proveedores no reproducibles\n\nElegir la herramienta segun el riesgo y conservar pruebas de entorno real donde sean necesarias." },
  { id: "checklist", label: "17) Checklist", title: "Integracion confiable", subtitle: "La suite merece confianza cuando comprueba estado, mensajes, errores y aislamiento de forma repetible.", chip: "Checklist", content: "PostgreSQL real y temporal\nMigrations aplicadas\nConstraints verificadas\nTransacciones y rollback\nConcurrencia relevante\nRabbitMQ real\nEventos y routing\nOutbox e Inbox\nWebApplicationFactory\nDatos aislados\nSin orden entre tests\nCI reproducible\nLogs y cleanup\nFloci o staging para AWS" },
  { id: "closing", label: "18) Cierre", title: "La infraestructura forma parte del test", subtitle: "Un backend senior prueba las fronteras reales antes de confiar en que todo funciona en produccion.", chip: "Cierre", content: "Unit tests explican reglas.\nIntegration tests verifican componentes reales.\nContract tests protegen acuerdos.\nE2E demuestra caminos criticos.\n\nTestcontainers no es magia ni un fin en si mismo. Es una forma controlada de obtener evidencia real sobre base de datos, broker y pipeline de la aplicacion." },
];

export default function Daily153Client() {
  const [activeSection, setActiveSection] = useState("goal");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/152"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Integration Testing con infraestructura real</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/152"><span className={styles.kbd}>←</span> Dia 152</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>14/08/2026</div><div className={styles.badge}>Daily #153 • Real Infrastructure</div><h2 className={styles.title}>Integration Testing con infraestructura real</h2><p className={styles.lead}>Testcontainers, PostgreSQL, RabbitMQ y WebApplicationFactory para comprobar que OrderFlow funciona fuera del aislamiento de los mocks.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/152"><span className={styles.kbd}>←</span> Dia 152</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
