"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "problem", label: "1) Problema", title: "Funcionar no significa estar terminado", subtitle: "TradeOps 360 necesita evidencia de calidad, diagnóstico, rendimiento y una operación de despliegue repetible.", chip: "Contexto", content: "Un módulo no está terminado cuando:\n- abre la vista\n- guarda un registro\n- funciona una vez\n\nEstá listo cuando:\n- las reglas tienen tests\n- los fallos se diagnostican\n- las consultas son razonables\n- el despliegue es reversible\n- el flujo crítico tiene smoke test." },
  { id: "testing", label: "2) Testing", title: "Probar el comportamiento del negocio", subtitle: "Los tests deben proteger reglas, relaciones y flujos completos, no solo líneas de código.", chip: "QA", content: "TradeOps debe probar:\n- importaciones\n- preventas\n- pagos\n- preventas convertidas\n- distribución\n- entregas parciales\n- incidencias\n- auditoría\n- integraciones\n\nVerificar resultados y estado persistido." },
  { id: "transaction-case", label: "3) TransactionCase", title: "Aislar los tests de Odoo", subtitle: "TransactionCase permite probar modelos y reglas dentro de una transacción controlada.", chip: "Odoo Tests", content: "from odoo.tests.common import TransactionCase\n\nclass TestTradeImport(TransactionCase):\n    def test_import_has_valid_state(self):\n        record = self.env['trade.import'].create({...})\n        self.assertEqual(record.state, 'draft')\n\nUn test claro expresa una regla observable." },
  { id: "regression", label: "4) Regresion", title: "La cobertura también protege lo anterior", subtitle: "Cada cambio debe demostrar que los flujos existentes siguen funcionando.", chip: "Regression", content: "Antes de cambiar:\n- ejecutar la regresión existente\n- guardar resultados\n- identificar fallos previos\n\nDespués de cambiar:\n- ejecutar tests nuevos\n- repetir tests afectados\n- ejecutar el smoke test\n\nNo ocultar un fallo debilitando una aserción." },
  { id: "debugging", label: "5) Debugging", title: "Investigar antes de tocar", subtitle: "Un error reproducible y bien aislado permite corregir la causa en vez de parchear el síntoma.", chip: "Debug", content: "Flujo de debugging:\n1. reproducir\n2. leer traceback\n3. identificar modelo y método\n4. revisar contexto y permisos\n5. aislar datos mínimos\n6. corregir\n7. repetir el test\n\nEl error es evidencia del comportamiento actual." },
  { id: "logs", label: "6) Logs", title: "Los logs cuentan lo que el usuario no ve", subtitle: "Registrar contexto útil ayuda a separar datos inválidos, permisos, dependencias y errores de código.", chip: "Observabilidad", content: "Registrar con criterio:\n- modelo y operación\n- identificador técnico\n- usuario y compañía\n- integración invocada\n- duración\n- resultado o error\n\nNunca incluir contraseñas, tokens ni datos sensibles." },
  { id: "shell", label: "7) Odoo Shell", title: "Inspeccionar el sistema con contexto real", subtitle: "Odoo Shell permite consultar modelos, relaciones y estados usando el Environment del servidor.", chip: "Herramienta", content: "env['trade.import'].search([\n    ('state', '=', 'receiving')\n])\n\nUsos:\n- comprobar datos\n- reproducir una regla\n- inspeccionar relaciones\n- validar una hipótesis\n\nNo usar SQL improvisado para arreglar producción." },
  { id: "n-plus-one", label: "8) Performance", title: "Detectar el problema N+1", subtitle: "Recorrer registros y disparar una consulta por cada línea puede degradar el sistema rápidamente.", chip: "Performance", content: "Riesgo:\nfor presale in presales:\n    print(presale.import_id.name)\n\nMejor:\n- usar recordsets\n- aprovechar prefetch\n- hacer búsquedas agrupadas\n- revisar consultas generadas\n- medir antes y después\n\nLa legibilidad y el rendimiento deben coexistir." },
  { id: "recordsets", label: "9) Recordsets", title: "Trabajar con el ORM de forma eficiente", subtitle: "Recordsets y prefetch reducen consultas repetidas cuando se recorren relaciones del dominio.", chip: "ORM", content: "imports = self.env['trade.import'].search([])\nproducts = imports.mapped('line_ids.product_id')\n\nEvitar búsquedas dentro de bucles cuando una operación sobre el conjunto expresa mejor la intención." },
  { id: "indexes", label: "10) Indices", title: "Indexar lo que se consulta", subtitle: "Los índices ayudan en búsquedas frecuentes, pero tienen coste de escritura y no sustituyen analizar el query plan.", chip: "Database", content: "Preguntar antes de indexar:\n- ¿se filtra a menudo?\n- ¿la columna tiene selectividad?\n- ¿qué volumen tendrá?\n- ¿el índice mejora el plan?\n\nMedir con datos realistas y evitar índices por intuición." },
  { id: "deploy", label: "11) Deploy", title: "Desplegar es actualizar un sistema vivo", subtitle: "Un addon nuevo necesita instalación; un addon existente necesita una actualización controlada.", chip: "Deploy", content: "Instalar:\n-i trade_import\n\nActualizar:\n-u trade_import\n\nAntes de ejecutar:\n- validar dependencias\n- revisar vistas y datos\n- hacer backup\n- comprobar migraciones\n- definir rollback" },
  { id: "backup", label: "12) Backup", title: "El backup es parte del despliegue", subtitle: "No existe rollback operativo si no podemos recuperar los datos y la versión anterior.", chip: "Recovery", content: "Antes del deploy:\n- backup de PostgreSQL\n- identificar versión desplegada\n- guardar configuración\n- registrar commit\n- probar restauración cuando sea posible\n\nUn backup no probado es una suposición, no una garantía." },
  { id: "rollback", label: "13) Rollback", title: "Preparar cómo volver atrás", subtitle: "Rollback puede significar restaurar código, revertir módulo o recuperar datos; debe estar definido antes del incidente.", chip: "Resiliencia", content: "Deploy\n  -> smoke test\n  -> observar\n  -> mantener o revertir\n\nDocumentar:\n- señal de rollback\n- responsable\n- comando o procedimiento\n- impacto de datos\n- validación posterior" },
  { id: "smoke", label: "14) Smoke Test", title: "Comprobar el camino crítico después del deploy", subtitle: "Un smoke test rápido confirma que el módulo carga y que el flujo principal sigue disponible.", chip: "Verification", content: "Smoke test TradeOps:\n1. abrir modulo\n2. crear importacion\n3. agregar linea\n4. validar estado\n5. crear preventa\n6. convertir a sale.order\n7. planificar distribucion\n8. revisar auditoria\n\nNo reemplaza la suite: la complementa." },
  { id: "e2e", label: "15) E2E", title: "El flujo completo de TradeOps 360", subtitle: "La prueba final une dominio, ventas, distribución, inventario, pagos, notificaciones y reportes.", chip: "E2E", content: "Importación\n  -> Preventa\n  -> sale.order\n  -> Distribución\n  -> stock.picking\n  -> Entrega\n  -> Incidencia si aplica\n  -> Auditoría\n  -> Reporte\n\nVerificar cada frontera y la trazabilidad final." },
  { id: "v1", label: "16) v1.0", title: "Definir qué significa terminar", subtitle: "Una versión profesional también se define por lo que explícitamente queda fuera de alcance.", chip: "Scope", content: "TradeOps 360 v1.0 incluye:\n- importaciones\n- preventas\n- pagos\n- conversiones\n- distribución\n- entregas parciales\n- incidencias\n- auditoría\n- notificaciones\n- reportes\n- testing y despliegue\n\nEl backlog futuro debe estar separado." },
  { id: "checklist", label: "17) Checklist", title: "Checklist de cierre", subtitle: "Antes de llamar v1.0 al sistema, revisar calidad, datos, operación y recuperación.", chip: "Checklist", content: "[ ] tests unitarios y de transacción\n[ ] regresión ejecutada\n[ ] errores diagnosticables\n[ ] consultas medidas\n[ ] índices justificados\n[ ] backup disponible\n[ ] upgrade probado\n[ ] rollback documentado\n[ ] smoke test verde\n[ ] permisos revisados\n[ ] auditoría verificable\n[ ] pendientes documentados" },
  { id: "closing", label: "18) Cierre", title: "TradeOps 360 v1.0 está preparado para operar", subtitle: "Cerrar un bloque no es dejar de mejorar: es conocer el estado real y poder continuar con seguridad.", chip: "Cierre", content: "Regla mental:\n\nProbar antes de afirmar.\nMedir antes de optimizar.\nRespaldar antes de desplegar.\nObservar después de publicar.\nRevertir con un plan.\n\nUn sistema profesional no es el que nunca falla; es el que puede detectar, explicar y recuperarse." },
];

export default function Daily175Client() {
  const [activeSection, setActiveSection] = useState("problem");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/174"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Testing, despliegue y cierre de TradeOps</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/174"><span className={styles.kbd}>←</span> Dia 174</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>14/09/2026</div><div className={styles.badge}>Daily #175 • TradeOps 360 v1.0</div><h2 className={styles.title}>Testing, debugging, performance, despliegue y cierre de TradeOps 360 v1.0</h2><p className={styles.lead}>Verificar el sistema completo, prepararlo para operar y cerrar el bloque con evidencia de calidad y recuperación.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/174"><span className={styles.kbd}>←</span> Dia 174</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
