"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "idea", label: "1) Idea clave", title: "Desplegar no es solo subir codigo", subtitle: "Una API .NET necesita compute, red, persistencia, secretos, health checks, observabilidad y una estrategia de actualizacion.", chip: "Deploy", content: "Codigo -> imagen Docker -> registry -> compute -> red -> datos -> observabilidad\n\nEl objetivo no es que la API arranque una vez. Debe poder recibir trafico, escalar, actualizarse y recuperarse cuando algo falle." },
  { id: "request", label: "2) Peticion", title: "El camino de una peticion", subtitle: "Entender el recorrido ayuda a elegir servicios y detectar donde puede fallar el sistema.", chip: "Arquitectura", content: "Cliente\n  |\nDNS\n  |\nLoad Balancer\n  |\nECS/Fargate, EC2 o App Runner\n  |\nAPI .NET\n  |\nRDS - Redis - S3 - RabbitMQ\n\nCada frontera necesita permisos, timeouts, logs y metricas." },
  { id: "options", label: "3) Opciones", title: "EC2, Elastic Beanstalk, ECS y App Runner", subtitle: "AWS ofrece distintos niveles de control y operacion para ejecutar una API.", chip: "Compute", content: "EC2: maximo control, mas responsabilidad.\nElastic Beanstalk: plataforma administrada para aplicaciones.\nECS/Fargate: contenedores sin administrar servidores.\nApp Runner: camino sencillo desde codigo o imagen a una API publica.\n\nLa eleccion depende del control requerido, experiencia del equipo, escalado y complejidad operativa." },
  { id: "ec2", label: "4) EC2", title: "Cuando elegir una maquina virtual", subtitle: "EC2 es util cuando necesitas control del sistema operativo o software muy especifico.", chip: "EC2", content: "API en EC2\n  |\nSecurity Group\n  |\nPostgreSQL administrado\n\nDebes operar parches, procesos, escalado, despliegues, logs y recuperacion. Es flexible, pero requiere mas trabajo que una plataforma de contenedores." },
  { id: "container", label: "5) Contenedores", title: "ECS y Fargate", subtitle: "El contenedor conserva el artefacto de Docker y el runtime se ocupa de ejecutarlo.", chip: "ECS", content: "Dockerfile\n  -> docker build\n  -> Amazon ECR\n  -> ECS Task Definition\n  -> ECS Service\n  -> Fargate\n\nECS administra tareas y servicios. Fargate evita administrar servidores y permite definir CPU, memoria, red, roles y variables." },
  { id: "ecr", label: "6) Registry", title: "Publicar la imagen en ECR", subtitle: "ECR es el registro privado donde AWS puede obtener la imagen de la API.", chip: "ECR", content: "docker build -t orderflow-api .\ndocker tag orderflow-api:latest <account>.dkr.ecr.<region>.amazonaws.com/orderflow-api:latest\ndocker push <repository>/orderflow-api:latest\n\nNo usar latest como unica estrategia en produccion. Preferir tags inmutables ligados a commit o version." },
  { id: "data", label: "7) Persistencia", title: "PostgreSQL, Redis e imagenes", subtitle: "La API y sus datos tienen necesidades distintas de durabilidad, latencia y disponibilidad.", chip: "Datos", content: "PostgreSQL -> Amazon RDS\nRedis -> ElastiCache\nImagenes y documentos -> S3\n\nLa base de datos no debe vivir dentro del contenedor efimero de la API. Definir backups, retencion, cifrado, acceso privado y restauracion probada." },
  { id: "config", label: "8) Configuracion", title: "Variables de entorno y secretos", subtitle: "El mismo artefacto debe desplegarse en ambientes distintos sin recompilar.", chip: "Seguridad", content: "ASPNETCORE_ENVIRONMENT=Production\nConnectionStrings__Default=...\nRabbitMq__Host=...\n\nLos valores sensibles deben venir de Secrets Manager o del mecanismo seguro del runtime. No guardar credenciales en Git, Dockerfile, imagenes ni logs." },
  { id: "health", label: "9) Health Checks", title: "Saber si la API puede recibir trafico", subtitle: "Liveness detecta procesos bloqueados; readiness indica si la instancia esta lista para servir.", chip: "Health", content: "/health/live\n/health/ready\n\nReadiness puede comprobar dependencias necesarias como PostgreSQL o RabbitMQ. Un check debe ser rapido y no generar una carga que empeore el incidente." },
  { id: "scaling", label: "10) Escalado", title: "Replicas y Auto Scaling", subtitle: "Escalar significa aumentar capacidad sin perder consistencia ni saturar dependencias.", chip: "Scaling", content: "Load Balancer\n  |\n+ API task\n+ API task\n+ API task\n\nEscalar por CPU, memoria, peticiones o latencia. La API debe ser stateless o externalizar sesiones, y PostgreSQL y proveedores externos tambien deben soportar el aumento." },
  { id: "load-balancer", label: "11) Load Balancer", title: "Distribuir trafico y actualizar gradualmente", subtitle: "El balanceador dirige peticiones a instancias sanas y ayuda a ejecutar despliegues seguros.", chip: "Networking", content: "Cliente -> HTTPS -> Load Balancer -> Target sano\n\nConfigurar certificados, security groups, health checks, timeouts y reglas de routing. No exponer directamente cada tarea de la API." },
  { id: "updates", label: "12) Actualizaciones", title: "Rolling Deployment", subtitle: "Reemplazar instancias gradualmente reduce el riesgo y permite observar la nueva version.", chip: "Release", content: "Version 1: 3 tareas\nVersion 2: inicia 1 tarea\nHealth check OK\nVersion 1: termina 1 tarea\nVersion 2: inicia otra\n\nLa aplicacion debe tolerar coexistencia temporal de versiones y contratos compatibles." },
  { id: "failure", label: "13) Fallos", title: "Que ocurre si una tarea falla", subtitle: "El scheduler puede reemplazar tareas, pero la aplicacion debe ser recuperable y observable.", chip: "Resiliencia", content: "Tarea unhealthy\n  -> Load Balancer deja de enviar trafico\n  -> ECS la reemplaza\n  -> nueva tarea inicia\n  -> readiness OK\n\nLogs, metricas, alertas y un runbook permiten distinguir un fallo aislado de una regresion de despliegue." },
  { id: "observability", label: "14) Operacion", title: "Logs, metricas y costes", subtitle: "Una API desplegada sin observabilidad es dificil de operar y puede generar costes inesperados.", chip: "CloudWatch", content: "Logs: errores, version, CorrelationId y contexto seguro.\nMetricas: latencia p95, 5xx, CPU, memoria, tareas y colas.\nAlertas: condiciones accionables con runbook.\nCostes: billing alerts, tags, limites y recursos sin uso.\n\nOpenTelemetry puede complementar CloudWatch con trazas distribuidas." },
  { id: "pipeline", label: "15) Pipeline", title: "Del commit a produccion", subtitle: "CI/CD automatiza tests, imagen, seguridad y despliegue repetible.", chip: "CI/CD", content: "Commit\n  -> tests\n  -> build Docker\n  -> scan\n  -> push ECR\n  -> deploy ECS\n  -> health checks\n  -> smoke tests\n  -> observacion\n\nEl pipeline debe poder detenerse, hacer rollback y conservar trazabilidad de la version desplegada." },
  { id: "architecture", label: "16) Arquitectura", title: "OrderFlow desplegado en AWS", subtitle: "Los componentes locales se convierten en servicios administrados y workloads reproducibles.", chip: "OrderFlow", content: "Route 53 / Load Balancer\n          |\n      ECS/Fargate\n Orders - Inventory - Payments\n      |       |\n    RDS    ElastiCache\n      |\n S3 - RabbitMQ - CloudWatch\n\nIAM, Secrets Manager, VPC, backups, health checks y CI/CD completan la operacion." },
  { id: "mistakes", label: "17) Errores", title: "Errores comunes", subtitle: "La primera arquitectura cloud debe ser controlable antes que espectacular.", chip: "Riesgos", content: "- desplegar sin health checks\n- exponer RDS a Internet\n- usar latest sin version\n- no definir limites de CPU y memoria\n- guardar secretos en la imagen\n- no probar rollback\n- ignorar costes\n- crear un cluster antes de necesitarlo\n\nLa simplicidad reduce superficie de fallo." },
  { id: "checklist", label: "18) Checklist", title: "API lista para AWS", subtitle: "Antes de considerar terminado el despliegue, hay que demostrar el flujo completo.", chip: "Checklist", content: "Dockerfile reproducible\nImagen en ECR\nECS/Fargate o runtime elegido\nVPC y Security Groups\nHTTPS y Load Balancer\nVariables externas\nSecretos protegidos\nRDS con backup\nRedis con politica definida\nS3 privado\nHealth checks\nAuto Scaling\nLogs y metricas\nCI/CD\nRollback probado\nAlertas de coste" },
  { id: "closing", label: "19) Cierre", title: "Desplegar es diseñar la operacion", subtitle: "Una API backend profesional debe ser ejecutable, observable, actualizable y recuperable.", chip: "Cierre", content: "Backend junior:\nMi API funciona en local.\n\nBackend senior:\nComo se publica? Quien puede acceder? Donde viven los datos? Como escala? Como se actualiza? Como se recupera? Cuanto cuesta?\n\nAWS no reemplaza la arquitectura. Le da una plataforma para llevarla a produccion." },
];

export default function Daily148Client() {
  const [activeSection, setActiveSection] = useState("idea");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/147"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Desplegar una API .NET en AWS</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/147"><span className={styles.kbd}>←</span> Dia 147</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>03/08/2026</div><div className={styles.badge}>Daily #148 • AWS Deployment</div><h2 className={styles.title}>Desplegar una API .NET en AWS</h2><p className={styles.lead}>De la imagen Docker al servicio cloud: compute, red, datos, seguridad, observabilidad y despliegues seguros.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/147"><span className={styles.kbd}>←</span> Dia 147</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
