"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "goal", label: "1) Objetivo", title: "No probar por probar", subtitle: "Una estrategia real conecta riesgos, capas del sistema, tipos de prueba y resultados observables.", chip: "Testing", content: "OrderFlow\n  |\n  +-- Dominio\n  +-- Persistencia\n  +-- API\n  +-- Eventos\n  +-- Servicios externos\n\nLa pregunta no es cuantos tests tenemos.\nLa pregunta es que riesgos cubren y que confianza aportan." },
  { id: "unit", label: "2) Unit Tests", title: "Probar reglas aisladas", subtitle: "Los unit tests son rapidos y precisos para invariantes y decisiones de dominio.", chip: "Unit", content: "Order vacia -> no puede confirmarse\nOrder confirmada -> no puede modificarse\nOrder pagada -> no puede pagarse otra vez\nTotal -> suma correcta de items\nCancelacion -> solo en estados permitidos\n\nNo necesitan Docker, base de datos ni red. Deben ser deterministas y faciles de leer." },
  { id: "integration", label: "3) Integration Tests", title: "Probar componentes reales juntos", subtitle: "La integracion verifica persistencia, mapeos, transacciones y contratos entre piezas.", chip: "Integration", content: "API\n  |\nRepository real\n  |\nPostgreSQL de prueba\n\nComprobar:\n- status HTTP\n- body y headers\n- datos persistidos\n- relaciones\n- rollback\n- ausencia de cambios parciales\n\nReutilizar fixtures y la infraestructura oficial del repositorio." },
  { id: "functional", label: "4) Functional Tests", title: "Probar capacidades del sistema", subtitle: "El test funcional valida un comportamiento desde la perspectiva de una funcionalidad completa.", chip: "Functional", content: "Crear orden\n  -> agregar items\n  -> confirmar\n  -> pagar\n  -> auditar\n\nEl foco es el resultado del caso de uso, no la implementación interna. Puede combinar API, persistencia y mensajeria si eso forma parte del flujo real." },
  { id: "contract", label: "5) Contract Tests", title: "Proteger los contratos entre servicios", subtitle: "Los contratos evitan que un productor rompa a consumidores que evolucionan de forma independiente.", chip: "Contract", content: "Orders publica OrderConfirmed\n  |\n  v\nInventory / Payments / Notifications\n\nVerificar nombres, tipos, campos obligatorios, compatibilidad y errores. Tambien aplica a HTTP, DTOs, eventos y mensajes RabbitMQ/SQS." },
  { id: "e2e", label: "6) E2E", title: "Probar el recorrido completo", subtitle: "E2E demuestra que el sistema funciona como lo usa un usuario o cliente real.", chip: "E2E", content: "Cliente\n  -> API\n  -> Orders\n  -> Inventory\n  -> Payments\n  -> evento\n  -> auditoria\n\nSon valiosos para caminos criticos, pero lentos, fragiles y costosos de diagnosticar. No deben sustituir toda la piramide." },
  { id: "pyramid", label: "7) Piramide", title: "Muchas pruebas rapidas, pocas caras", subtitle: "La distribucion de pruebas debe equilibrar feedback, confianza y coste de mantenimiento.", chip: "Piramide", content: "          E2E\n       Contract\n    Functional\n  Integration\nUnit Unit Unit Unit\n\nUnit: muchas y rapidas.\nIntegration: suficientes para fronteras reales.\nContract: protegen comunicaciones.\nE2E: pocos flujos criticos." },
  { id: "mocks", label: "8) Mocks", title: "Usar mocks donde aportan aislamiento", subtitle: "Un mock es util para controlar una dependencia externa o una condicion dificil de reproducir.", chip: "Mocks", content: "Mock apropiado:\n- proveedor de pagos externo\n- reloj\n- servicio caido\n- respuesta lenta\n- error de red\n\nEl mock debe representar un contrato real y no ocultar errores del componente que pretendemos integrar." },
  { id: "no-mocks", label: "9) Limites", title: "No abusar de mocks", subtitle: "Mockear la base de datos o el broker en una prueba de integracion elimina precisamente lo que se queria verificar.", chip: "Riesgos", content: "Si probamos persistencia, usar persistencia real de prueba.\nSi probamos routing, usar el cliente HTTP real.\nSi probamos eventos, usar el mecanismo de mensajeria que corresponda.\n\nMocks para aislar fronteras externas; infraestructura real para validar integracion." },
  { id: "orderflow", label: "10) Caso completo", title: "La compra de OrderFlow", subtitle: "Un mismo flujo necesita varias capas de pruebas, cada una con una responsabilidad clara.", chip: "OrderFlow", content: "Dominio: reglas de Order y Payment.\nPersistencia: repositories y transacciones.\nAPI: endpoints, DTOs y errores.\nEvento: contrato OrderPaid.\nCompra completa: camino feliz E2E.\n\nNo convertir un unico E2E en la unica evidencia de que todo funciona." },
  { id: "failures", label: "11) Fallos", title: "Probar cuando las cosas salen mal", subtitle: "La calidad se demuestra tambien con timeouts, duplicados, dependencias caidas y cambios parciales.", chip: "Resiliencia", content: "Payments timeout -> respuesta contractual\nPayment 503 -> retry limitado\nPayment 400 -> no retry\nMensaje duplicado -> Inbox/idempotencia\nRabbitMQ caido -> Outbox conserva evento\nBD falla -> rollback\nCircuit abierto -> fallback o estado pendiente\n\nCada fallo debe verificar respuesta y estado final." },
  { id: "matrix", label: "12) Matriz", title: "Relacionar riesgo, prueba y resultado", subtitle: "Una matriz evita huecos silenciosos y duplicacion de escenarios equivalentes.", chip: "Cobertura", content: "Riesgo                 Prueba          Evidencia\nOrder invalida           Unit             Excepcion/regla\nPersistencia incorrecta  Integration     Estado BD\nDTO roto                 Contract         Schema\nPago externo caido       Integration     Error/rollback\nCompra critica           E2E              Flujo completo\nEvento duplicado         Integration     Una sola operacion\n\nRegistrar tambien bloqueos, defectos y pendientes." },
  { id: "coverage", label: "13) Cobertura", title: "Cobertura no es solo porcentaje", subtitle: "Un numero alto no garantiza que los riesgos criticos esten cubiertos.", chip: "QA", content: "Revisar:\n- endpoints nuevos o modificados\n- estados y transiciones\n- errores y codigos HTTP\n- persistencia y atomicidad\n- autenticacion y permisos\n- eventos y efectos secundarios\n- dependencias externas\n- concurrencia e idempotencia\n\nLa cobertura debe hablar de comportamiento, no solo de lineas ejecutadas." },
  { id: "workflow", label: "14) Flujo", title: "Como trabajar cada cambio", subtitle: "El repositorio es la fuente de verdad y Git mantiene la trazabilidad entre cambio, test y resultado.", chip: "Proceso", content: "1. Revisar instrucciones y arquitectura.\n2. Identificar cambios desde la ultima revision.\n3. Localizar tests existentes.\n4. Analizar endpoints y reglas.\n5. Crear matriz de cobertura.\n6. Implementar escenarios aprobados.\n7. Ejecutar tests especificos y suite.\n8. Registrar resultados y pendientes." },
  { id: "checklist", label: "15) Checklist", title: "Estrategia minima para OrderFlow", subtitle: "Antes de cerrar una funcionalidad debemos poder explicar que esta cubierto y que no.", chip: "Checklist", content: "Unit tests de dominio\nIntegration tests de persistencia\nAPI tests de contratos y errores\nContract tests de eventos\nE2E de compra critica\nFallos de dependencias\nIdempotencia y duplicados\nRollback y atomicidad\nFixtures deterministas\nComandos oficiales ejecutados\nTrazabilidad actualizada" },
  { id: "closing", label: "16) Cierre", title: "Testing es diseño de confianza", subtitle: "Un backend senior no acumula tests: construye evidencia suficiente para cambiar el sistema con seguridad.", chip: "Cierre", content: "Unit protege reglas.\nIntegration protege fronteras.\nContract protege acuerdos.\nFunctional protege capacidades.\nE2E protege caminos criticos.\n\nLa mejor estrategia no es probar todo igual. Es probar cada riesgo en la capa que ofrece la evidencia mas clara y economica." },
];

export default function Daily152Client() {
  const [activeSection, setActiveSection] = useState("goal");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/151"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Diseñar una estrategia de testing real</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/151"><span className={styles.kbd}>←</span> Dia 151</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>13/08/2026</div><div className={styles.badge}>Daily #152 • Testing Strategy</div><h2 className={styles.title}>Diseñar una estrategia de testing real</h2><p className={styles.lead}>Unit, integration, contract y E2E aplicados a OrderFlow para construir evidencia de calidad sin duplicar pruebas.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/151"><span className={styles.kbd}>←</span> Dia 151</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
