"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "idea", label: "1) Idea clave", title: "Conectar servicios sin encadenarlos", subtitle: "Orders, Inventory y Payments ya son independientes; ahora deben colaborar sin acoplar todas sus decisiones.", chip: "Idea", content: "Orders confirma la orden\n        |\n        v\nInventory reserva unidades\n        |\n        v\nPayments procesa el cobro\n        |\n        v\nInventory confirma consumo\n        |\n        v\nOrders completa la orden\n\nHoy comenzamos a conectar este flujo mediante RabbitMQ." },
  { id: "http", label: "2) HTTP directo", title: "El problema de encadenar llamadas", subtitle: "Una cadena sincronica obliga a Orders a conocer direcciones, contratos, tiempos y errores de todos los servicios.", chip: "Acoplamiento", content: "Cliente\n  |\n  v\nOrders --HTTP--> Inventory --HTTP--> Payments --HTTP--> Orders\n\nLa solicitud del cliente debe esperar todo el flujo.\n\nSi Payments no responde, aparecen preguntas sobre el estado de la orden, la reserva y los reintentos." },
  { id: "rabbit", label: "3) RabbitMQ", title: "Un intermediario de mensajes", subtitle: "El productor publica, RabbitMQ conserva y el consumidor procesa cuando esta disponible.", chip: "Mensajeria", content: "Productor\n    |\n    v\nRabbitMQ\n    |\n    v\nConsumidor\n\nSi Inventory esta apagado, el mensaje puede permanecer en la cola. Cuando vuelve, procesa el mensaje pendiente.\n\nRabbitMQ no elimina fallos: permite administrarlos de forma controlada." },
  { id: "event-command", label: "4) Evento vs comando", title: "Comunicar hechos y solicitar acciones", subtitle: "Un evento informa algo que ocurrio; un comando pide a un destinatario que haga algo.", chip: "Conceptos", content: "Evento:\nOrderConfirmed\nPaymentApproved\nInventoryReserved\n\nComando:\nReserveInventory\nProcessPayment\nReleaseInventory\n\nLos eventos se expresan en pasado y reducen el conocimiento que el emisor necesita sobre sus consumidores." },
  { id: "domain-integration", label: "5) Tipos de evento", title: "Dominio no es integracion", subtitle: "Un evento interno puede conocer detalles del modelo; un evento que cruza servicios debe ser estable y versionable.", chip: "Contratos", content: "Evento de dominio:\nOrderConfirmedDomainEvent\n\nEvento de integracion:\nOrderConfirmedIntegrationEvent\n\nNunca publicamos directamente la entidad Order. Construimos un contrato explicito, serializable e independiente del dominio interno." },
  { id: "base-contract", label: "6) Contrato base", title: "IntegrationEvent", subtitle: "Todos los mensajes necesitan identidad, fecha, tipo y version.", chip: "BuildingBlocks", content: "IIntegrationEvent:\nGuid MessageId\nDateTimeOffset OccurredAt\nstring EventType\nint Version\n\nUna clase IntegrationEvent puede servir como base para contratos de Orders, Inventory y Payments." },
  { id: "order-event", label: "7) OrderConfirmed", title: "El primer evento de integracion", subtitle: "Orders publica solo los datos que Inventory y Payments necesitan para continuar.", chip: "Orders", content: "OrderConfirmedIntegrationEvent:\nMessageId\nOccurredAt\nOrderId\nCustomerId\nTotal\nCurrency\nItems\n\nOrderConfirmedItem:\nProductId\nProductName\nUnitPrice\nQuantity\n\nNo incluimos entidades, DbContext, direcciones innecesarias ni tokens sensibles." },
  { id: "metadata", label: "8) Metadata", title: "MessageId, CorrelationId y CausationId", subtitle: "La metadata permite rastrear duplicados, flujos y la causa de cada mensaje.", chip: "Trazabilidad", content: "MessageId: identidad unica del mensaje.\nCorrelationId: agrupa todo el flujo de una orden.\nCausationId: indica que mensaje provoco el actual.\n\nOrderConfirmed causa InventoryReserved.\nInventoryReserved causa PaymentRequested.\n\nEstos ids conectan mensajes, logs e incidentes." },
  { id: "versioning", label: "9) Versionado", title: "Un contrato de integracion es una API", subtitle: "Los consumidores pueden desplegarse en momentos diferentes y no deben romperse por cambios arbitrarios.", chip: "Compatibilidad", content: "Hoy: OrderConfirmed v1\nMañana: ShippingAddress, TaxAmount, PromotionId\n\nOpciones:\n- agregar campos opcionales\n- publicar v2\n- mantener ambas versiones temporalmente\n\nNunca modificamos un contrato publicado sin considerar a sus consumidores." },
  { id: "rabbit-concepts", label: "10) RabbitMQ", title: "Exchange, queue, binding y routing key", subtitle: "Cada pieza tiene una responsabilidad distinta dentro del enrutamiento.", chip: "RabbitMQ", content: "Exchange: recibe mensajes.\nQueue: conserva mensajes para un consumidor.\nBinding: conecta exchange con queue.\nRouting key: ayuda a decidir el destino.\n\nExchange: orderflow.events\nTipo: topic\nRouting key: orders.order-confirmed.v1" },
  { id: "queues", label: "11) Colas", title: "Cada consumidor necesita su propia cola", subtitle: "Dos consumidores que necesitan el mensaje no deben competir por una sola cola.", chip: "Topologia", content: "Exchange: orderflow.events\n\nQueue: inventory.order-confirmed\nQueue: analytics.order-confirmed\n\nAmbas reciben OrderConfirmed.\n\nSi Inventory y Analytics compartieran una cola, solo uno recibiria cada mensaje. Las colas representan consumidores independientes." },
  { id: "flow", label: "12) Flujo inicial", title: "La cadena de eventos", subtitle: "El proceso avanza mediante hechos publicados por cada servicio.", chip: "Flujo", content: "OrderConfirmed\n        |\n        v\nInventory consume\n        |\n        +--> InventoryReserved\n        |\n        +--> InventoryReservationFailed\n                         |\n                         v\n              Payments consume Reserved\n                         |\n                         +--> PaymentApproved\n                         +--> PaymentRejected" },
  { id: "inventory-event", label: "13) InventoryReserved", title: "Contrato de reserva exitosa", subtitle: "Payments necesita saber que la reserva existe antes de iniciar el cobro.", chip: "Inventory", content: "InventoryReservedIntegrationEvent:\nMessageId\nCorrelationId\nCausationId\nOccurredAt\nReservationId\nOrderId\nItems\n\nInventoryReservedItem:\nProductId\nQuantity\n\nEl consumidor no necesita conocer las entidades internas de Inventory." },
  { id: "failure-event", label: "14) Reserva fallida", title: "InventoryReservationFailed", subtitle: "Un fallo de negocio tambien puede viajar como evento para que Orders compense.", chip: "Compensacion", content: "InventoryReservationFailedIntegrationEvent:\nMessageId\nCorrelationId\nCausationId\nOccurredAt\nOrderId\nFailureCode\nFailureReason\n\nLa falta de stock no es un error de transporte: es una decision de negocio que otros servicios deben conocer." },
  { id: "payment-events", label: "15) Payments", title: "Eventos de pago", subtitle: "Payments publica resultados para que Orders e Inventory avancen o compensen.", chip: "Payments", content: "PaymentApprovedIntegrationEvent:\nPaymentId\nOrderId\nAmount\nCurrency\nProviderPaymentId\n\nPaymentRejectedIntegrationEvent:\nPaymentId\nOrderId\nRejectionCode\nRejectionReason\n\nCada evento mantiene MessageId, CorrelationId, CausationId, OccurredAt y Version." },
  { id: "contracts", label: "16) Proyectos de contratos", title: "Compartir contratos, no el dominio", subtitle: "Los servicios pueden referenciar DTOs de integracion estables sin compartir reglas ni persistencia.", chip: "Contracts", content: "Contracts\n|-- Contracts.Orders\n|-- Contracts.Inventory\n|-- Contracts.Payments\n\nCompartimos:\nDTOs de integracion estables\n\nNo compartimos:\nentidades\nrepositorios\nDbContext\nservicios de aplicacion\nreglas de dominio" },
  { id: "event-bus", label: "17) Abstraccion", title: "IEventBus", subtitle: "Application publica eventos mediante una interfaz; Infrastructure conoce RabbitMQ.", chip: "Abstraccion", content: "public interface IEventBus\n{\n    Task PublishAsync<TEvent>(\n        TEvent integrationEvent,\n        CancellationToken cancellationToken = default)\n        where TEvent : IIntegrationEvent;\n}\n\nEsta frontera permite probar casos de uso sin levantar RabbitMQ y cambiar la tecnologia de transporte." },
  { id: "options", label: "18) Configuracion", title: "RabbitMqOptions", subtitle: "Host, puerto, credenciales, virtual host y exchange se configuran por entorno.", chip: "Config", content: "RabbitMq:\nHostName: rabbitmq\nPort: 5672\nUserName: orderflow\nPassword: configurada por entorno\nVirtualHost: /\nExchangeName: orderflow.events\n\nLocal puede usar localhost. Docker usa rabbitmq como nombre de servicio. Los secretos no deben hardcodearse." },
  { id: "connection", label: "19) Conexion", title: "Gestionar la conexion RabbitMQ", subtitle: "La conexion debe reutilizarse, recuperarse automaticamente y liberarse correctamente.", chip: "Infrastructure", content: "RabbitMqConnection:\n- reutiliza una conexion abierta\n- crea ConnectionFactory desde Options\n- AutomaticRecoveryEnabled = true\n- NetworkRecoveryInterval = 5 segundos\n- expone GetConnectionAsync\n- implementa IAsyncDisposable\n\nLa aplicacion no debe crear una conexion nueva por cada mensaje." },
  { id: "envelope", label: "20) Envelope", title: "Serializar mensajes con contexto", subtitle: "Un envelope uniforme facilita versionado, trazas, routing y consumidores genericos.", chip: "Mensajes", content: "MessageEnvelope<T>:\nMessageId\nCorrelationId\nCausationId\nMessageType\nVersion\nOccurredAt\nData\n\nEl payload contiene solo el contrato de integracion. JSON es suficiente para comenzar, siempre que el contrato sea estable." },
  { id: "publisher", label: "21) Publicador", title: "RabbitMqEventBus", subtitle: "El publicador serializa el envelope, declara el exchange y publica con routing key.", chip: "Publisher", content: "PublishAsync:\n1. obtener conexion\n2. crear channel\n3. asegurar exchange topic\n4. serializar envelope JSON\n5. calcular routing key\n6. publicar bytes\n7. confirmar o registrar fallo\n\nLa publicacion no debe ocultar errores: debe dejar trazabilidad para reintento u Outbox." },
  { id: "consumer", label: "22) Consumidor", title: "Inventory como consumidor", subtitle: "El worker escucha su cola, deserializa el evento y llama el caso de uso de reserva.", chip: "Consumer", content: "Inventory consumer:\n1. leer delivery\n2. deserializar envelope\n3. validar tipo y version\n4. verificar idempotencia\n5. reservar todos los items\n6. publicar Reserved o Failed\n7. ack si se proceso\n8. nack/retry si fallo recuperable\n\nEl consumidor nunca debe depender de un request HTTP abierto." },
  { id: "ack", label: "23) ACK", title: "Confirmar solo despues de procesar", subtitle: "Un mensaje no debe marcarse como consumido antes de guardar el resultado de negocio.", chip: "Entrega", content: "Leer mensaje\n   |\n   v\nProcesar dominio\n   |\n   v\nGuardar cambios\n   |\n   v\nPublicar resultado\n   |\n   v\nACK\n\nSi el proceso falla antes del ACK, RabbitMQ puede entregar de nuevo. Por eso la idempotencia es obligatoria." },
  { id: "idempotent", label: "24) Idempotencia", title: "El consumidor debe tolerar duplicados", subtitle: "At-least-once delivery significa que el mismo mensaje puede llegar mas de una vez.", chip: "Idempotencia", content: "MessageId = 39516f83...\n\nAntes de procesar:\n1. buscar MessageId en ProcessedMessages\n2. si existe, ACK y salir\n3. si no existe, procesar\n4. registrar MessageId en la misma transaccion\n5. ACK\n\nUn redelivery no debe reservar ni cobrar dos veces." },
  { id: "outbox", label: "25) Outbox", title: "El problema de guardar y publicar", subtitle: "Si la base guarda y RabbitMQ falla, el estado cambia pero el evento no sale.", chip: "Outbox", content: "Guardar OrderConfirmed\n        |\n        +--> RabbitMQ falla\n\nSin Outbox, el mensaje se pierde.\n\nSolucion:\n1. guardar estado y OutboxMessage en la misma transaccion\n2. worker lee mensajes pendientes\n3. publica en RabbitMQ\n4. marca enviado\n\nLa Outbox sera la siguiente capa de confiabilidad." },
  { id: "retry-dlq", label: "26) Retries y DLQ", title: "Fallos recuperables y permanentes", subtitle: "No todos los mensajes deben reintentarse indefinidamente.", chip: "Operacion", content: "Fallo transitorio:\nretry con backoff\n\nFallo permanente:\nack y Dead Letter Queue\n\nPoison message:\nsiempre falla por contrato o datos invalidos\n\nLa DLQ permite investigar, corregir y reprocesar sin bloquear la cola principal." },
  { id: "compose", label: "27) Docker Compose", title: "Agregar RabbitMQ al entorno", subtitle: "El broker debe poder levantarse junto a los servicios para probar el flujo completo.", chip: "Docker", content: "rabbitmq:\n  image: rabbitmq:4-management\n  ports:\n    - 5672:5672\n    - 15672:15672\n  volumes:\n    - rabbitmq-data:/var/lib/rabbitmq\n\nOrders, Inventory y Payments usan rabbitmq como hostname dentro de la red Docker." },
  { id: "flow-final", label: "28) Flujo completo", title: "La compra basada en eventos", subtitle: "Cada servicio reacciona a hechos y publica el siguiente resultado sin conocer la implementacion interna del resto.", chip: "Integracion", content: "OrderConfirmed\n   |\n   v\nInventoryReserved\n   |\n   v\nPaymentApproved\n   |\n   +--> InventoryConsumptionConfirmed\n   |\n   +--> OrderCompleted\n\nSi falla Inventory: InventoryReservationFailed.\nSi falla Payment: PaymentRejected y liberacion de reserva." },
  { id: "testing", label: "29) Pruebas", title: "Casos que debemos verificar", subtitle: "La mensajeria debe probar disponibilidad, duplicados, orden y recuperacion del broker.", chip: "Testing", content: "Inventory apagado -> mensaje pendiente\nConsumidor reiniciado -> mensaje se procesa\nMismo MessageId dos veces -> una sola reserva\nPayment caido -> cola conserva evento\nPublicacion fallida -> Outbox pendiente\nMensaje invalido -> DLQ\nConsumidor lento -> backpressure\nContrato v1 -> consumidor antiguo sigue funcionando" },
  { id: "checklist", label: "30) Checklist", title: "Validacion de la integracion", subtitle: "RabbitMQ esta bien integrado cuando el flujo sobrevive a reinicios, duplicados y fallos de red.", chip: "Checklist", content: "Exchange topic creado\nColas independientes por consumidor\nRouting keys versionadas\nContratos separados del dominio\nMessageId unico\nCorrelationId propagado\nACK despues de procesar\nConsumidores idempotentes\nRetries limitados\nDLQ configurada\nRabbitMQ en Docker Compose\nOutbox planificada\nObservabilidad de mensajes\n\nLa mensajeria desacopla, pero exige disciplina operativa." },
  { id: "closing", label: "31) Cierre", title: "Como piensa un backend senior", subtitle: "Los eventos no son una forma de esconder llamadas HTTP: son contratos y decisiones de entrega.", chip: "Cierre", content: "Backend junior:\nRabbitMQ resuelve la comunicacion.\n\nBackend senior:\nCada evento necesita contrato, version, identidad, consumidor idempotente, estrategia de retry, DLQ, observabilidad y un plan de compensacion.\n\nLos eventos permiten que un servicio comunique lo que ocurrio sin controlar directamente como reaccionan los demas." },
];

export default function Daily141Client() {
  const [activeSection, setActiveSection] = useState("idea");

  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement | null;
      if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return;
      if (event.key.toLowerCase() === "p") window.location.href = "/daily/140";
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, []);

  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);

  return (
    <div className={styles.page}>
      <header className={styles.topbar}><div className={styles.topbarInner}>
        <div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>RabbitMQ y comunicacion mediante eventos</div></div></div>
        <nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav>
        <div className={styles.actions}><Link className={styles.btn} href="/daily/140"><span className={styles.kbd}>←</span> Dia 140</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div>
      </div></header>
      <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}>
        <div className={styles.dailyHero}><div className={styles.createdAt}>27/07/2026</div><div className={styles.badge}>Daily #141 • Event-Driven Architecture</div><h2 className={styles.title}>Integrar RabbitMQ y comunicar microservicios mediante eventos</h2><p className={styles.lead}>Orders, Inventory y Payments colaboraran mediante contratos de integracion, colas independientes e idempotencia.</p></div>
        <nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>
        {sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}
        <div className={styles.footerNav}><Link className={styles.btn} href="/daily/140"><span className={styles.kbd}>←</span> Dia 140</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div>
      </div></article></div></main>
    </div>
  );
}
