"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "project", label: "1) Proyecto", title: "Que es TradeOps 360", subtitle: "Un modulo empresarial para gestionar clientes, equipos, tickets y ordenes de trabajo dentro de Odoo.", chip: "TradeOps", content: "Clientes\n        |\n        v\nEquipos instalados\n        |\n        v\nTickets de servicio\n        |\n        v\nOrdenes de trabajo\n        |\n        +-- tecnico\n        +-- materiales\n        +-- horas\n        +-- coste\n        |\n        v\nCierre e informe" },
  { id: "principle", label: "2) Principio", title: "Extender Odoo, no reemplazarlo", subtitle: "La arquitectura debe aprovechar modelos, usuarios, companias, seguridad y servicios estandar del framework.", chip: "Arquitectura", content: "Odoo Core\n  +-- res.partner\n  +-- res.users\n  +-- res.company\n  +-- mail.thread\n  +-- security\n  +-- ORM\n        |\n        v\nTradeOps 360\n  +-- equipment\n  +-- ticket\n  +-- work.order\n\nUsar herencia y composicion. No duplicar capacidades que Odoo ya resuelve." },
  { id: "mental", label: "3) Modelo mental", title: "La arquitectura de Odoo", subtitle: "Un modulo conecta Python, PostgreSQL, registry, Environment, XML, permisos y vistas.", chip: "Odoo 17", content: "Usuario\n  |\nVista XML\n  |\nAction / Controller\n  |\nModelo + ORM\n  |\nEnvironment\n  |\nRegistry\n  |\nPostgreSQL\n\nCada capa tiene responsabilidades y contratos diferentes." },
  { id: "registry", label: "4) Registry", title: "El registro de modelos", subtitle: "El registry mantiene los modelos cargados y permite que Odoo componga extensiones de distintos modulos.", chip: "Registry", content: "Modulo base: res.partner\n        +\nTradeOps: extension res.partner\n        |\n        v\nModelo final registrado\n\nEl orden de carga y las dependencias del manifest importan. Un modulo debe declarar lo que necesita para que Odoo pueda construir el registry correctamente." },
  { id: "env", label: "5) Environment", title: "Trabajar con env", subtitle: "`env` conecta modelo, usuario, compania, contexto y acceso a otros modelos.", chip: "ORM", content: "self.env['res.partner']\nself.env.user\nself.env.company\nself.env.context\n\nEl mismo modelo puede comportarse distinto segun usuario, compania y contexto. No tratar `env` como una variable global sin reglas de seguridad." },
  { id: "reuse", label: "6) Reutilizar", title: "Que reutilizara TradeOps", subtitle: "El proyecto se integra con las capacidades estandar de Odoo en vez de crear sustitutos innecesarios.", chip: "Integracion", content: "res.partner -> clientes\nres.users -> tecnicos y usuarios\nres.company -> multi-company\nmail.thread -> chatter\nmail.activity -> tareas\nir.attachment -> documentos\nres.currency -> costes\n\nEl valor propio esta en el dominio Field Service, no en reconstruir el ERP." },
  { id: "module-size", label: "7) Limites", title: "Evitar un modulo gigantesco", subtitle: "Separar responsabilidades permite evolucionar el proyecto y mantener las dependencias comprensibles.", chip: "Modularidad", content: "fieldops_equipment\nfieldops_service\nfieldops_reports\nfieldops_integration\n\nAl inicio puede existir un modulo `tradeops`, pero sus modelos deben tener limites claros. Extraer cuando el dominio, equipo o ciclo de despliegue lo justifique." },
  { id: "domains", label: "8) Dominios", title: "Separar los dominios propios", subtitle: "El proyecto debe distinguir clientes, equipos, tickets y ordenes aunque compartan relaciones.", chip: "Dominio", content: "res.partner\n  |\n  +-- tradeops.equipment\n          |\n          +-- tradeops.ticket\n                  |\n                  +-- tradeops.work.order\n\nCada modelo debe proteger sus invariantes y exponer metodos de negocio claros. Las vistas no deben contener reglas que pertenecen al modelo." },
  { id: "sql", label: "9) Persistencia", title: "Por que evitar SQL directo", subtitle: "El ORM mantiene relaciones, permisos, cache, multi-company y extensibilidad de los modelos.", chip: "PostgreSQL", content: "Preferir:\nself.env['tradeops.equipment'].search(domain)\n\nEn lugar de:\nSELECT * FROM tradeops_equipment\n\nSQL directo puede saltarse ACL, Record Rules, company isolation, computed fields y contratos internos. Usarlo solo con una necesidad demostrada y controlada." },
  { id: "today", label: "10) Mejora de hoy", title: "Definir la arquitectura antes de programar", subtitle: "La primera entrega de TradeOps es un mapa de capas y fronteras, no una pantalla aislada.", chip: "Milestone", content: "Odoo estandar\n        | reutilizar\nTradeOps 360\n        | dominio propio\n        +-- equipment\n        +-- ticket\n        +-- work.order\n        |\n        v\nReportes + integraciones\n\nLa arquitectura servira para decidir donde colocar cada futura funcionalidad." },
  { id: "qa", label: "11) QA", title: "Preguntas de arquitectura", subtitle: "Una arquitectura util permite responder preguntas de negocio, seguridad y operacion antes de escribir codigo.", chip: "QA", content: "Que modelo es dueño de cada dato?\nQue reutilizamos de Odoo?\nQue permiso necesita cada actor?\nQue ocurre entre companias?\nQue estado puede cambiar y quien?\nQue parte necesita chatter?\nQue integracion sera externa?\nComo se prueba el flujo completo?" },
  { id: "checklist", label: "12) Checklist", title: "TradeOps preparado para crecer", subtitle: "El diseño inicial debe ser suficientemente simple para comenzar y suficientemente claro para evolucionar.", chip: "Checklist", content: "Problema de negocio definido\nActores identificados\nModelos estandar localizados\nDominios propios separados\nDependencias declaradas\nUso de ORM definido\nMulti-company contemplado\nSeguridad considerada\nFlujo principal documentado\nPrimer modelo priorizado\nTests y upgrade previstos" },
  { id: "closing", label: "13) Cierre", title: "La arquitectura vive dentro del framework", subtitle: "Un desarrollador backend de Odoo entiende el sistema que extiende y el dominio que aporta.", chip: "Cierre", content: "Backend junior:\nCreo tablas y pantallas nuevas.\n\nBackend senior:\nReutiliza Odoo, entiende registry y env, respeta ORM y seguridad, separa dominios y construye el modulo para evolucionar sin romper el core.\n\nTradeOps 360 empieza con una arquitectura antes que con codigo." },
];

export default function Daily157Client() {
  const [activeSection, setActiveSection] = useState("project");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/156"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Arquitectura de Odoo 17</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/156"><span className={styles.kbd}>←</span> Dia 156</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>20/08/2026</div><div className={styles.badge}>Daily #157 • Odoo Architecture</div><h2 className={styles.title}>Arquitectura de Odoo 17 y donde vive TradeOps 360</h2><p className={styles.lead}>Definir las capas, dependencias y fronteras del modulo antes de empezar a construir modelos y vistas.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/156"><span className={styles.kbd}>←</span> Dia 156</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
