"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "problem", label: "1) Problema", title: "Relacionar datos sin perder el dominio", subtitle: "Una importacion real necesita clientes, tipos, lineas y configuracion reutilizable.", chip: "Contexto", content: "Importacion\n  |\n  +-- cliente\n  +-- tipo de importacion\n  +-- lineas\n  |      +-- equipo\n  |      +-- serie\n  |      +-- fecha\n  |\n  v\ntrade_core\n\nLas relaciones deben expresar reglas del negocio, no solo conectar tablas." },
  { id: "many2one", label: "2) Many2one", title: "Un registro pertenece a otro", subtitle: "Many2one representa la referencia habitual: muchos equipos pueden pertenecer a un cliente.", chip: "Relation", content: "partner_id = fields.Many2one(\n    'res.partner',\n    required=True,\n    ondelete='restrict',\n)\n\nUso:\nequipment.partner_id\n\nEl campo guarda una referencia y permite navegar al registro relacionado respetando permisos y contexto." },
  { id: "one2many", label: "3) One2many", title: "El lado inverso de una relacion", subtitle: "One2many muestra el conjunto de registros que apuntan hacia un registro principal.", chip: "Relation", content: "line_ids = fields.One2many(\n    'tradeops.import.line',\n    'import_id',\n)\n\nEl modelo hijo necesita el Many2one inverso:\nimport_id = fields.Many2one('tradeops.import')\n\nSin el campo inverso, Odoo no puede mantener la relacion correctamente." },
  { id: "config", label: "4) Configuracion", title: "Puertos y tipos como datos configurables", subtitle: "Los valores que cambian por negocio no deben quedar hardcodeados en Python.", chip: "Data", content: "tradeops.import.type\n\nEjemplos:\n- Equipment CSV\n- Customer Import\n- Maintenance Update\n\nUna configuracion puede tener nombre, codigo, activo, modelo destino y opciones. El codigo consume esos datos mediante el ORM." },
  { id: "import", label: "5) Importacion", title: "Relacionar la importacion con Odoo", subtitle: "Una importacion puede pertenecer a un cliente y a un tipo configurable mientras conserva sus lineas.", chip: "TradeOps", content: "class Import(models.Model):\n    _name = 'tradeops.import'\n\n    name = fields.Char(required=True)\n    partner_id = fields.Many2one('res.partner')\n    type_id = fields.Many2one('tradeops.import.type')\n    line_ids = fields.One2many(\n        'tradeops.import.line', 'import_id')\n\nEl modelo orquesta; las reglas profundas permanecen en el dominio apropiado." },
  { id: "partner", label: "6) res.partner", title: "Reutilizar el cliente estandar", subtitle: "No crear un modelo Customer paralelo si Odoo ya tiene contactos, companias y direcciones.", chip: "Reuse", content: "res.partner\n  +-- nombre\n  +-- email\n  +-- compania\n  +-- direcciones\n  +-- permisos\n        |\n        v\ntradeops.import.partner_id\n\nExtender res.partner solo cuando TradeOps aporte comportamiento o datos propios." },
  { id: "lines", label: "7) Lineas", title: "Crear las lineas de importacion", subtitle: "Las lineas representan cada fila recibida y permiten validar y reportar errores individualmente.", chip: "Lines", content: "tradeops.import.line\n\nCampos:\n- import_id\n- equipment_name\n- serial_number\n- installation_date\n- partner_id\n- state\n- error_message\n- status\n\nSeparar cabecera y lineas hace posible reintentar, auditar y mostrar que filas fallaron." },
  { id: "inverse", label: "8) Inverso", title: "Pensar desde ambos lados", subtitle: "Una relacion no es solo como se crea: tambien importa como se consulta desde el registro padre.", chip: "Recordset", content: "import.line.import_id\n        |\n        v\nimport.line records\n        |\n        v\nimport.line_ids en la importacion\n\nDesde la importacion podemos contar lineas, filtrar errores y recorrerlas. Desde la linea podemos acceder a la cabecera y su contexto." },
  { id: "cascade", label: "9) ondelete", title: "Decidir que ocurre al borrar", subtitle: "La politica de borrado forma parte de la integridad del dominio.", chip: "Integrity", content: "cascade:\nborra hijos cuando se borra el padre.\n\nrestrict:\nbloquea el borrado si existen relaciones.\n\nset null:\nquita la referencia y conserva el hijo.\n\nElegir segun negocio. Para historicos o auditoria, borrar en cascada puede ser una perdida de informacion." },
  { id: "domain-field", label: "10) Domain en Field", title: "Limitar selecciones en la interfaz", subtitle: "Un domain puede mostrar solo registros validos para el contexto del campo.", chip: "Domain", content: "partner_id = fields.Many2one(\n    'res.partner',\n    domain=[('is_company', '=', True)],\n)\n\nEl usuario no ve contactos que no corresponden al caso de negocio. El domain mejora UX, pero no sustituye una validacion server-side." },
  { id: "domain-search", label: "11) Domain en search", title: "Buscar con condiciones expresivas", subtitle: "El mismo concepto se usa en consultas del ORM para localizar registros validos.", chip: "Search", content: "imports = env['tradeops.import'].search([\n    ('partner_id', '=', partner.id),\n    ('state', 'in', ['draft', 'error']),\n])\n\nUn domain puede combinar igualdad, pertenencia, fechas y relaciones. Revisar indice y volumen cuando la consulta sea operativa." },
  { id: "many2many", label: "12) Many2many", title: "Relacionar varios con varios", subtitle: "Many2many sirve para conjuntos independientes como tecnicos, etiquetas o equipos relacionados.", chip: "Relation", content: "technician_ids = fields.Many2many(\n    'res.users',\n    string='Technicians',\n)\n\nUna orden puede tener varios tecnicos y un tecnico muchas ordenes. Usar Command API para crear, agregar, reemplazar o quitar relaciones de forma explicita." },
  { id: "shell", label: "13) Flujo", title: "Crear una importacion completa", subtitle: "El shell permite comprobar relaciones y recordsets antes de construir toda la interfaz.", chip: "Practice", content: "import_record = env['tradeops.import'].create({\n    'name': 'August Equipment',\n    'partner_id': partner.id,\n    'type_id': import_type.id,\n})\n\nimport_record.write({\n    'line_ids': [Command.create({\n        'equipment_name': 'Pump A',\n        'serial_number': 'SN-001',\n    })],\n})\n\nComprobar padre, hijos, dominio y permisos." },
  { id: "state", label: "14) Resultado", title: "TradeOps con relaciones reales", subtitle: "La importacion ya puede representar cabecera, configuracion, cliente y lineas sin datos aislados.", chip: "Milestone", content: "Importacion\n  +-- Cliente (Many2one)\n  +-- Tipo (Many2one)\n  +-- Lineas (One2many)\n        +-- Equipo\n        +-- Estado\n        +-- Error\n\nEquipos y usuarios pueden participar mediante relaciones adicionales. La estructura prepara validacion, reintentos y auditoria." },
  { id: "qa", label: "15) QA", title: "Validar relaciones y domains", subtitle: "Una relacion correcta debe probarse desde el modelo, la interfaz y los casos de borrado.", chip: "QA", content: "Many2one apunta al modelo correcto\nOne2many tiene inverse_name correcto\nMany2many no duplica relaciones\nDomain oculta opciones invalidas\nValidacion server-side existe\nondelete coincide con negocio\nLineas pertenecen a una importacion\nDatos configurables se pueden cambiar\nSearch devuelve recordsets esperados\nTests cubren padre e hijos" },
  { id: "closing", label: "16) Cierre", title: "Las relaciones expresan el negocio", subtitle: "Una buena arquitectura Odoo hace visibles las reglas a traves del modelo y no las esconde en scripts o vistas.", chip: "Cierre", content: "Backend junior:\nConecto tablas y sigo.\n\nBackend senior:\nDecide cardinalidad, inversa, borrado, dominio, permisos, datos configurables y comportamiento de recordsets.\n\nTradeOps ya puede recibir una importacion estructurada y convertirla en datos de negocio consistentes." },
];

export default function Daily161Client() {
  const [activeSection, setActiveSection] = useState("problem");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/160"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Relaciones y Domains en Odoo</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/160"><span className={styles.kbd}>←</span> Dia 160</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>25/08/2026</div><div className={styles.badge}>Daily #161 • Odoo Relations</div><h2 className={styles.title}>Relaciones, Domains y datos configurables en TradeOps 360</h2><p className={styles.lead}>Conectar importaciones, clientes, tipos y lineas mediante Many2one, One2many, Many2many y domains del ORM.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/160"><span className={styles.kbd}>←</span> Dia 160</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
