"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "problem", label: "1) Problema", title: "Un sistema empresarial debe comunicar", subtitle: "Guardar datos no alcanza: hay que saber qué ocurrió, quién actuó, cuándo y qué debe hacerse después.", chip: "Contexto", content: "Importación\n  -> Preventa\n  -> sale.order\n  -> Distribución\n  -> Entrega\n  -> Conciliación\n\nEl sistema también necesita:\ncomunicar + registrar + observar + reportar." },
  { id: "reuse", label: "2) Reutilizar", title: "Odoo ya tiene infraestructura para esto", subtitle: "La misma regla de extender antes que reconstruir aplica a notificaciones y trazabilidad.", chip: "Arquitectura", content: "Notificaciones -> mail.thread\nChatter        -> mensajes del registro\nActividades    -> mail.activity\nAuditoría      -> tracking y mensajes\nReportes       -> vistas y acciones\n\nTradeOps configura y extiende capacidades estándar." },
  { id: "mail-thread", label: "3) mail.thread", title: "Habilitar el historial del registro", subtitle: "mail.thread permite que un modelo tenga mensajes, seguidores y cambios visibles en Chatter.", chip: "Odoo", content: "class TradeImport(models.Model):\n    _name = 'trade.import'\n    _inherit = ['mail.thread', 'mail.activity.mixin']\n\n    state = fields.Selection(\n        [...], tracking=True)\n\nEl historial pertenece al registro, no a una nota externa." },
  { id: "chatter", label: "4) Chatter", title: "El contexto vive junto al negocio", subtitle: "El usuario puede reconstruir la conversación y los cambios sin abandonar la importación, preventa o distribución.", chip: "Chatter", content: "Registro\n  +-- mensajes\n  +-- seguidores\n  +-- cambios de estado\n  +-- actividades\n  +-- notas operativas\n\nChatter mejora soporte, coordinación y trazabilidad funcional." },
  { id: "tracking", label: "5) Tracking", title: "Auditar cambios importantes", subtitle: "tracking=True registra cambios de campos relevantes sin convertir cada atributo en ruido.", chip: "Auditoria", content: "state = fields.Selection(\n    [...],\n    tracking=True,\n)\n\nRegistrar:\n- estado\n- responsable\n- almacén\n- fecha operativa\n- datos que cambian decisiones\n\nElegir campos con criterio de negocio." },
  { id: "audit", label: "6) Auditoria", title: "Auditoría técnica y empresarial", subtitle: "Los logs ayudan a diagnosticar; la auditoría empresarial explica decisiones sobre registros concretos.", chip: "Control", content: "Log técnico:\n  error de conexión, stack trace, latencia\n\nAuditoría empresarial:\n  usuario cambió estado\n  preventa fue convertida\n  entrega quedó parcial\n  incidencia fue resuelta\n\nNo confundir observabilidad de infraestructura con trazabilidad del negocio." },
  { id: "message-post", label: "7) message_post", title: "Publicar eventos legibles para el equipo", subtitle: "Las acciones de negocio pueden dejar un mensaje contextual en el registro.", chip: "Mensajes", content: "self.message_post(\n    body=(\n        'Importación enviada a revisión por %s.'\n        % self.env.user.name\n    )\n)\n\nEl mensaje debe explicar la acción sin exponer secretos ni datos innecesarios." },
  { id: "activity", label: "8) Activities", title: "Una actividad pide una acción futura", subtitle: "Una notificación informa; una activity asigna trabajo, responsable y fecha límite.", chip: "Operación", content: "Activity:\n- responsable\n- tipo de tarea\n- fecha límite\n- resumen\n- registro relacionado\n\nEjemplo:\nRevisar documentación de importación\nResponsable: Operaciones\nVence: fecha de recepción" },
  { id: "notification", label: "9) Diferencia", title: "Notificación no es Activity", subtitle: "La comunicación inmediata y el trabajo pendiente son efectos distintos y deben modelarse como tales.", chip: "Diseño", content: "Notificación:\n  'La importación cambió a Receiving.'\n\nActivity:\n  'Validar documentos antes del viernes.'\n\nUna informa el presente; la otra organiza una responsabilidad futura." },
  { id: "integration", label: "10) Integraciones", title: "Integrar respetando el dominio", subtitle: "Una integración externa debe traducir contratos y errores sin introducir reglas fuera del límite del modelo.", chip: "Boundary", content: "TradeOps\n  -> valida dominio\n  -> prepara payload\n  -> llama servicio externo\n  -> registra resultado\n  -> actualiza estado\n\nNo ocultar errores externos ni marcar éxito antes de confirmarlo." },
  { id: "failures", label: "11) Fallos externos", title: "Un servicio externo puede fallar", subtitle: "Timeout, error funcional o respuesta inválida deben dejar una situación trazable y sin cambios parciales.", chip: "Resiliencia", content: "Casos:\n- timeout\n- servicio no disponible\n- HTTP 4xx\n- HTTP 5xx\n- respuesta incompleta\n- credencial inválida\n\nRegistrar el intento, clasificar el fallo y permitir reintento seguro cuando corresponda." },
  { id: "reports", label: "12) Reportes", title: "Convertir datos en información útil", subtitle: "Un reporte debe responder una pregunta operativa, no repetir todos los campos del modelo.", chip: "Reportes", content: "Preguntas útiles:\n- importaciones en tránsito\n- entregas parciales pendientes\n- preventas sin conversión\n- pagos pendientes\n- incidencias abiertas\n- tiempo medio por estado\n\nDiseñar el reporte desde la decisión que debe apoyar." },
  { id: "kpi", label: "13) KPI", title: "No guardar todo lo que se puede calcular", subtitle: "Los indicadores derivados deben tener dependencias claras y solo almacenarse cuando aporten búsqueda o rendimiento.", chip: "KPI", content: "KPI posibles:\n- entregas parciales\n- porcentaje pagado\n- días en estado\n- incidencias abiertas\n- costo real importado\n\nDefinir fuente, fórmula, frecuencia y dueño antes de persistir un indicador." },
  { id: "dashboard", label: "14) Dashboard", title: "Una vista de operación para TradeOps", subtitle: "El dashboard reúne señales que permiten actuar antes de que el proceso se detenga.", chip: "Operación", content: "TradeOps Dashboard\n  +-- Importaciones en Receiving\n  +-- Entregas parciales\n  +-- Incidencias sin resolver\n  +-- Preventas por convertir\n  +-- Pagos pendientes\n  +-- Integraciones fallidas\n\nCada tarjeta debe llevar a los registros accionables." },
  { id: "qa", label: "15) QA", title: "Probar comunicación, fallos y reportes", subtitle: "La cobertura debe verificar efectos secundarios y que los errores no oculten ni corrompan el estado.", chip: "QA", content: "Casos mínimos:\n- cambio válido deja tracking\n- transición inválida no deja falso éxito\n- activity tiene responsable y fecha\n- integración exitosa registra resultado\n- timeout no cambia estado incorrectamente\n- permisos limitan auditoría\n- reporte muestra datos correctos\n- mensaje no expone secretos" },
  { id: "complete", label: "16) Flujo", title: "El patrón completo de hoy", subtitle: "Una acción de negocio debe poder ejecutarse, comunicarse, auditarse y medirse.", chip: "Mapa", content: "Acción de negocio\n  -> validar dominio\n  -> persistir cambio\n  -> tracking / auditoría\n  -> notificar o crear activity\n  -> integrar si aplica\n  -> exponer en reporte\n\nEl resultado es operable y explicable, no solo correcto en la base de datos." },
  { id: "closing", label: "17) Cierre", title: "Un sistema empresarial debe explicar lo que hace", subtitle: "TradeOps ya no solo ejecuta procesos: comunica decisiones, conserva historia y transforma datos en acciones.", chip: "Cierre", content: "Regla mental:\n\nNo reinventar la comunicación.\nNo confundir logs con auditoría.\nNo confundir notificación con trabajo pendiente.\nNo ocultar fallos de integraciones.\nNo crear reportes sin una decisión detrás.\n\nUn sistema confiable deja evidencia y ayuda a operar." },
];

export default function Daily174Client() {
  const [activeSection, setActiveSection] = useState("problem");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/173"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Integraciones y auditoría en Odoo 17</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/173"><span className={styles.kbd}>←</span> Dia 173</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>11/09/2026</div><div className={styles.badge}>Daily #174 • Odoo Operations</div><h2 className={styles.title}>Integraciones, notificaciones, auditoría y reportes en Odoo 17</h2><p className={styles.lead}>Comunicar lo ocurrido, conservar trazabilidad y convertir datos de TradeOps en información útil para operar.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/173"><span className={styles.kbd}>←</span> Dia 173</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
