"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "idea", label: "1) Idea clave", title: "Practicar cloud sin depender de una cuenta real", subtitle: "AWS real puede generar costes, requiere credenciales y exige limpiar correctamente los recursos.", chip: "Cloud", content: "AWS\nECS\nFargate\nRDS\nS3\nSQS\nIAM\nCloudWatch\n\nEn desarrollo y aprendizaje podemos ejecutar servicios compatibles localmente para recibir feedback rapido sin crear infraestructura real en cada prueba." },
  { id: "floci", label: "2) Floci", title: "Un emulador local de AWS", subtitle: "Floci expone APIs compatibles en localhost para trabajar con AWS CLI y SDKs.", chip: "Floci", content: "Nuestra aplicacion\n        |\n        v\nAWS SDK\n        |\n        v\nFloci\nlocalhost:4566\n\nLa aplicacion conserva el contrato del servicio; cambia el endpoint y las credenciales de desarrollo." },
  { id: "services", label: "3) Servicios", title: "Que podemos practicar", subtitle: "El emulador permite experimentar con varios servicios del ecosistema cloud.", chip: "Servicios", content: "S3\nSQS\nSNS\nLambda\nDynamoDB\nRDS\nSecrets Manager\nEventBridge\nCloudWatch\nECS\nEC2\n\nNo implica que todos los servicios tengan exactamente el mismo comportamiento que AWS real." },
  { id: "docker", label: "4) Docker Compose", title: "Levantar Floci localmente", subtitle: "El entorno local puede ser reproducible y compartido por el equipo.", chip: "Docker", content: "services:\n  floci:\n    image: floci/floci:latest\n    ports:\n      - \"4566:4566\"\n\nDespues:\n\ndocker compose up -d\n\nEndpoint local:\nhttp://localhost:4566" },
  { id: "cli", label: "5) AWS CLI", title: "Apuntar el CLI al emulador", subtitle: "Las variables de entorno evitan que los comandos de aprendizaje creen recursos reales.", chip: "AWS CLI", content: "export AWS_ENDPOINT_URL=http://localhost:4566\nexport AWS_DEFAULT_REGION=us-east-1\nexport AWS_ACCESS_KEY_ID=test\nexport AWS_SECRET_ACCESS_KEY=test\n\nLa configuracion debe estar aislada del entorno real y ser facil de activar en local o CI." },
  { id: "s3", label: "6) S3", title: "Crear un bucket local", subtitle: "El mismo flujo de objetos puede probarse sin usar un bucket de produccion.", chip: "S3", content: "aws s3 mb s3://orderflow-files\naws s3 ls\naws s3 cp ./archivo.txt s3://orderflow-files\n\nPara produccion siguen siendo necesarios IAM, cifrado, politicas, versionado y lifecycle." },
  { id: "sqs", label: "7) SQS", title: "Probar productores y consumidores", subtitle: "Una cola local permite verificar integraciones de mensajeria desde la API.", chip: "SQS", content: "aws sqs create-queue --queue-name orderflow-orders\n\nProducer\n   |\n   v\nSQS local\n   |\n   v\nConsumer\n\nLa API .NET puede usar AWSSDK.SQS y cambiar solo ServiceURL al ejecutar localmente." },
  { id: "dotnet", label: "8) .NET", title: "Configurar el SDK", subtitle: "El codigo de negocio no debe saber si habla con Floci o con AWS real.", chip: ".NET", content: "var config = new AmazonSQSConfig\n{\n    ServiceURL = \"http://localhost:4566\"\n};\n\nvar client = new AmazonSQSClient(\n    \"test\", \"test\", config);\n\nEn produccion cambia la configuracion, no la logica de publicar y consumir mensajes." },
  { id: "testing", label: "9) Testing", title: "Usar infraestructura local en tests", subtitle: "Los tests de integracion pueden ejecutar API, emulador y consumidores en contenedores.", chip: "Integracion", content: "Test\n  |\n  v\nAPI\n  | publica\n  v\nFloci / SQS local\n  |\n  v\nConsumer\n\nEsto reduce dependencias externas, costes y variabilidad en CI, pero no elimina la necesidad de validar despues contra AWS real." },
  { id: "iac", label: "10) Infraestructura", title: "Practicar Infrastructure as Code", subtitle: "Terraform, OpenTofu, CDK y AWS CLI pueden apuntar al entorno local.", chip: "IaC", content: "IaC local\n  -> crear bucket\n  -> crear cola\n  -> configurar permisos\n  -> ejecutar tests\n  -> destruir entorno\n\nEl equipo practica declaracion, automatizacion y repetibilidad antes de promocionar cambios a staging." },
  { id: "limits", label: "11) Limites", title: "Floci no sustituye AWS", subtitle: "Un emulador acelera el desarrollo, pero no reproduce toda la nube real.", chip: "Realidad", content: "Pueden existir diferencias en:\n- rendimiento\n- networking\n- IAM real\n- limites\n- disponibilidad\n- comportamiento bajo carga\n\nRegla:\nEmulador para desarrollo y testing.\nAWS real para validar caracteristicas propias de cloud." },
  { id: "workflow", label: "12) Flujo", title: "Del desarrollo local a produccion", subtitle: "La infraestructura local debe mejorar el feedback sin romper la ruta hacia un entorno real.", chip: "Workflow", content: "Desarrollo\n   |\nFloci local\n   |\nIntegration Tests\n   |\nCI\n   |\nAWS Staging\n   |\nAWS Production\n\nCada etapa debe mantener contratos y configuracion explicita." },
  { id: "orderflow", label: "13) OrderFlow", title: "Aplicar el entorno local al proyecto", subtitle: "El proyecto puede practicar almacenamiento, colas, secretos y eventos sin salir del equipo.", chip: "OrderFlow", content: "S3 -> documentos\nSQS -> procesamiento de ordenes\nSNS -> distribucion de eventos\nSecrets Manager -> secretos de desarrollo\nDynamoDB -> experimentar con NoSQL\n\nTodo puede arrancar desde Docker Compose y formar parte del entorno de integracion." },
  { id: "checklist", label: "14) Ejercicio", title: "Construir el laboratorio local", subtitle: "El objetivo es poder repetir el flujo completo desde cero.", chip: "Practica", content: "1. Levantar Floci con Docker Compose.\n2. Configurar AWS CLI para localhost:4566.\n3. Crear un bucket S3.\n4. Subir un archivo.\n5. Crear una cola SQS.\n6. Enviar y recibir un mensaje.\n7. Conectar una aplicacion .NET.\n8. Identificar los cambios para AWS real." },
  { id: "closing", label: "15) Cierre", title: "Un buen entorno local se parece a produccion", subtitle: "Desarrollar localmente reduce coste y riesgo, pero la validacion final sigue necesitando infraestructura real.", chip: "Cierre", content: "Backend junior:\nPara aprender AWS necesito crear todo directamente en AWS.\n\nBackend senior:\nDesarrollo y pruebo localmente siempre que sea posible, y uso infraestructura real cuando necesito validar comportamiento real de cloud.\n\nLa configuracion cambia; el contrato de negocio permanece." },
];

export default function Daily150Client() {
  const [activeSection, setActiveSection] = useState("idea");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/148"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>AWS local con Floci</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/148"><span className={styles.kbd}>←</span> Dia 148</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>11/08/2026</div><div className={styles.badge}>Daily #150 • AWS Local</div><h2 className={styles.title}>AWS local con Floci: practicar cloud sin gastar dinero</h2><p className={styles.lead}>Un entorno local compatible con AWS permite aprender, desarrollar y probar integraciones sin depender de una cuenta real en cada ejecucion.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/148"><span className={styles.kbd}>←</span> Dia 148</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
