"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "idea", label: "1) Idea clave", title: "Orders es el nucleo de la compra", subtitle: "No sera una API CRUD: gestionara decisiones, reglas y estados del proceso de compra.", chip: "Idea", content: "En la clase anterior extraimos Catalog.\n\nAhora extraeremos:\n\nOrders Service\n\nOrders sera responsable de gestionar el ciclo de vida completo de una orden.\n\nNo administra productos ni pagos. Administra decisiones y estados relacionados con la compra.\n\nLa primera extraccion fue Catalog. La siguiente construye el nucleo del proceso." },
  { id: "responsibility", label: "2) Responsabilidad", title: "Que responsabilidad tendra Orders", subtitle: "Orders protege las reglas de la orden desde su creacion hasta su confirmacion o cancelacion.", chip: "Limites", content: "Orders controla:\n\ncrear ordenes\nagregar y eliminar productos\ncalcular el total\nconfirmar ordenes\ncancelar ordenes\ntransiciones de estado\nprecio historico\neventos de la orden\n\nResponde si existe, si puede modificarse, cual es su total y cual es su estado.\n\nNo responde por stock, pagos, envios ni notificaciones." },
  { id: "snapshot", label: "3) Snapshot", title: "Orders no copia todo Catalog", subtitle: "Solo solicita la informacion minima y conserva una fotografia historica del momento de compra.", chip: "Historia", content: "Orders necesita:\n\nProductId\nName\nPrice\nActive\n\nNo necesita categorias, marcas, imagenes, especificaciones ni la descripcion completa.\n\nCuando el cliente agrega un producto, Orders guarda:\n\nProductId\nProductName\nUnitPrice\nQuantity\n\nLa orden no debe consultar Catalog cada vez que se muestra." },
  { id: "price", label: "4) Precio historico", title: "Por que existe el snapshot", subtitle: "La orden debe conservar el precio que el cliente vio, aunque Catalog cambie despues.", chip: "Consistencia", content: "Hoy Catalog:\nKeyboard = 89.99\n\nEl cliente agrega 2 unidades.\n\nMañana Catalog:\nKeyboard = 99.99\n\nLa orden sigue mostrando:\n2 x 89.99 = 179.98\n\nOrders guarda la informacion necesaria para reconstruir historicamente la compra." },
  { id: "structure", label: "5) Estructura", title: "La estructura del servicio", subtitle: "Orders separa API, casos de uso, dominio e infraestructura.", chip: "Arquitectura", content: "Orders\n|-- Orders.API\n|   |-- Controllers\n|   |-- Middleware\n|   |-- Program.cs\n|-- Orders.Application\n|   |-- Orders/Commands\n|   |-- Orders/Queries\n|   |-- Orders/DTOs\n|   |-- Orders/Services\n|-- Orders.Domain\n|   |-- Orders\n|   |-- Common\n|-- Orders.Infrastructure\n    |-- Persistence\n    |-- Repositories\n    |-- Catalog\n    |-- Migrations" },
  { id: "states", label: "6) Estados", title: "La maquina de estados inicial", subtitle: "No todos los estados se usan hoy, pero el modelo queda preparado para el proceso distribuido.", chip: "Estados", content: "Draft = 1\nPendingProcessing = 2\nPaymentProcessing = 3\nCompleted = 4\nPaymentFailed = 5\nInventoryReservationFailed = 6\nCancelled = 7\n\nHoy construiremos Draft, PendingProcessing y Cancelled. Los demas apareceran cuando agreguemos Inventory y Payments." },
  { id: "item", label: "7) OrderItem", title: "El item protege sus propias reglas", subtitle: "Cantidad, precio, producto y nombre deben ser validos antes de entrar al agregado.", chip: "Domain", content: "OrderItem valida:\n\nId no vacio\nProductId no vacio\nProductName requerido\nUnitPrice mayor que cero\nQuantity mayor que cero\n\npublic decimal Total => UnitPrice * Quantity;\n\nIncreaseQuantity y ChangeQuantity tambien rechazan cantidades invalidas. Los setters permanecen privados." },
  { id: "aggregate", label: "8) Aggregate Root", title: "Order controla sus items", subtitle: "Toda modificacion del agregado pasa por Order para proteger su consistencia.", chip: "DDD", content: "Order es el Aggregate Root.\n\npublic IReadOnlyCollection<OrderItem> Items => _items.AsReadOnly();\npublic decimal Total => _items.Sum(item => item.Total);\n\nMetodos publicos:\nAddItem\nChangeItemQuantity\nRemoveItem\nConfirm\nCancel\n\nNunca permitimos order.Items.Add(item) ni item.Quantity = -20." },
  { id: "order-rules", label: "9) Reglas de Order", title: "Transiciones e invariantes", subtitle: "Solo una orden Draft puede modificarse y una orden vacia no puede confirmarse.", chip: "Reglas", content: "AddItem:\n- exige estado Draft\n- si el producto existe, aumenta cantidad\n- si no existe, crea OrderItem\n\nConfirm:\n- exige estado Draft\n- rechaza una orden vacia\n- exige total mayor que cero\n- cambia a PendingProcessing\n\nCancel:\n- solo permite cancelar Draft\n\nCada cambio actualiza UpdatedAt." },
  { id: "catalog-contract", label: "10) Contrato Catalog", title: "Consultar Catalog sin acoplar Application", subtitle: "Application depende de una abstraccion, no de HttpClient ni de detalles de transporte.", chip: "Contrato", content: "public interface ICatalogService\n{\n    Task<CatalogProductSnapshot?> GetProductAsync(\n        Guid productId, CancellationToken cancellationToken = default);\n}\n\npublic sealed record CatalogProductSnapshot(\n    Guid Id, string Name, decimal Price, bool Active);\n\nOrders.Application conoce el contrato. Infrastructure implementara HTTP." },
  { id: "repository", label: "11) Repositorio", title: "Persistencia de Orders", subtitle: "El repositorio carga el agregado completo y la unidad de trabajo guarda sus cambios.", chip: "Persistencia", content: "public interface IOrderRepository\n{\n    Task<Order?> GetByIdAsync(Guid orderId, CancellationToken ct = default);\n    Task AddAsync(Order order, CancellationToken ct = default);\n    void Update(Order order);\n}\n\npublic interface IUnitOfWork\n{\n    Task<int> SaveChangesAsync(CancellationToken ct = default);\n}\n\nGetByIdAsync debe usar Include(order => order.Items)." },
  { id: "dtos", label: "12) DTOs", title: "Contratos HTTP de Orders", subtitle: "Los DTOs expresan la API sin exponer directamente las entidades del dominio.", chip: "API", content: "CreateOrderRequest(Guid CustomerId)\nAddOrderItemRequest(Guid ProductId, int Quantity)\n\nOrderItemResponse:\nProductId, ProductName, UnitPrice, Quantity, Total\n\nOrderResponse:\nId, CustomerId, Status, Total, CreatedAt, Items\n\nLa respuesta muestra el snapshot almacenado, no consulta Catalog para reconstruirse." },
  { id: "application", label: "13) Application Service", title: "Casos de uso de Orders", subtitle: "El servicio coordina repositorio, Catalog y dominio sin duplicar reglas profundas.", chip: "Application", content: "CreateAsync:\n1. crea Order en Draft\n2. guarda\n3. devuelve OrderResponse\n\nGetByIdAsync:\n1. carga Order con Items\n2. mapea respuesta\n\nAddItemAsync:\n1. carga Order\n2. consulta Catalog\n3. valida existencia y Active\n4. llama order.AddItem(...)\n5. guarda\n\nConfirmAsync y CancelAsync llaman al dominio y persisten." },
  { id: "add-flow", label: "14) Agregar producto", title: "Flujo sincronico con Catalog", subtitle: "Orders necesita nombre, precio y estado inmediatamente para crear el snapshot.", chip: "Flujo", content: "Orders\n  |\n  v\nCatalog\n  |\n  v\nCatalogProductSnapshot\n  |\n  v\nOrder.AddItem\n  |\n  v\nSaveChanges\n\nSi Catalog devuelve null, el producto no existe. Si esta inactivo, la orden no cambia." },
  { id: "unavailable", label: "15) Catalog caido", title: "Dependencia no disponible", subtitle: "Orders no inventa precios ni accede directamente a CatalogDb.", chip: "Resiliencia", content: "Si Catalog esta caido:\n\nHTTP 503 Service Unavailable\n\n{\n  \"code\": \"orders.catalog_unavailable\",\n  \"message\": \"Catalog is temporarily unavailable.\"\n}\n\nMas adelante añadiremos timeout, retry, circuit breaker y cache." },
  { id: "http", label: "16) Cliente HTTP", title: "CatalogHttpService", subtitle: "Infrastructure implementa ICatalogService con un HttpClient tipado.", chip: "HTTP", content: "public async Task<CatalogProductSnapshot?> GetProductAsync(Guid id, CancellationToken ct)\n{\n    using var response = await _httpClient.GetAsync(\n        $\"internal/catalog/products/{id}\", ct);\n    if (response.StatusCode == HttpStatusCode.NotFound) return null;\n    response.EnsureSuccessStatusCode();\n    return await response.Content.ReadFromJsonAsync<CatalogProductSnapshot>(\n        cancellationToken: ct);\n}\n\nApplication nunca depende directamente de HttpClient." },
  { id: "http-config", label: "17) HttpClient", title: "Configurar la comunicacion", subtitle: "La URL de Catalog cambia entre local y Docker, por eso vive en configuracion.", chip: "Config", content: "services.AddHttpClient<ICatalogService, CatalogHttpService>((sp, httpClient) =>\n{\n    var url = sp.GetRequiredService<IConfiguration>()\n        [\"Services:Catalog:BaseUrl\"]\n        ?? throw new InvalidOperationException();\n    httpClient.BaseAddress = new Uri(url);\n    httpClient.Timeout = TimeSpan.FromSeconds(3);\n});\n\nLocal: http://localhost:5001/\nDocker: http://catalog-api:8080/" },
  { id: "dbcontext", label: "18) DbContext", title: "OrdersDb independiente", subtitle: "Orders tiene su propio DbContext, sus tablas y sus migraciones.", chip: "EF Core", content: "public sealed class OrdersDbContext : DbContext, IUnitOfWork\n{\n    public DbSet<Order> Orders => Set<Order>();\n    public DbSet<OrderItem> OrderItems => Set<OrderItem>();\n\n    protected override void OnModelCreating(ModelBuilder builder)\n    {\n        builder.ApplyConfigurationsFromAssembly(\n            typeof(OrdersDbContext).Assembly);\n    }\n}\n\nOrdersDb no depende del DbContext de Catalog." },
  { id: "mapping", label: "19) Mapping", title: "Configurar Order y OrderItem", subtitle: "El mapeo respeta el aggregate y evita calcular Total como columna almacenada.", chip: "Database", content: "Order:\n- tabla Orders\n- Status como string\n- FailureReason con maximo 500\n- Total ignorado\n- Items con cascade delete\n- acceso por field _items\n\nOrderItem:\n- tabla OrderItems\n- ProductName maximo 200\n- UnitPrice precision 18,2\n- Total ignorado\n- indice unico por OrderId y ProductId" },
  { id: "repository-impl", label: "20) Repositorio", title: "Cargar el agregado completo", subtitle: "Sin los items cargados, Total y las reglas del agregado no funcionan correctamente.", chip: "Include", content: "public async Task<Order?> GetByIdAsync(Guid orderId, CancellationToken ct = default)\n{\n    return await _dbContext.Orders\n        .Include(order => order.Items)\n        .FirstOrDefaultAsync(order => order.Id == orderId, ct);\n}\n\nEl Include es obligatorio para reconstruir Order con todos sus items." },
  { id: "controller", label: "21) Controller", title: "Exponer el proceso de orden", subtitle: "Los endpoints llaman casos de uso y devuelven codigos HTTP que representan el estado real.", chip: "Endpoints", content: "POST /api/orders\nGET /api/orders/{orderId}\nPOST /api/orders/{orderId}/items\nPOST /api/orders/{orderId}/confirm\nPOST /api/orders/{orderId}/cancel\n\nCreate devuelve 201 Created.\nGet devuelve 200 o 404.\nAddItem devuelve 200.\nConfirm devuelve 202 Accepted.\nCancel devuelve 200." },
  { id: "accepted", label: "22) 202 Accepted", title: "Por que confirmar devuelve 202", subtitle: "Confirmar solo inicia el procesamiento; aun faltan inventario, pago y notificacion.", chip: "HTTP", content: "Draft\n  |\n  v\nPendingProcessing\n\nTodavia no hemos:\nreservado inventario\nprocesado el pago\ncompletado la compra\nenviado la notificacion\n\n202 Accepted expresa que el proceso fue aceptado y continuara despues." },
  { id: "events", label: "23) Lo que falta", title: "Confirm todavia no publica eventos", subtitle: "Primero construimos el nucleo del dominio; RabbitMQ y Outbox vendran despues.", chip: "Roadmap", content: "Hoy:\nCambiar estado\n      |\n      v\nGuardar\n\nFuturo:\nOrderConfirmed\nInventoryReservationRequested\nPaymentRequested\n\nLos eventos se añadiran cuando configuremos RabbitMQ y Outbox." },
  { id: "ownership", label: "24) Propiedad de datos", title: "No hay claves foraneas entre servicios", subtitle: "ProductId es una referencia logica, no una foreign key hacia CatalogDb.", chip: "Ownership", content: "CatalogDb\n  Products\n\nOrdersDb\n  Orders\n  OrderItems.ProductId\n\nOrdersDb no tendra una foreign key hacia CatalogDb.Products.\n\nEntre microservicios usamos contratos e identificadores, no relaciones de base de datos cruzadas." },
  { id: "docker", label: "25) Docker Compose", title: "Levantar Orders con su base", subtitle: "Orders API y OrdersDb tendran servicios, red, volumen y health check propios.", chip: "Docker", content: "orders-api:\n  build: src/Services/Orders/Orders.API/Dockerfile\n  ports: 5002:8080\n  depends_on: orders-db y catalog-api\n  Services__Catalog__BaseUrl: http://catalog-api:8080/\n\norders-db:\n  image: postgres:17\n  database: orderflow_orders\n  volume: orders-data\n  healthcheck: pg_isready\n\nCada servicio conserva su propia persistencia." },
  { id: "migrations", label: "26) Migraciones", title: "Crear OrdersDb", subtitle: "La base independiente necesita su propia migracion y proceso de actualizacion.", chip: "EF CLI", content: "dotnet ef migrations add InitialOrders \\\n  --project src/Services/Orders/Orders.Infrastructure \\\n  --startup-project src/Services/Orders/Orders.API \\\n  --output-dir Persistence/Migrations\n\nDotnet ef database update se ejecuta usando los mismos project y startup-project." },
  { id: "manual-test", label: "27) Prueba manual", title: "Demostrar el flujo completo", subtitle: "El proceso debe poder probarse desde crear la orden hasta confirmar el snapshot.", chip: "Demo", content: "1. POST /api/orders con CustomerId\n2. POST /api/orders/{id}/items con ProductId y Quantity\n3. Orders consulta Catalog\n4. Se guarda nombre y precio historico\n5. POST /api/orders/{id}/confirm\n6. La orden cambia a PendingProcessing\n\nEjemplo: 2 x 89.99 = 179.98." },
  { id: "failures", label: "28) Fallos", title: "Casos que debemos probar", subtitle: "Las reglas importantes se validan observando que la orden no quede alterada cuando la operacion falla.", chip: "Testing", content: "Orden vacia -> 400 Bad Request\nProducto inexistente -> producto rechazado\nProducto inactivo -> no se agrega\nCantidad negativa -> 400 Bad Request\nModificar orden confirmada -> operacion rechazada\nCatalog no disponible -> 503 Service Unavailable\n\nEn cada fallo la orden debe conservar su estado anterior." },
  { id: "result", label: "29) Resultado", title: "Que hemos conseguido", subtitle: "Orders ya tiene propiedad de datos, dominio y contratos independientes.", chip: "Resultado", content: "Cliente\n  |\n  v\nGateway\n  |\n  v\nOrders\n  |\n  v\nCatalog\n\nCada servicio tiene:\nresponsabilidad propia\nbase de datos propia\ndominio propio\ncontratos propios\ndespliegue independiente\n\nOrders ya no accede directamente a Products." },
  { id: "checklist", label: "30) Checklist", title: "Validacion de la extraccion", subtitle: "El servicio esta listo cuando protege el flujo y puede ejecutarse sin CatalogDb.", chip: "Checklist", content: "Orders tiene base propia\nOrder es Aggregate Root\nItems se modifican mediante Order\nSolo Draft puede modificarse\nPrecio historico almacenado\nCatalog consultado por HTTP\nSin foreign keys entre servicios\nOrden vacia rechazada\nConfirm devuelve 202\nOrders puede ejecutarse sin CatalogDb\n\nLo siguiente sera crear Inventory Service." },
  { id: "senior", label: "31) Cierre", title: "Como piensa un backend senior", subtitle: "Extraer Orders es extraer reglas, transiciones, contratos y propiedad de datos, no solo tablas.", chip: "Cierre", content: "Backend junior:\nUna orden es una tabla con items.\n\nBackend senior:\nUna orden es un agregado que protege reglas, controla transiciones y conserva la historia de la compra.\n\nOrders no es un CRUD de ordenes. Es el servicio responsable de proteger el proceso de compra." },
];

export default function Daily138Client() {
  const [activeSection, setActiveSection] = useState("idea");

  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement | null;
      if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return;
      if (event.key.toLowerCase() === "p") window.location.href = "/daily/137";
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, []);

  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);

  return (
    <div className={styles.page}>
      <header className={styles.topbar}><div className={styles.topbarInner}>
        <div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Orders Service y el nucleo de la compra</div></div></div>
        <nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav>
        <div className={styles.actions}><Link className={styles.btn} href="/daily/137"><span className={styles.kbd}>←</span> Dia 137</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div>
      </div></header>
      <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}>
        <div className={styles.dailyHero}><div className={styles.createdAt}>22/07/2026</div><div className={styles.badge}>Daily #138 • Orders Service</div><h2 className={styles.title}>Extraer Orders Service y construir el nucleo del proceso de compra</h2><p className={styles.lead}>Orders no sera un CRUD de ordenes: sera el agregado que protege reglas, estados y el precio historico de cada compra.</p></div>
        <nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>
        {sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}
        <div className={styles.footerNav}><Link className={styles.btn} href="/daily/137"><span className={styles.kbd}>←</span> Dia 137</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div>
      </div></article></div></main>
    </div>
  );
}
