"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily/daily-lesson.module.css";

type Section = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: Section[] = [
  { id: "problem", label: "1) Problema", title: "Un login real, no una simulación", subtitle: "El objetivo era comprobar que una persona pudiera autenticarse desde un navegador contra un entorno ya desplegado.", chip: "E2E", content: "El flujo era concreto: abrir la aplicación, ir al login, introducir credenciales, pulsar Access y acabar en /en/home. Playwright controla navegadores reales, así que el recorrido atraviesa frontend, red, backend, sesión y redirección.\n\nAplicación → login → credenciales → Access\n→ autenticación → sesión → /en/home → PASS\n\nNo fue necesario levantar el frontend en local: el test apuntó al entorno ficticio https://testing.example.com." },
  { id: "setup", label: "2) Preparación", title: "Un proyecto E2E pequeño y ejecutable", subtitle: "Playwright se inicializó como proyecto independiente con su propia configuración.", chip: "Setup", content: "brinxpress-tests/\n├── tests/login.spec.js\n├── playwright.config.js\n├── package.json\n└── run.sh\n\nnpm init playwright@latest\nnpx playwright test tests/login.spec.js --project=chromium --headed\n\nNode.js permite ejecutar Playwright. La instalación preparó Chromium, Firefox y WebKit; pese a un aviso de compatibilidad del sistema operativo, descargó una build alternativa. Durante el desarrollo se usó --headed para observar el navegador, no solo leer un reporte." },
  { id: "locators", label: "3) Locators", title: "El DOM real manda", subtitle: "El primer intento falló porque automatizaba una interfaz imaginada, no la que veía el navegador.", chip: "DOM", content: "Se asumió input[type=\"email\"] y un botón Login. Al inspeccionar el frontend se descubrieron #email, #password y un botón cuyo nombre accesible era Access.\n\n// Suposición incorrecta\npage.locator('input[type=\"email\"]')\npage.getByRole('button', { name: 'Login' })\n\n// Elementos observados\npage.locator('#email')\npage.locator('#password')\npage.getByRole('button', { name: 'Access' })\n\nAutomatizar frontend significa estudiar el DOM real. Un selector erróneo puede fallar aunque la funcionalidad esté bien." },
  { id: "route", label: "4) Entrada", title: "La ruta inicial también es parte del test", subtitle: "La página de inicio no era la mejor puerta de entrada para autenticar.", chip: "Ruta", content: "En vez de navegar a /en/home, el test entró por /en/auth/login?callbackUrl=/en/home. El parámetro indica dónde debe continuar el usuario tras autenticarse y convierte la redirección en una expectativa clara.\n\nawait page.goto('https://testing.example.com/en/auth/login?callbackUrl=/en/home');\nawait expect(page).toHaveURL(/\\/en\\/home/);\n\nHacer clic no demuestra que el login haya terminado. La URL esperada es la primera evidencia observable del resultado." },
  { id: "environment", label: "5) Entorno", title: "Certificados y secretos son parte de la ejecución", subtitle: "El entorno introdujo HTTPS no confiable y credenciales que no debían quedar versionadas.", chip: "Config", content: "// playwright.config.js\nuse: {\n  ignoreHTTPSErrors: true,\n  trace: 'on-first-retry',\n}\n\nexport ADMIN_USER='...'\nexport ADMIN_PASSWORD='...'\n\nEl error net::ERR_CERT_AUTHORITY_INVALID era propio del certificado del entorno, no de Playwright. También apareció value: expected string, got undefined: una variable de entorno no estaba definida. El test conoce los nombres de los secretos, pero no almacena sus valores." },
  { id: "diagnosis", label: "6) Diagnóstico", title: "Cuando el click no produce autenticación", subtitle: "Los campos, el botón y las credenciales parecían correctos, pero el navegador seguía en el login.", chip: "Debug", content: "EMAIL: admin@example.com\nPASSWORD LENGTH: 13\nBUTTON DISABLED: false\nFORM ERRORS: 0\n\nPágina login       ✓\nClick              ✓\nPOST autenticación ✗\nRedirección        ✗\n\nHabía un role=alert sin mensaje y respuestas correctas de sesión y carrito, pero inicialmente no una petición POST de autenticación. Quitar la aserción final produjo un engañoso 1 passed: el script terminaba sin excepción, aunque el usuario no hubiera iniciado sesión. Un test pasa cuando demuestra el comportamiento esperado, no cuando sus instrucciones dejan de ejecutarse." },
  { id: "hydration", label: "7) Sincronización", title: "HTML visible no significa aplicación preparada", subtitle: "React aún no había conectado por completo los eventos del formulario.", chip: "React", content: "La hidratación conecta el HTML existente con estado, handlers e interactividad. Se podían ver los inputs y pulsar el botón antes de que el submit estuviera listo.\n\nawait page.goto(url, { waitUntil: 'networkidle' });\nawait page.waitForTimeout(1000); // espera temporal\n\nTambién se probó pressSequentially() para reproducir eventos de teclado. Después apareció el POST, el servidor respondió 200 y Playwright alcanzó /en/home. La espera fija resolvió el diagnóstico inicial, pero debe sustituirse por una condición observable del frontend." },
  { id: "test", label: "8) Test", title: "El flujo resultante", subtitle: "Cada paso ahora tiene una razón: ruta correcta, elementos reales y una verificación final.", chip: "Código", content: "import { test, expect } from '@playwright/test';\n\ntest('login', async ({ page }) => {\n  await page.goto('https://testing.example.com/en/auth/login?callbackUrl=/en/home', { waitUntil: 'networkidle' });\n  await page.waitForTimeout(1000);\n  await page.locator('#email').pressSequentially(process.env.ADMIN_USER!, { delay: 50 });\n  await page.locator('#password').pressSequentially(process.env.ADMIN_PASSWORD!, { delay: 50 });\n  await page.getByRole('button', { name: 'Access' }).click();\n  await expect(page).toHaveURL(/\\/en\\/home/);\n});" },
  { id: "qa", label: "9) QA", title: "Qué cubre realmente esta prueba", subtitle: "El login es una frontera donde varias capas deben colaborar correctamente.", chip: "Cobertura", content: "Formulario → validación frontend → eventos JavaScript\n→ HTTP → backend → autenticación → sesión → redirección\n\nEste primer test ya evidencia que el formulario acepta datos, el botón desencadena el flujo, el backend autentica y el usuario llega a la zona esperada. Todavía puede ampliarse con credenciales erróneas, permisos y una señal visible de sesión autenticada." },
  { id: "challenge", label: "10) Reto", title: "Añade una evidencia de sesión", subtitle: "La URL es buena evidencia, pero un elemento exclusivo de una sesión autenticada fortalece el test.", chip: "Práctica", content: "Tras iniciar sesión manualmente, inspecciona /en/home y encuentra un elemento real que solo pueda ver una persona autenticada. No copies un selector supuesto.\n\nObservar → entender → automatizar → comprobar\n\nLa siguiente mejora es sustituir la espera fija por una condición observable y añadir esa aserción de interfaz." },
];

export default function PlaywrightLesson() {
  const [activeSection, setActiveSection] = useState(sections[0].id);
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Backend Knowledge Lab</h1><div className={styles.brandSub}>QA Automation · Playwright</div></div></div><nav className={styles.nav} aria-label="Navegación"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link><Link className={styles.pill} href="/profile">Perfil</Link></nav><div className={styles.actions}><Link className={`${styles.btn} ${styles.primary}`} href="#problem">Empezar <span className={styles.kbd}>↓</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.badge}>Clase 1 · QA Automation</div><h2 className={styles.title}>Nuestro primer test de frontend con Playwright</h2><div className={styles.meta} aria-label="Metadatos"><span className={`${styles.chip} ${styles.chipOk}`}>5–10 min</span><span className={styles.chip}>Nivel: inicial</span><span className={`${styles.chip} ${styles.chipPro}`}>Playwright</span><span className={styles.chip}>Testing E2E</span></div><p className={styles.lead}>Automatizar un login desplegado sirve para aprender locators, rutas, secretos, sincronización y qué evidencia hace que un test sea confiable.</p></div><nav className={styles.toc} aria-label="Índice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily">Ver archivo de lecciones</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
