"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "idea", label: "1) Idea clave", title: "Evitar eventos perdidos", subtitle: "Guardar una orden y publicar su evento son operaciones diferentes si RabbitMQ esta fuera de la transaccion.", chip: "Idea", content: "Orders confirma una orden.\n\n1. Guarda la orden.\n2. Intenta publicar OrderConfirmed.\n3. RabbitMQ esta caido.\n\nResultado:\nOrder = PendingProcessing\nMensaje = perdido\nInventory nunca reserva\nPayments nunca cobra\n\nHoy resolvemos este problema con Transactional Outbox." },
  { id: "dual-write", label: "2) Dual write", title: "El problema de las dos escrituras", subtitle: "PostgreSQL y RabbitMQ no comparten una transaccion local sencilla.", chip: "Riesgo", content: "Orders necesita:\n\nActualizar Order\nPublicar OrderConfirmed\n\nPero escribe en:\nPostgreSQL\nRabbitMQ\n\nEsto se conoce como Dual Write Problem. Cambiar el orden tampoco lo resuelve: siempre existe una ventana de fallo entre ambos sistemas." },
  { id: "outbox", label: "3) Outbox", title: "Que es Transactional Outbox", subtitle: "El evento se guarda en una tabla local junto al cambio de negocio y se publica despues.", chip: "Patron", content: "En vez de:\nGuardar Order -> Publicar RabbitMQ\n\nHacemos:\nGuardar Order\nGuardar OutboxMessage\n        |\n        v\nMisma transaccion PostgreSQL\n\nDespues un worker lee mensajes pendientes, publica y marca ProcessedAt." },
  { id: "guarantee", label: "4) Garantia", title: "Que garantiza Outbox", subtitle: "Todo cambio confirmado conserva su evento aunque el broker este temporalmente caido.", chip: "Consistencia", content: "Si la transaccion falla:\nNi Order ni OutboxMessage quedan guardados.\n\nSi funciona:\nOrder y evento quedan registrados.\n\nRabbitMQ puede estar apagado. El evento permanece en la base y se publicara cuando el worker pueda procesarlo." },
  { id: "at-least-once", label: "5) At least once", title: "Outbox puede duplicar mensajes", subtitle: "Evita perdidas, pero no garantiza que un mensaje se publique exactamente una vez.", chip: "Entrega", content: "1. Outbox publica el mensaje.\n2. RabbitMQ lo recibe.\n3. El worker cae antes de marcar ProcessedAt.\n4. Reinicia.\n5. Publica el mismo mensaje otra vez.\n\nPor eso los consumidores necesitan Inbox e idempotencia por MessageId." },
  { id: "model", label: "6) OutboxMessage", title: "El modelo de la tabla Outbox", subtitle: "La entidad tecnica conserva payload, metadata, reintentos y el ultimo error.", chip: "Modelo", content: "OutboxMessage:\nId = MessageId\nOccurredAt\nType\nContent JSON\nCorrelationId\nCausationId\nCreatedAt\nProcessedAt\nRetryCount\nNextRetryAt\nError\n\nId mantiene la identidad durante todos los reintentos." },
  { id: "fields", label: "7) Campos", title: "Campos importantes", subtitle: "Cada fecha y estado permite operar, investigar y reintentar el mensaje correctamente.", chip: "Metadata", content: "Type identifica el contrato.\nContent contiene JSON serializado.\nOccurredAt marca el hecho de negocio.\nCreatedAt marca su registro local.\nProcessedAt marca publicacion exitosa.\nRetryCount cuenta fallos.\nNextRetryAt controla el proximo intento.\nError conserva el ultimo motivo." },
  { id: "mapping", label: "8) Mapeo", title: "El evento nace en el dominio", subtitle: "El dominio comunica que ocurrio algo; Infrastructure lo transforma en un contrato y OutboxMessage.", chip: "DDD", content: "Order.Confirm()\n        |\n        v\nOrderConfirmedDomainEvent\n        |\n        v\nOrderConfirmedIntegrationEvent\n        |\n        v\nOutboxMessage\n\nOrder no conoce RabbitMQ, JSON ni tablas tecnicas." },
  { id: "domain-event", label: "9) Domain Event", title: "Registrar OrderConfirmed", subtitle: "El agregado levanta un evento cuando cambia de forma valida.", chip: "Domain", content: "OrderConfirmedDomainEvent:\nOrderId\nCustomerId\nTotal\nItems\nOccurredAt\n\nCuando Confirm valida que la orden no esta vacia:\nStatus = PendingProcessing\nConfirmedAt = ahora\nRaiseDomainEvent(OrderConfirmedDomainEvent)\n\nLa entidad comunica el hecho sin publicar directamente." },
  { id: "entity", label: "10) Entity base", title: "Guardar eventos del agregado", subtitle: "Una clase Entity puede acumular eventos hasta que el contexto los convierta en Outbox.", chip: "BuildingBlocks", content: "Entity:\nprivate List<object> _domainEvents\n\nDomainEvents => solo lectura\nRaiseDomainEvent(event)\nClearDomainEvents()\n\nOrder hereda de Entity y mantiene sus eventos durante la unidad de trabajo." },
  { id: "context", label: "11) DbContext", title: "Outbox en OrdersDb", subtitle: "La tabla Outbox debe vivir en la misma base y DbContext que Order.", chip: "EF Core", content: "OrdersDbContext:\nDbSet<Order> Orders\nDbSet<OrderItem> OrderItems\nDbSet<OutboxMessage> OutboxMessages\n\nApplyConfigurationsFromAssembly registra el mapeo de la entidad tecnica." },
  { id: "config", label: "12) Configuracion", title: "Mapear OutboxMessages", subtitle: "Indices sobre ProcessedAt y NextRetryAt hacen eficiente la consulta del worker.", chip: "Database", content: "Table: OutboxMessages\nKey: Id\nType: maximo 500 y requerido\nContent: jsonb y requerido\nCorrelationId: requerido\nError: maximo 4000\nIndex: ProcessedAt\nIndex: NextRetryAt\nIndex compuesto: ProcessedAt + NextRetryAt" },
  { id: "manual", label: "13) Estrategia manual", title: "Guardar Outbox desde Application", subtitle: "Funciona al principio, pero repite serializacion y detalles tecnicos en cada caso de uso.", chip: "Primera version", content: "ConfirmAsync:\n1. cargar Order\n2. order.Confirm()\n3. crear OrderConfirmedIntegrationEvent\n4. serializarlo\n5. crear OutboxMessage\n6. agregarlo al repositorio\n7. SaveChangesAsync\n\nOrder y OutboxMessage usan el mismo DbContext y la misma transaccion." },
  { id: "repository", label: "14) Repositorio", title: "IOutboxRepository", subtitle: "Application puede abstraer el agregado tecnico mientras el contexto comparte la transaccion.", chip: "Abstraccion", content: "IOutboxRepository:\nTask AddAsync(\n    OutboxMessage message,\n    CancellationToken cancellationToken = default);\n\nOutboxRepository solo agrega a OrdersDbContext. El commit sigue ocurriendo en SaveChangesAsync." },
  { id: "interceptor", label: "15) Interceptor", title: "Convertir eventos automaticamente", subtitle: "Un SaveChangesInterceptor captura eventos antes de guardar y crea OutboxMessages de forma transversal.", chip: "Infrastructure", content: "SavingChangesAsync:\n1. buscar Entities con DomainEvents\n2. extraer los eventos\n3. mapearlos a IntegrationEvents\n4. crear OutboxMessages\n5. agregarlos al DbContext\n6. continuar SaveChanges\n\nAsi ConfirmAsync solo cambia el dominio y guarda." },
  { id: "mapper", label: "16) Mapper", title: "Domain event a integration event", subtitle: "El mapper evita que el contrato externo dependa de clases internas del dominio.", chip: "Contratos", content: "IntegrationEventMapper.Map(domainEvent)\n\nOrderConfirmedDomainEvent ->\nOrderConfirmedIntegrationEvent\n\nEl resultado define MessageId, CorrelationId, CausationId, EventType, Version y payload estable." },
  { id: "registration", label: "17) Registro", title: "Registrar el interceptor", subtitle: "EF Core debe usar el mismo interceptor en todos los SaveChanges de OrdersDbContext.", chip: "DI", content: "services.AddSingleton<ConvertDomainEventsToOutboxInterceptor>();\n\nservices.AddDbContext<OrdersDbContext>((sp, options) =>\n{\n    options.UseNpgsql(connectionString);\n    options.AddInterceptors(sp.GetRequiredService<ConvertDomainEventsToOutboxInterceptor>());\n});" },
  { id: "cleanup", label: "18) Limpiar eventos", title: "No borrar eventos demasiado pronto", subtitle: "Si SaveChanges falla despues de limpiar DomainEvents, el evento puede desaparecer de memoria.", chip: "Cuidado", content: "Version debil:\nCapturar -> agregar Outbox -> ClearDomainEvents -> intentar guardar\n\nSi falla el guardado, perdemos el evento en memoria.\n\nVersiones mas robustas:\n- limpiar solo despues del exito\n- restaurar si falla\n- controlar el ciclo desde SaveChangesAsync." },
  { id: "override", label: "19) Override", title: "Alternativa con SaveChangesAsync", subtitle: "Sobrescribir el DbContext puede ser mas sencillo de comprender al comenzar.", chip: "Diseño", content: "SaveChangesAsync:\n1. AddDomainEventsToOutbox()\n2. await base.SaveChangesAsync()\n3. ClearDomainEvents() solo tras exito\n4. devolver resultado\n\nLa logica sigue dentro de la misma transaccion local." },
  { id: "factory", label: "20) Factory", title: "OutboxMessageFactory", subtitle: "Una factory centraliza serializacion, metadata y construccion del mensaje tecnico.", chip: "BuildingBlocks", content: "OutboxMessageFactory.Create(IIntegrationEvent):\n\n- serializa con JsonSerializerDefaults.Web\n- usa el tipo concreto del evento\n- conserva MessageId y OccurredAt\n- guarda CorrelationId y CausationId\n- devuelve OutboxMessage\n\nLos casos de uso no repiten este codigo." },
  { id: "processor", label: "21) Worker", title: "OutboxProcessor", subtitle: "Un BackgroundService publica los mensajes pendientes en lotes pequeños.", chip: "Worker", content: "OutboxProcessor:\n1. crear scope\n2. seleccionar pendientes\n3. respetar NextRetryAt\n4. publicar en IEventBus\n5. marcar ProcessedAt si funciona\n6. MarkAsFailed si falla\n7. esperar antes del siguiente lote\n\nEl worker debe detenerse con CancellationToken y registrar logs." },
  { id: "selection", label: "22) Seleccion", title: "Consultar mensajes pendientes", subtitle: "El worker no debe leer mensajes ya procesados ni reintentar antes de tiempo.", chip: "Consulta", content: "Pendiente cuando:\nProcessedAt == null\nAND (NextRetryAt == null OR NextRetryAt <= ahora)\n\nOrdenar por CreatedAt.\nLimitar el lote.\n\nEn produccion puede requerirse locking para evitar que dos workers procesen la misma fila." },
  { id: "retry", label: "23) Retries", title: "Reintentos con backoff", subtitle: "Cada fallo actualiza RetryCount, Error y NextRetryAt sin bloquear el resto del lote.", chip: "Resiliencia", content: "Intento 1 -> 5 segundos\nIntento 2 -> 30 segundos\nIntento 3 -> 2 minutos\nIntento 4 -> 10 minutos\n\nEl delay puede ser exponencial con jitter.\n\nDespues del limite, marcar como fallo permanente o enviar a una DLQ de Outbox." },
  { id: "publish-failure", label: "24) Fallo de broker", title: "RabbitMQ caido no pierde la orden", subtitle: "El worker falla, registra el error y vuelve a intentarlo mas tarde.", chip: "Operacion", content: "Orders confirma\n      |\n      v\nOrder + Outbox COMMIT\n      |\n      v\nRabbitMQ caido\n      |\n      v\nOutbox.Error + RetryCount\n      |\n      v\nProximo intento\n\nEl estado de negocio y el evento siguen alineados." },
  { id: "duplicates", label: "25) Duplicados", title: "Outbox necesita consumidores idempotentes", subtitle: "El worker puede publicar dos veces si cae despues del publish y antes de marcar procesado.", chip: "Idempotencia", content: "MessageId = abc-123\n\nPublicar -> broker recibe\nWorker cae\nPublicar de nuevo -> mismo MessageId\n\nInventory y Payments deben registrar MessageId procesados y no repetir reservar, cobrar o completar." },
  { id: "transaction", label: "26) Atomicidad", title: "La transaccion local es la frontera", subtitle: "Outbox no intenta una transaccion distribuida entre PostgreSQL y RabbitMQ.", chip: "Diseño", content: "Dentro de PostgreSQL:\nOrder + OutboxMessage\n\nFuera de PostgreSQL:\nRabbitMQ\n\nLa garantia es:\nTodo cambio confirmado deja un mensaje persistido.\n\nLa entrega posterior es al menos una vez y depende de idempotencia del consumidor." },
  { id: "observability", label: "27) Observabilidad", title: "Medir la salud de Outbox", subtitle: "Una Outbox sin metricas puede acumular miles de eventos silenciosamente.", chip: "Operabilidad", content: "Metricas utiles:\nPendingMessages\nOldestMessageAge\nPublishSuccessCount\nPublishFailureCount\nRetryCount\nPermanentFailureCount\nProcessingDuration\n\nLogs deben incluir MessageId, CorrelationId, EventType, RetryCount y Exception." },
  { id: "testing", label: "28) Pruebas", title: "Casos que debemos probar", subtitle: "La garantia debe demostrarse en transacciones, fallos del broker y reintentos.", chip: "Testing", content: "Confirmar guarda Order y Outbox.\nFallo de transaccion no guarda ninguno.\nRabbitMQ caido deja Outbox pendiente.\nWorker publica y marca ProcessedAt.\nFallo despues de publicar permite duplicado.\nRetry actualiza Error y NextRetryAt.\nMensaje procesado no vuelve a enviarse.\nDomainEvent se transforma al contrato correcto.\nEvento conserva CorrelationId y Version." },
  { id: "checklist", label: "29) Checklist", title: "Validacion de Transactional Outbox", subtitle: "El patron esta bien implementado cuando un cambio confirmado nunca queda sin su evento persistido.", chip: "Checklist", content: "OutboxMessages existe\nMismo DbContext que el agregado\nMisma transaccion local\nMessageId estable\nJSON y Type guardados\nProcessedAt indexado\nRetryCount y NextRetryAt\nWorker con scopes\nBackoff configurado\nErrores observables\nConsumidores idempotentes\nPruebas de rollback\nPruebas de duplicados\n\nOutbox evita perdida, no elimina la necesidad de Inbox." },
  { id: "closing", label: "30) Cierre", title: "Como piensa un backend senior", subtitle: "No basta con publicar un evento despues de guardar: hay que garantizar que el cambio y su mensaje sobrevivan juntos.", chip: "Cierre", content: "Backend junior:\nGuardo la orden y despues publico.\n\nBackend senior:\nGuardo el estado y el evento en una misma transaccion local, proceso la Outbox con reintentos y diseño consumidores idempotentes para la entrega al menos una vez.\n\nTransactional Outbox convierte un problema de coordinacion en un flujo recuperable y observable." },
];

export default function Daily142Client() {
  const [activeSection, setActiveSection] = useState("idea");

  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement | null;
      if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return;
      if (event.key.toLowerCase() === "p") window.location.href = "/daily/141";
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, []);

  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);

  return (
    <div className={styles.page}>
      <header className={styles.topbar}><div className={styles.topbarInner}>
        <div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Transactional Outbox y eventos confiables</div></div></div>
        <nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav>
        <div className={styles.actions}><Link className={styles.btn} href="/daily/141"><span className={styles.kbd}>←</span> Dia 141</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div>
      </div></header>
      <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}>
        <div className={styles.dailyHero}><div className={styles.createdAt}>28/07/2026</div><div className={styles.badge}>Daily #142 • Transactional Outbox</div><h2 className={styles.title}>Implementar Transactional Outbox y evitar eventos perdidos</h2><p className={styles.lead}>El cambio de negocio y el evento que lo representa deben persistirse juntos para que RabbitMQ pueda fallar sin perder el flujo.</p></div>
        <nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>
        {sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}
        <div className={styles.footerNav}><Link className={styles.btn} href="/daily/141"><span className={styles.kbd}>←</span> Dia 141</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div>
      </div></article></div></main>
    </div>
  );
}
