"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "problem", label: "1) Problema", title: "Una operacion que necesita orden", subtitle: "TradeOps debe crecer con dominio, importaciones y futuras integraciones sin convertirse en un modulo inmantenible.", chip: "Contexto", content: "TradeOps 360\n  |\n  +-- clientes\n  +-- equipos\n  +-- tickets\n  +-- ordenes de trabajo\n  +-- importaciones\n  +-- integraciones\n\nLa arquitectura empieza separando responsabilidades antes de acumular modelos y datos en una sola carpeta." },
  { id: "module", label: "2) Modulo", title: "Que es realmente un modulo Odoo", subtitle: "Es una unidad instalable con manifest, imports, modelos, vistas, datos, seguridad y tests.", chip: "Odoo", content: "trade_core/\n├── __init__.py\n├── __manifest__.py\n├── models/\n├── views/\n├── security/\n├── data/\n└── tests/\n\nEl modulo declara sus dependencias y le dice al registry como cargar sus piezas." },
  { id: "core", label: "3) trade_core", title: "Crear el nucleo del dominio", subtitle: "trade_core contiene los modelos y reglas que representan el negocio principal de TradeOps.", chip: "Core", content: "trade_core\n  +-- equipment\n  +-- service.ticket\n  +-- work.order\n  +-- estados\n  +-- relaciones\n  +-- reglas\n\nDebe ser estable y reutilizable. Otros modulos pueden depender de el, pero el core no debe conocer cada integracion futura." },
  { id: "manifest", label: "4) Manifest", title: "Describir el modulo", subtitle: "`__manifest__.py` define identidad, dependencias, datos cargados y opciones de instalacion.", chip: "Manifest", content: "{\n    'name': 'Trade Core',\n    'version': '17.0.1.0.0',\n    'depends': ['base', 'mail'],\n    'data': [\n        'security/ir.model.access.csv',\n        'views/equipment_views.xml',\n    ],\n    'installable': True,\n}\n\nUn manifest incorrecto puede ocultar el modulo, romper la carga o dejar datos sin instalar." },
  { id: "depends", label: "5) depends", title: "Declarar dependencias reales", subtitle: "Odoo carga primero los modulos declarados en `depends` y pone sus modelos a disposicion del nuevo modulo.", chip: "Dependencias", content: "trade_core depende de:\nbase -> modelos y usuarios\nmail -> chatter y tracking\n\ntrade_import depende de:\ntrade_core -> modelos FieldOps\n\nNo declarar dependencias por costumbre. Cada una aumenta el acoplamiento y debe justificar una capacidad usada." },
  { id: "init", label: "6) Imports", title: "El papel de __init__.py", subtitle: "Los archivos de inicializacion conectan el paquete Python con los modelos que Odoo debe cargar.", chip: "Python", content: "trade_core/__init__.py\n    from . import models\n\ntrade_core/models/__init__.py\n    from . import equipment\n    from . import ticket\n\nSi el import falta, el archivo existe pero el registry no conoce el modelo. Los logs deben confirmar la carga." },
  { id: "import", label: "7) trade_import", title: "Separar la entrada de datos", subtitle: "Las importaciones tienen reglas, formatos y errores propios; no deben contaminar el nucleo del dominio.", chip: "Import", content: "trade_import/\n├── __init__.py\n├── __manifest__.py\n├── models/\n├── wizard/\n├── data/\n└── tests/\n\nPuede leer CSV, validar columnas, resolver clientes y equipos y reportar errores sin convertir trade_core en un importador gigante." },
  { id: "separation", label: "8) Separacion", title: "Por que separar Core e Imports", subtitle: "El nucleo representa el negocio; el modulo de entrada transforma formatos externos en comandos validos.", chip: "Diseño", content: "Archivo externo\n    |\n    v\ntrade_import\n    | valida y transforma\n    v\ntrade_core\n    | aplica reglas\n    v\nPostgreSQL\n\nBeneficios:\n- menor acoplamiento\n- tests mas claros\n- upgrades controlados\n- integraciones reemplazables" },
  { id: "install", label: "9) Instalar", title: "Instalar modulos correctamente", subtitle: "Instalar crea estructuras y datos iniciales; la operacion debe quedar registrada y ser reproducible.", chip: "Operacion", content: "1. Copiar modulo en addons_path.\n2. Reiniciar Odoo si corresponde.\n3. Actualizar lista de aplicaciones.\n4. Buscar trade_core.\n5. Instalar.\n6. Verificar logs y menus.\n7. Instalar trade_import despues.\n\nEl orden respeta las dependencias declaradas." },
  { id: "upgrade", label: "10) Actualizar", title: "Instalar no es actualizar", subtitle: "Cambiar codigo existente requiere upgrade del modulo y pruebas sobre datos ya persistidos.", chip: "Upgrade", content: "Instalar:\ncrea el modulo por primera vez.\n\nActualizar:\nlee cambios de Python, XML, seguridad y datos.\n\nTras un cambio:\n- ejecutar upgrade\n- revisar logs\n- probar vistas\n- comprobar datos existentes\n- validar rollback o backup\n\nNunca asumir que reiniciar basta." },
  { id: "evolution", label: "11) Evolucion", title: "El manifest crecera con TradeOps", subtitle: "A medida que aparecen vistas, reportes, seguridad y cron, el manifest debe conservar un orden claro.", chip: "Roadmap", content: "'data': [\n  'security/groups.xml',\n  'security/ir.model.access.csv',\n  'data/service_types.xml',\n  'views/equipment_views.xml',\n  'views/ticket_views.xml',\n  'report/work_order_report.xml',\n  'data/cron.xml',\n]\n\nOrdenar dependencias y datos facilita revisar, instalar y actualizar." },
  { id: "state", label: "12) Estado", title: "TradeOps despues de hoy", subtitle: "La estructura de modulos permite que el proyecto avance sin mezclar dominio, importacion y futuras capacidades.", chip: "Milestone", content: "trade_core\n  -> dominio principal\n\ntrade_import\n  -> entrada de datos\n\nSiguiente crecimiento:\n- modelos de equipos\n- vistas\n- seguridad\n- tickets\n- work orders\n- reportes\n- tests\n\nCada incremento debe actualizar el modulo correcto." },
  { id: "qa", label: "13) QA", title: "Comprobar la anatomia", subtitle: "La calidad inicial se verifica instalando, actualizando y comprobando que las dependencias se cargan en el orden esperado.", chip: "QA", content: "trade_core aparece en Apps\nManifest valido\nDependencias instaladas\nImports completos\nModelos visibles en registry\ntrade_import no instala antes del core\nUpgrade sin perdida de datos\nLogs sin warnings bloqueantes\nTests de instalacion\nTests de validacion de imports" },
  { id: "checklist", label: "14) Checklist", title: "Modulo mantenible", subtitle: "La estructura es buena cuando permite cambiar una responsabilidad sin tocar todas las demas.", chip: "Checklist", content: "Nombres claros\nManifest versionado\nDepends minimo\n__init__.py correcto\nCore separado\nImports separado\nDatos ordenados\nSecurity declarada\nViews agrupadas\nTests por modulo\nUpgrade probado\nDocumentacion actualizada" },
  { id: "closing", label: "15) Cierre", title: "La estructura anticipa el crecimiento", subtitle: "Separar un core estable de modulos de entrada permite que TradeOps evolucione sin convertirse en un bloque fragil.", chip: "Cierre", content: "Backend junior:\nMeto todos los archivos donde funcionen.\n\nBackend senior:\nDefine modulos, dependencias, limites de dominio, orden de carga y estrategia de upgrade.\n\ntrade_core y trade_import son el primer paso de una arquitectura Odoo mantenible." },
];

export default function Daily159Client() {
  const [activeSection, setActiveSection] = useState("problem");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/158"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Anatomia de un modulo Odoo</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/158"><span className={styles.kbd}>←</span> Dia 158</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>24/08/2026</div><div className={styles.badge}>Daily #159 • Odoo Modules</div><h2 className={styles.title}>Anatomia de un modulo Odoo: crear trade_core y trade_import</h2><p className={styles.lead}>Separar el nucleo de TradeOps 360 de sus importaciones para construir un sistema Odoo mantenible y ampliable.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/158"><span className={styles.kbd}>←</span> Dia 158</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
