"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "problem", label: "1) Problema", title: "Importar equipos sin perder reglas", subtitle: "TradeOps necesita recibir datos externos y convertirlos en registros validos del dominio.", chip: "Contexto", content: "Archivo externo\n  |\n  v\ntrade_import\n  | valida\n  v\ntrade_core\n  | ORM\n  v\nPostgreSQL\n\nLa importacion no debe escribir tablas directamente ni saltarse las reglas del modelo." },
  { id: "orm", label: "2) ORM", title: "El ORM de Odoo", subtitle: "El Object Relational Mapper conecta modelos Python con registros PostgreSQL y aplica el contexto del framework.", chip: "ORM", content: "Modelo Python\n  |\n  v\nOdoo ORM\n  |\n  v\nPostgreSQL\n\nEl ORM ofrece create, search, write, unlink, relaciones, permisos, cache y transacciones sin construir SQL para cada operacion." },
  { id: "model", label: "3) Modelo", title: "Crear el primer modelo", subtitle: "Un modelo representa una entidad del dominio y concentra datos y comportamiento relacionado.", chip: "Model", content: "from odoo import models, fields\n\nclass Equipment(models.Model):\n    _name = 'tradeops.equipment'\n    _description = 'Installed Equipment'\n\n    name = fields.Char(required=True)\n    serial_number = fields.Char(required=True)\n\nEl modelo debe vivir en trade_core y estar conectado mediante __init__.py." },
  { id: "model-base", label: "4) models.Model", title: "Heredar del modelo base", subtitle: "`models.Model` aporta el comportamiento persistente que Odoo necesita para registrar entidades.", chip: "Python", content: "class Equipment(models.Model):\n    _name = 'tradeops.equipment'\n\nLa herencia tecnica conecta la clase con el ORM. No es una clase Python aislada: Odoo la descubre al cargar el registry y crea su metadata." },
  { id: "name", label: "5) _name", title: "Elegir un nombre estable", subtitle: "`_name` es el identificador tecnico del modelo y forma parte de sus referencias, permisos y relaciones.", chip: "Identidad", content: "_name = 'tradeops.equipment'\n\nUsar nombres consistentes por modulo y dominio. Cambiarlo despues puede afectar datos, XML IDs, ACL, vistas e integraciones. Elegirlo antes de publicar el modelo." },
  { id: "fields", label: "6) Fields", title: "Describir los datos", subtitle: "Cada Field define tipo, validacion, etiqueta, comportamiento y posibles relaciones.", chip: "Fields", content: "name = fields.Char()\nserial_number = fields.Char()\ninstallation_date = fields.Date()\nstate = fields.Selection([...])\nwarranty_until = fields.Date()\npartner_id = fields.Many2one('res.partner')\nnotes = fields.Text()\n\nLos fields son parte del contrato del modelo y de la interfaz generada por Odoo." },
  { id: "defaults", label: "7) Reglas basicas", title: "required y default", subtitle: "Los defaults ayudan al flujo; required protege datos esenciales, pero no reemplaza todas las reglas de negocio.", chip: "Validacion", content: "state = fields.Selection(\n    [('active', 'Active'), ('retired', 'Retired')],\n    default='active',\n    required=True,\n)\n\nDefinir que campo es obligatorio, que valor inicial es seguro y que validaciones necesitan una constraint posterior." },
  { id: "register", label: "8) Registro", title: "Hacer que Odoo conozca el modelo", subtitle: "Crear el archivo no basta: los imports deben conectarlo con el registry.", chip: "Registry", content: "trade_core/__init__.py\n    from . import models\n\ntrade_core/models/__init__.py\n    from . import equipment\n\nDespues revisar logs. Si el import falta, el modelo no existe para Odoo aunque el archivo este en disco." },
  { id: "upgrade", label: "9) Actualizar", title: "Aplicar cambios del modelo", subtitle: "El modulo debe actualizarse para que Odoo registre fields, metadata y cambios de esquema.", chip: "Upgrade", content: "1. Detener o preparar el servidor.\n2. Corregir imports y manifest.\n3. Ejecutar upgrade del modulo.\n4. Revisar logs y PostgreSQL.\n5. Probar instalacion limpia.\n6. Probar sobre datos existentes.\n\nReiniciar sin upgrade no aplica automaticamente todos los cambios." },
  { id: "shell", label: "10) Sin interfaz", title: "Probar el modelo desde shell", subtitle: "La interfaz es una capa; el ORM debe poder probarse directamente y de forma reproducible.", chip: "Debug", content: "env['tradeops.equipment'].create({\n    'name': 'Pump A',\n    'serial_number': 'SN-001',\n})\n\nComprobar:\n- registro creado\n- fields accesibles\n- default aplicado\n- permisos correctos\n- transaccion persistida\n\nEl shell ayuda a separar errores del modelo de errores de la vista." },
  { id: "import", label: "11) Importacion", title: "Crear la primera importacion", subtitle: "trade_import recibe filas, valida columnas y usa el modelo core para crear equipos.", chip: "Import", content: "CSV\n  |\n  v\ntrade_import\n  | parsea y valida\n  v\nvals = {name, serial_number, partner_id}\n  |\n  v\nenv['tradeops.equipment'].create(vals)\n\nSi una fila es invalida, devolver un error util y decidir si la importacion es atomica o parcial de forma explicita." },
  { id: "recordset", label: "12) Recordsets", title: "Pensar en conjuntos de registros", subtitle: "En Odoo `self` suele representar cero, uno o muchos registros, no necesariamente una sola fila.", chip: "Recordset", content: "equipments = env['tradeops.equipment'].search([])\n\nUn recordset puede ser:\n- vacio\n- un registro\n- varios registros\n\nLos metodos deben respetar esa semantica y no asumir que self siempre contiene exactamente un elemento." },
  { id: "search", label: "13) search", title: "Buscar con domains", subtitle: "`search()` devuelve recordsets filtrados mediante domains expresivos y compatibles con el ORM.", chip: "Query", content: "equipments = env['tradeops.equipment'].search([\n    ('state', '=', 'active'),\n])\n\nEl domain expresa la intencion. Añadir limit, order o campos adecuados cuando el caso lo necesite y evitar cargar registros innecesarios." },
  { id: "write", label: "14) write y self", title: "Modificar registros correctamente", subtitle: "`write()` opera sobre el recordset y `self` representa el conjunto recibido por el metodo.", chip: "Operacion", content: "equipments.write({'state': 'retired'})\n\nPara un metodo de modelo:\n- validar self\n- respetar recordsets multiples\n- aplicar reglas de negocio\n- usar write/create del ORM\n- conservar permisos y contexto\n\nNo iterar por costumbre si una operacion por conjunto expresa mejor la intencion." },
  { id: "result", label: "15) Resultado", title: "Lo construido hoy", subtitle: "TradeOps ya tiene el camino tecnico para pasar de un archivo externo a un modelo persistente.", chip: "Milestone", content: "trade_core\n  -> Equipment model\n  -> Fields\n  -> registry\n  -> create/search/write\n\ntrade_import\n  -> parsea filas\n  -> valida datos\n  -> llama al ORM\n  -> informa errores\n\nLa importacion usa el dominio; no crea una segunda implementacion de reglas." },
  { id: "qa", label: "16) QA", title: "Comprobar el primer flujo", subtitle: "La primera evidencia debe cubrir modelo, persistencia, importacion y comportamiento con datos invalidos.", chip: "QA", content: "Modelo aparece en registry\nCreate persiste equipo\nRequired rechaza datos incompletos\nDefault aplica estado\nSearch devuelve recordset\nWrite actualiza registros\nFila valida se importa\nFila invalida informa error\nNo hay SQL directo\nPermisos se respetan\nTests ejecutables desde CI" },
  { id: "closing", label: "17) Cierre", title: "El ORM es una frontera de arquitectura", subtitle: "Usarlo bien permite que TradeOps evolucione con reglas, permisos, relaciones y migraciones controladas.", chip: "Cierre", content: "Backend junior:\nCreo tablas y las lleno desde un script.\n\nBackend senior:\nModela entidades, usa Fields, respeta recordsets, busca con domains, modifica mediante ORM y convierte importaciones en comandos de dominio.\n\nHoy TradeOps deja de ser solo estructura y empieza a persistir negocio." },
];

export default function Daily160Client() {
  const [activeSection, setActiveSection] = useState("problem");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/159"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>ORM, Fields y Recordsets en Odoo</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/159"><span className={styles.kbd}>←</span> Dia 159</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>25/08/2026</div><div className={styles.badge}>Daily #160 • Odoo ORM</div><h2 className={styles.title}>ORM, modelos, Fields y Recordsets: creando nuestra primera importacion</h2><p className={styles.lead}>Crear un modelo persistente y convertir filas externas en equipos validos de TradeOps mediante el ORM de Odoo.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/159"><span className={styles.kbd}>←</span> Dia 159</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
