"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "problem", label: "1) Problema", title: "Convertir sin duplicar la venta", subtitle: "Una preventa confirmada debe crear una venta estándar cuando la importación ya pueda entregarse.", chip: "Contexto", content: "trade.import\n  -> mercancia completada\ntrade.presale\n  -> compromiso comercial confirmado\nsale.order\n  -> venta estandar Odoo\n\nLa conversion une nuestro flujo custom con la funcionalidad nativa de ventas." },
  { id: "integration", label: "2) Integracion", title: "Integrar con el modelo estándar", subtitle: "La responsabilidad de TradeOps es mapear su preventa al contrato de sale.order, no reinventar ventas.", chip: "Odoo", content: "trade.presale\n  -> customer_id\n  -> line_ids\n  -> import_id\n  -> estado\n\nMapping\n  -> sale.order.partner_id\n  -> sale.order.order_line\n  -> trazabilidad\n\nOdoo conserva precios, impuestos, facturas y entregas." },
  { id: "sale-order", label: "3) sale.order", title: "Conocer el destino de la conversión", subtitle: "sale.order ya posee el ciclo de venta completo y debe seguir siendo el origen de verdad para la venta.", chip: "Modelo", content: "sale.order\n  +-- partner_id\n  +-- order_line\n  +-- state\n  +-- amount_total\n  +-- invoice_status\n  +-- picking_ids\n\nLa preventa no copia estas responsabilidades; las alimenta una vez." },
  { id: "mapping", label: "4) Mapping", title: "Mapear datos antes de crear", subtitle: "Cada campo del origen debe tener un destino claro y una regla explícita de transformación.", chip: "Diseño", content: "Preventa.customer_id -> SaleOrder.partner_id\nPreventa.line.product_id -> SaleOrderLine.product_id\nPreventa.line.quantity -> SaleOrderLine.product_uom_qty\nPreventa.line.unit_price -> SaleOrderLine.price_unit\nPreventa.name -> origin o referencia\n\nMapear evita pérdidas de contexto y conversiones implícitas." },
  { id: "action", label: "5) Accion", title: "La conversión es una acción empresarial", subtitle: "Un método explícito expresa intención, centraliza validaciones y puede exponerse mediante un botón controlado.", chip: "Workflow", content: "def action_convert_to_sale_order(self):\n    self.ensure_one()\n    self._check_can_convert()\n    sale_order = self._create_sale_order()\n    self.sale_order_id = sale_order\n    self.state = 'converted'\n    return self._open_sale_order(sale_order)" },
  { id: "conditions", label: "6) Condiciones", title: "No toda preventa puede convertirse", subtitle: "El negocio decide cuándo la operación es válida; el método debe comprobarlo antes de crear nada.", chip: "Reglas", content: "Condiciones mínimas:\n- preventa confirmada\n- importacion completada\n- lineas existentes\n- cliente definido\n- sin venta previa\n- cantidades validas\n\nSi falla una condición, devolver UserError con un mensaje accionable." },
  { id: "protect", label: "7) Proteccion", title: "Proteger la operación en servidor", subtitle: "El botón no es una garantía: la validación debe ejecutarse desde UI, RPC, shell o automatizaciones.", chip: "Seguridad", content: "def _check_can_convert(self):\n    if self.state != 'confirmed':\n        raise UserError('La preventa debe estar confirmada.')\n    if self.import_id.state != 'completed':\n        raise UserError('La importacion debe estar completada.')\n    if self.sale_order_id:\n        raise UserError('La preventa ya fue convertida.')" },
  { id: "ensure-one", label: "8) ensure_one", title: "Una conversión trabaja sobre una preventa", subtitle: "ensure_one() documenta y protege que la acción crea una venta para un registro concreto.", chip: "ORM", content: "def action_convert_to_sale_order(self):\n    self.ensure_one()\n\nLa acción de lista puede iterar preventas una a una, pero el método base debe tener semántica inequívoca." },
  { id: "create-order", label: "9) Crear venta", title: "Construir el sale.order con valores explícitos", subtitle: "La cabecera se crea usando los campos estándar que Odoo espera.", chip: "Create", content: "sale_order = self.env['sale.order'].create({\n    'partner_id': self.customer_id.id,\n    'origin': self.name,\n    'client_order_ref': self.name,\n    'order_line': line_commands,\n})\n\nNo confirmar automáticamente la venta salvo que la regla de negocio lo exija." },
  { id: "lines", label: "10) Lineas", title: "Transformar líneas en comandos relacionales", subtitle: "One2many se crea con comandos para que Odoo persista cabecera y líneas en una operación coherente.", chip: "ORM", content: "line_commands = [\n    (0, 0, {\n        'product_id': line.product_id.id,\n        'product_uom_qty': line.quantity,\n        'price_unit': line.unit_price,\n    })\n    for line in self.line_ids\n]\n\n(0, 0, values) crea una línea nueva dentro de order_line." },
  { id: "traceability", label: "11) Trazabilidad", title: "Mantener el vínculo de ambos lados", subtitle: "Una conversión profesional permite navegar desde la preventa a la venta y volver al origen comercial.", chip: "Traceability", content: "En trade.presale:\n  sale_order_id = fields.Many2one('sale.order')\n\nEn sale.order mediante _inherit:\n  trade_presale_id = fields.Many2one('trade.presale')\n\nPreventa -> Venta -> Importacion\n\nLa trazabilidad facilita soporte, auditoria y reportes." },
  { id: "idempotency", label: "12) Idempotencia", title: "Evitar la doble conversión", subtitle: "Dos clics o reintentos no deben producir dos pedidos de venta.", chip: "Idempotencia", content: "Antes de crear:\nif self.sale_order_id:\n    return self._open_sale_order(self.sale_order_id)\n\nO bien bloquear con UserError según UX acordada.\n\nLa regla real es: una preventa solo puede originar una sale.order." },
  { id: "state", label: "13) Estado", title: "Cambiar estado después de crear", subtitle: "La preventa se marca convertida solo cuando la venta estándar existe y la relación quedó persistida.", chip: "Transicion", content: "sale_order creado\n  -> guardar sale_order_id\n  -> actualizar state = 'converted'\n  -> devolver acción de apertura\n\nNo adelantar el estado. Si falla la creación, la preventa debe continuar sin convertir." },
  { id: "atomic", label: "14) Atomicidad", title: "La conversión debe ser todo o nada", subtitle: "Cabecera, líneas, vínculo y estado deben quedar consistentes aun cuando ocurra un error.", chip: "Transaccion", content: "Preventa valida\n  -> crear sale.order\n  -> crear lineas\n  -> enlazar registros\n  -> cambiar estado\n\nSi algo falla, la transacción de Odoo hace rollback.\nNo deben quedar ventas parciales ni preventas marcadas incorrectamente." },
  { id: "boundary", label: "15) Boundary", title: "No invadir responsabilidades estándar", subtitle: "La conversión crea una venta; no debe reimplementar facturación, stock, impuestos o confirmación nativa.", chip: "Arquitectura", content: "TradeOps controla:\n- elegibilidad de preventa\n- mapping\n- trazabilidad\n- idempotencia\n\nOdoo Sale controla:\n- venta\n- impuestos\n- facturas\n- entregas\n- estados de venta\n\nRespetar este límite reduce mantenimiento." },
  { id: "qa", label: "16) QA", title: "Probar el flujo completo", subtitle: "La verificación debe cubrir el contrato, la persistencia y la ausencia de efectos parciales.", chip: "QA", content: "Casos mínimos:\n- happy path crea una sale.order\n- importacion no completada falla\n- preventa draft falla\n- doble clic no duplica venta\n- fallo de create no cambia estado\n- líneas y precios se mapean\n- trazabilidad en ambos sentidos\n- rollback no deja registros parciales" },
  { id: "closing", label: "17) Cierre", title: "Una conversión es un límite entre dominios", subtitle: "La acción conecta un proceso custom con Odoo estándar sin romper la responsabilidad de ninguno.", chip: "Cierre", content: "Regla mental:\n\nValidar antes de cruzar el límite.\nMapear explícitamente.\nCrear de forma atómica.\nGuardar trazabilidad.\nHacer la operación idempotente.\n\nTradeOps transforma la preventa en una venta real, una sola vez." },
];

export default function Daily170Client() {
  const [activeSection, setActiveSection] = useState("problem");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/169"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Preventa a venta estandar de Odoo</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/169"><span className={styles.kbd}>←</span> Dia 169</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>05/09/2026</div><div className={styles.badge}>Daily #170 • Odoo Integration</div><h2 className={styles.title}>Convertir una Preventa en sale.order estándar de Odoo</h2><p className={styles.lead}>Integrar el compromiso comercial de TradeOps con el modelo de ventas estándar, de forma trazable e idempotente.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/169"><span className={styles.kbd}>←</span> Dia 169</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
