"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "idea", label: "1) Idea clave", title: "Payments no es solo HttpClient", subtitle: "Un proveedor externo puede ser lento, rechazar, fallar o procesar un cobro cuya respuesta se perdio.", chip: "Idea", content: "OrderFlow ya puede:\n\nCrear una orden\nConfirmarla\nReservar inventario\n\nAhora necesitamos cobrar.\n\nPayments se comunicara con Stripe, PayPal, Adyen, Mercado Pago o un proveedor bancario.\n\nIntegrar pagos significa diseñar para respuestas inciertas, duplicados y fallos de comunicacion." },
  { id: "responsibility", label: "2) Responsabilidad", title: "Que responsabilidad tendra Payments", subtitle: "Payments gestiona intentos, referencias, reembolsos y resultados del proveedor.", chip: "Limites", content: "Payments controla:\n\ncrear intentos de pago\ncomunicarse con el proveedor\nregistrar cada intento\nevitar cobros duplicados\ninterpretar aprobaciones y rechazos\nmanejar timeouts\nconsultar operaciones inciertas\nregistrar referencias externas\nprocesar reembolsos\npublicar resultados\n\nNo decide stock, catalogo, orden ni notificaciones." },
  { id: "outcomes", label: "3) Resultados", title: "Rechazo no es fallo tecnico", subtitle: "Debemos distinguir una respuesta de negocio de una respuesta que nunca pudimos conocer.", chip: "Semantica", content: "Pago rechazado:\n\nTarjeta sin fondos\nTarjeta vencida\nOperacion no autorizada\nLimite excedido\n\nEl proveedor respondio correctamente. Es PaymentRejected.\n\nFallo tecnico:\n\nTimeout\nConnection refused\nHTTP 500\nRespuesta invalida\n\nNo conocemos el resultado. Es PendingVerification." },
  { id: "timeout", label: "4) Timeout", title: "Un timeout no es un rechazo", subtitle: "El proveedor puede haber cobrado aunque nuestra aplicacion no recibiera la respuesta.", chip: "Riesgo", content: "1. Payments envia la solicitud.\n2. El proveedor realiza el cobro.\n3. La respuesta se pierde.\n4. Payments recibe timeout.\n5. Payments reintenta sin control.\n6. El cliente recibe dos cobros.\n\nPor eso debemos marcar el pago como incierto y verificarlo antes de volver a cobrar." },
  { id: "idempotency", label: "5) Idempotencia", title: "La clave representa el negocio", subtitle: "Los retries deben reutilizar la misma clave para que el proveedor no cree un segundo cobro.", chip: "Idempotencia", content: "Idempotency-Key: order-payment-151874fb\n\nPrimera solicitud:\nEl proveedor crea el cobro.\n\nSegunda solicitud con la misma clave:\nEl proveedor devuelve el mismo resultado.\n\nNo debemos generar una clave nueva por cada intento HTTP. La clave representa el pago de la orden." },
  { id: "states", label: "6) Estados", title: "La maquina de estados del pago", subtitle: "Cada estado expresa una realidad diferente del proceso financiero.", chip: "Estados", content: "Pending = creado, aun no iniciado\nProcessing = enviado al proveedor\nApproved = cobro confirmado\nRejected = proveedor rechazo\nPendingVerification = resultado incierto\nRefundPending = devolucion solicitada\nRefunded = devolucion confirmada\nRefundFailed = devolucion fallida\n\nNo debemos colapsarlos en un simple boolean Success." },
  { id: "structure", label: "7) Estructura", title: "La estructura de Payments", subtitle: "La integracion queda aislada de dominio, aplicacion y persistencia.", chip: "Arquitectura", content: "Payments\n|-- Payments.API\n|   |-- Controllers\n|   |-- Middleware\n|   |-- Program.cs\n|-- Payments.Application\n|   |-- Payments\n|   |-- Refunds\n|   |-- DTOs\n|   |-- Abstractions\n|-- Payments.Domain\n|   |-- Payments\n|   |-- Refunds\n|-- Payments.Infrastructure\n    |-- Persistence\n    |-- Providers\n    |-- Repositories\n    |-- Migrations" },
  { id: "payment", label: "8) Payment", title: "La entidad Payment", subtitle: "Payment guarda el estado, la clave de idempotencia, la referencia externa y sus intentos.", chip: "Domain", content: "Payment:\nId\nOrderId\nAmount\nCurrency\nIdempotencyKey\nStatus\nProviderPaymentId\nRejectionCode\nRejectionReason\nCreatedAt\nProcessedAt\nUpdatedAt\nAttempts\n\nEl constructor valida ids, monto, moneda y clave. Las propiedades tienen private set." },
  { id: "attempt", label: "9) Intentos", title: "PaymentAttempt registra cada llamada", subtitle: "La auditoria financiera necesita conocer cuantas llamadas se hicieron y que resultado tuvo cada una.", chip: "Auditoria", content: "PaymentAttemptStatus:\nStarted\nApproved\nRejected\nUncertain\n\nCada intento guarda:\nNumber\nProviderPaymentId\nResultCode\nResultDescription\nStartedAt\nFinishedAt\n\nEsto sirve para soporte, conciliacion, diagnostico y cumplimiento financiero." },
  { id: "behavior", label: "10) Comportamiento", title: "Payment protege sus transiciones", subtitle: "El agregado decide cuando puede iniciar, aprobar, rechazar o marcar un pago como incierto.", chip: "Reglas", content: "StartAttempt:\n- rechaza Approved, Rejected o Refunded\n- cambia a Processing\n- crea el intento\n\nApprove:\n- exige Processing\n- requiere ProviderPaymentId\n\nReject:\n- exige codigo y razon\n\nMarkPendingVerification:\n- conserva la incertidumbre\n\nConfirmAfterVerification:\n- solo permite resolver un pago incierto." },
  { id: "provider-contract", label: "11) Proveedor", title: "Contrato IPaymentProvider", subtitle: "Application no conoce HttpClient ni el SDK de Stripe o del proveedor elegido.", chip: "Abstraccion", content: "IPaymentProvider:\nChargeAsync(ProviderChargeRequest)\nGetStatusAsync(idempotencyKey)\nRefundAsync(ProviderRefundRequest)\n\nProviderChargeRequest:\nPaymentId\nOrderId\nAmount\nCurrency\nPaymentMethodToken\nIdempotencyKey\n\nInfrastructure implementa el proveedor concreto." },
  { id: "result", label: "12) Resultado discriminado", title: "No devolver solo bool Success", subtitle: "El caso de uso debe distinguir aprobado, rechazado e incierto.", chip: "Contrato", content: "ProviderPaymentResultType:\nApproved\nRejected\nUncertain\n\nProviderPaymentResult incluye:\nType\nProviderPaymentId\nCode\nDescription\n\nApproved necesita referencia externa. Rejected necesita codigo y descripcion. Uncertain conserva el motivo." },
  { id: "dtos", label: "13) DTOs", title: "Procesar un pago", subtitle: "La API recibe datos de la orden y devuelve el estado actual del pago.", chip: "API", content: "ProcessPaymentRequest:\nOrderId\nAmount\nCurrency\nPaymentMethodToken\n\nPaymentResponse:\nPaymentId\nOrderId\nAmount\nCurrency\nStatus\nProviderPaymentId\nRejectionCode\nRejectionReason\n\nEl token del metodo no debe persistirse como dato sensible." },
  { id: "repository", label: "14) Repositorio", title: "Buscar por orden y por idempotencia", subtitle: "La persistencia debe impedir que la misma operacion de negocio cree pagos duplicados.", chip: "Persistencia", content: "IPaymentRepository:\nGetByIdAsync\nGetByOrderIdAsync\nGetByIdempotencyKeyAsync\nAddAsync\n\nIUnitOfWork:\nSaveChangesAsync\n\nAdemas, la base debe tener un indice unico para IdempotencyKey." },
  { id: "key", label: "15) Crear clave", title: "Una clave estable por orden", subtitle: "La misma orden siempre genera la misma clave de pago.", chip: "Idempotencia", content: "private static string CreateIdempotencyKey(Guid orderId)\n{\n    return $\"order-payment-{orderId:N}\";\n}\n\nPara una orden concreta:\norder-payment-151874fbeb384699acd24bc943a9296a\n\nLa clave no representa el request HTTP; representa la operacion de cobro." },
  { id: "application", label: "16) Caso de uso", title: "ProcessAsync paso a paso", subtitle: "Primero registramos nuestra intencion, despues llamamos al proveedor y finalmente guardamos el resultado.", chip: "Application", content: "1. Validar request.\n2. Crear idempotencyKey.\n3. Buscar pago existente.\n4. Devolverlo si ya existe.\n5. Crear Payment Pending.\n6. Guardarlo.\n7. Iniciar intento y guardar.\n8. Crear ProviderChargeRequest.\n9. Llamar IPaymentProvider.\n10. Aplicar Approved, Rejected o Uncertain.\n11. Guardar resultado.\n12. Devolver PaymentResponse." },
  { id: "before-external", label: "17) Orden transaccional", title: "Guardar antes del efecto externo", subtitle: "No debemos depender de poder guardar localmente despues de cobrar al proveedor.", chip: "Transaccion", content: "Primero:\nPayment Pending\nPaymentAttempt Started\nGuardar\n\nDespues:\nLlamar al proveedor\n\nFinalmente:\nGuardar Approved, Rejected o PendingVerification\n\nSi cobramos primero y nuestra base falla, podemos perder el registro local del cobro. Aun necesitaremos reconciliacion para fallos posteriores." },
  { id: "http", label: "18) HTTP Provider", title: "Enviar la clave al proveedor", subtitle: "La implementacion HTTP debe propagar la idempotencia y clasificar respuestas.", chip: "HTTP", content: "POST payments\nHeader: Idempotency-Key\n\nBody:\nreference\norderId\namount\ncurrency\npaymentMethodToken\n\n2xx -> Approved\n422 -> Rejected\nTimeout o error de red -> Uncertain\nRespuesta invalida -> Uncertain o fallo tecnico\n\nNunca se debe reintentar un cobro con una clave nueva." },
  { id: "resilience", label: "19) Resiliencia", title: "Timeout, retry y circuit breaker", subtitle: "Los patrones deben proteger el sistema sin multiplicar efectos financieros.", chip: "Resiliencia", content: "Timeout limita cuanto esperamos.\nRetry solo es seguro con la misma clave.\nCircuit Breaker evita llamar a un proveedor caido.\nFallback puede devolver PendingVerification.\n\nOrden recomendado:\n1. Timeout\n2. Clasificar incertidumbre\n3. Consultar estado\n4. Reintentar con idempotencia\n5. Abrir circuito si el fallo persiste" },
  { id: "uncertain", label: "20) Incertidumbre", title: "Resolver un pago incierto", subtitle: "PendingVerification no significa que debamos cobrar otra vez.", chip: "Reconciliacion", content: "Payment PendingVerification\n        |\n        v\nConsultar proveedor por IdempotencyKey\n        |\n        +--> Approved: ConfirmAfterVerification\n        |\n        +--> Rejected: marcar rechazo\n        |\n        +--> Sigue sin respuesta: mantener pendiente\n\nLa incertidumbre se resuelve consultando, no duplicando el cobro." },
  { id: "refund", label: "21) Reembolsos", title: "Procesar una devolucion", subtitle: "Un refund tambien necesita estados, referencia externa e idempotencia.", chip: "Refund", content: "RefundPending\nRefunded\nRefundFailed\n\nFlujo:\n1. validar que Payment fue Approved\n2. crear solicitud de refund\n3. llamar provider.RefundAsync\n4. registrar referencia\n5. marcar Refunded o RefundFailed\n\nNunca devolver dos veces la misma operacion." },
  { id: "database", label: "22) Persistencia", title: "PaymentsDb propio", subtitle: "Pagos e intentos viven en una base independiente y auditable.", chip: "EF Core", content: "PaymentsDbContext:\nDbSet<Payment> Payments\nDbSet<PaymentAttempt> PaymentAttempts\n\nConfiguracion:\nPayment.Amount precision 18,2\nCurrency maximo 3\nIdempotencyKey requerida y unica\nProviderPaymentId indexable\nAttempts con relacion a Payment\n\nPayments no escribe OrdersDb ni CatalogDb." },
  { id: "concurrency", label: "23) Concurrencia", title: "Proteger pagos duplicados", subtitle: "La logica de aplicacion no basta: la base debe reforzar la unicidad.", chip: "Concurrencia", content: "Dos requests para la misma orden pueden llegar a la vez.\n\nAmbos buscan y no encuentran Payment.\nAmbos intentan crear.\n\nLa restriccion unica sobre IdempotencyKey hace que solo uno gane.\n\nEl segundo debe volver a leer el pago existente y devolver el mismo resultado." },
  { id: "api", label: "24) Endpoints", title: "Exponer Payments", subtitle: "La API debe representar estados financieros y operaciones inciertas sin ocultarlas.", chip: "Endpoints", content: "POST /api/payments\nGET /api/payments/{id}\nGET /api/orders/{orderId}/payment\nPOST /api/payments/{id}/verify\nPOST /api/payments/{id}/refund\n\n201 al crear intento.\n200 para estado conocido.\n202 si queda PendingVerification.\n409 para conflicto de operacion." },
  { id: "flow", label: "25) Flujo completo", title: "Orders, Inventory y Payments", subtitle: "La compra avanza por servicios con estados claros y compensaciones posibles.", chip: "Integracion", content: "Orders confirma\n       |\n       v\nInventory reserva\n       |\n       v\nPayments procesa\n       |\n       +--> Approved -> confirmar consumo\n       |\n       +--> Rejected -> liberar inventario\n       |\n       +--> Uncertain -> reconciliar\n\nEl siguiente bloque conectara estos pasos con eventos y Saga." },
  { id: "failures", label: "26) Fallos", title: "Casos que debemos probar", subtitle: "Una integracion financiera debe demostrar como se comporta ante cada incertidumbre.", chip: "Testing", content: "Tarjeta rechazada -> Rejected\nTimeout despues de cobro -> PendingVerification\nRetry con misma clave -> no duplica\nRetry con clave nueva -> debe rechazarse en diseño\nProveedor caido -> circuit abierto\nRespuesta invalida -> resultado incierto\nReembolso aprobado -> Refunded\nReembolso fallido -> RefundFailed\nDos requests simultaneos -> un solo Payment" },
  { id: "result-final", label: "27) Resultado", title: "Que hemos conseguido", subtitle: "Payments ya puede integrar un proveedor externo sin confundir negocio, transporte e incertidumbre.", chip: "Resultado", content: "Payments tiene:\n\ndominio de pagos\nestados explicitos\nintentos auditables\nclave de idempotencia\nproveedor abstraido\nrespuestas discriminadas\nreconciliacion\nreembolsos\nbase propia\n\nUn timeout ya no se interpreta ingenuamente como rechazo." },
  { id: "checklist", label: "28) Checklist", title: "Validacion de Payments", subtitle: "El servicio esta listo cuando puede repetir, verificar y compensar sin cobrar dos veces.", chip: "Checklist", content: "Payment valida sus invariantes\nPaymentAttempt registra cada llamada\nIdempotencyKey estable por orden\nIndice unico en base\nRejected separado de Uncertain\nProvider abstraido\nPersistencia previa al cobro\nTimeout controlado\nRetry con misma clave\nConsulta de estado incierto\nRefund idempotente\nPaymentsDb independiente\n\nEl proceso ya puede avanzar hacia una arquitectura distribuida confiable." },
  { id: "closing", label: "29) Cierre", title: "Como piensa un backend senior", subtitle: "Cobrar no es llamar un endpoint: es diseñar estados, auditoria, idempotencia y reconciliacion.", chip: "Cierre", content: "Backend junior:\nPayments es un wrapper de HttpClient.\n\nBackend senior:\nCada cobro tiene una operacion de negocio, intentos, una clave estable, un resultado posible y un plan para cuando la respuesta se pierde.\n\nUn sistema de pagos confiable no asume que la red siempre responde." },
];

export default function Daily140Client() {
  const [activeSection, setActiveSection] = useState("idea");

  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement | null;
      if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return;
      if (event.key.toLowerCase() === "p") window.location.href = "/daily/139";
    };
    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, []);

  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);

  return (
    <div className={styles.page}>
      <header className={styles.topbar}><div className={styles.topbarInner}>
        <div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Payments Service y resiliencia externa</div></div></div>
        <nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav>
        <div className={styles.actions}><Link className={styles.btn} href="/daily/139"><span className={styles.kbd}>←</span> Dia 139</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div>
      </div></header>
      <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}>
        <div className={styles.dailyHero}><div className={styles.createdAt}>25/07/2026</div><div className={styles.badge}>Daily #140 • Payments Service</div><h2 className={styles.title}>Crear Payments Service e integrar resiliencia ante fallos externos</h2><p className={styles.lead}>Payments debe manejar rechazos, timeouts, duplicados y reembolsos sin perder la trazabilidad ni cobrar dos veces.</p></div>
        <nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>
        {sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}
        <div className={styles.footerNav}><Link className={styles.btn} href="/daily/139"><span className={styles.kbd}>←</span> Dia 139</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div>
      </div></article></div></main>
    </div>
  );
}
