"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "platform", label: "1) Plataforma", title: "Odoo es una plataforma extensible", subtitle: "Extendemos las capacidades existentes antes de reconstruir funcionalidades del ERP.", chip: "Odoo", content: "Odoo\n  +-- Ventas\n  +-- Inventario\n  +-- Contactos\n  +-- Seguridad\n  +-- Framework\n        ↓\n    TradeOps 360\n\nUn addon encapsula una funcionalidad y puede instalarse, actualizarse y versionarse." },
  { id: "architecture", label: "2) Arquitectura", title: "Server, ORM y PostgreSQL", subtitle: "El servidor coordina la logica, el ORM y la persistencia relacional.", chip: "Arquitectura", content: "Usuario\n   ↓\nWeb Client\n   ↓\nOdoo Server\n   ↓\nORM\n   ↓\nPostgreSQL\n\nTrabajamos con modelos y recordsets, no con tablas directamente." },
  { id: "manifest", label: "3) Addon", title: "El manifest define el modulo", subtitle: "Nombre, version, dependencias y archivos forman el contrato de carga del addon.", chip: "Modulo", content: "{\n    'name': 'TradeOps Imports',\n    'version': '17.0.1.0.0',\n    'depends': ['trade_core'],\n    'data': [],\n    'installable': True,\n}\n\nLas dependencias determinan el orden de carga." },
  { id: "model", label: "4) Modelos", title: "Un modelo representa comportamiento", subtitle: "No es solo una tabla: contiene datos, relaciones, validaciones y acciones del negocio.", chip: "ORM", content: "class TradeImport(models.Model):\n    _name = 'trade.import'\n\n    name = fields.Char(required=True)\n    state = fields.Selection([...])\n    line_ids = fields.One2many(...)\n\nEl modelo expresa el lenguaje de TradeOps." },
  { id: "env", label: "5) Environment", title: "El contexto vive en env", subtitle: "Usuario, compania, contexto y modelos disponibles acompañan cada operacion del ORM.", chip: "Contexto", content: "self.env.user\nself.env.company\nself.env.context\nself.env['product.product']\n\nEl Environment responde desde que contexto se ejecuta la operacion." },
  { id: "relations", label: "6) Relaciones", title: "Relacionar entidades sin perder claridad", subtitle: "Many2one, One2many y Many2many modelan los vinculos reales entre los conceptos.", chip: "Relaciones", content: "Importacion\n  +-- Many2one -> proveedor\n  +-- One2many -> lineas\n  +-- One2many -> gastos\n\nLas relaciones deben tener dominios, ondelete y permisos coherentes." },
  { id: "rules", label: "7) Reglas", title: "Constraints e invariantes protegen el dominio", subtitle: "Las reglas del servidor deben funcionar desde UI, shell, RPC, importaciones y cron.", chip: "Validacion", content: "@api.constrains('quantity')\ndef _check_positive_quantity(self):\n    for line in self:\n        if line.quantity <= 0:\n            raise ValidationError(\n                'La cantidad debe ser mayor que cero.')\n\nUna vista puede ayudar, pero no sustituye la constraint." },
  { id: "computed", label: "8) Computed", title: "Calcular lo derivado", subtitle: "Computed fields y @api.depends mantienen valores utiles sincronizados con sus dependencias.", chip: "Computed", content: "@api.depends('line_ids.quantity')\ndef _compute_total(self):\n    for record in self:\n        record.total = sum(\n            line.quantity for line in record.line_ids)\n\nUsar store=True cuando el valor deba buscarse, ordenarse o reportarse." },
  { id: "workflow", label: "9) Workflow", title: "Los estados necesitan transiciones validas", subtitle: "Un Selection define valores posibles; las acciones de negocio definen el flujo permitido.", chip: "Workflow", content: "Draft\n  ↓\nDocument Review\n  ↓\nValidated\n  ↓\nIn Transit\n  ↓\nReceiving\n  ↓\nCompleted\n\nNo se debe asignar completed directamente desde cualquier estado." },
  { id: "cost", label: "10) Costos", title: "El costo real incluye los gastos de importacion", subtitle: "Flete, nacionalizacion y transporte se distribuyen proporcionalmente entre las lineas.", chip: "Costing", content: "purchase_total = sum(line.purchase_subtotal)\nadditional_cost = sum(expense.amount)\n\nline_ratio = line.purchase_subtotal / purchase_total\nline.additional_cost = line_ratio * additional_cost\nline.real_cost = line.purchase_subtotal + line.additional_cost" },
  { id: "map", label: "11) Mapa", title: "El conocimiento ya forma un sistema", subtitle: "Addon, ORM, relaciones, reglas, workflow y costos se conectan en TradeOps 360.", chip: "Integracion", content: "Odoo\n  -> trade_core\n  -> trade_import\n       -> lineas\n       -> gastos\n       -> computed fields\n       -> constraints\n       -> workflow\n       -> costo real\n\nCada capa debe reforzar a las demas." },
  { id: "checklist", label: "12) Checklist", title: "Resumen para continuar construyendo", subtitle: "Antes de avanzar, el modelo debe ser comprensible, consistente y verificable.", chip: "Checklist", content: "[x] Arquitectura Odoo entendida\n[x] Addons y manifest\n[x] ORM y Environment\n[x] Modelos y relaciones\n[x] Computed fields\n[x] Constraints e invariantes\n[x] Workflow y acciones\n[x] Gastos y prorrateo\n[ ] Implementar y probar TradeOps 360" },
  { id: "closing", label: "13) Cierre", title: "De conceptos aislados a un sistema", subtitle: "El objetivo no es memorizar APIs, sino conectar las piezas para construir un modulo profesional.", chip: "Cierre", content: "Backend junior:\nConoce herramientas por separado.\n\nBackend senior:\nSabe cuando extender, donde colocar una regla, como persistirla y como comprobar el flujo completo.\n\nEl siguiente paso es implementar sobre esta base." },
];

export default function Daily165Client() {
  const [activeSection, setActiveSection] = useState("platform");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/164"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Resumen de Odoo 17 y TradeOps 360</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/164"><span className={styles.kbd}>←</span> Dia 164</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>31/08/2026</div><div className={styles.badge}>Daily #165 • Odoo Review</div><h2 className={styles.title}>Resumen de lo que hemos visto hasta ahora</h2><p className={styles.lead}>Una síntesis conceptual de Odoo 17, el ORM, las reglas de negocio y la construcción de TradeOps 360.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/164"><span className={styles.kbd}>←</span> Dia 164</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
