"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import styles from "../daily-lesson.module.css";

type LessonSection = { id: string; label: string; title: string; subtitle: string; chip: string; content: string };

const sections: LessonSection[] = [
  { id: "problem", label: "1) Problema", title: "Vender antes de recibir la mercancia", subtitle: "El equipo comercial necesita comprometer unidades de una importacion que aun esta en transito.", chip: "Contexto", content: "IMP-001\n  +-- TV x 100\n  +-- Laptop x 50\n\nPreventas\n  +-- Cliente A -> 20 TV\n  +-- Cliente B -> 30 TV\n\nLa preventa reserva una intencion comercial; aun no es una venta estandar." },
  { id: "concept", label: "2) Concepto", title: "Preventa e importacion son conceptos distintos", subtitle: "La preventa pertenece al flujo de TradeOps y se convertira en sale.order solo con una accion posterior.", chip: "Dominio", content: "trade.import\n  -> proceso de importacion\n\ntrade.presale\n  -> compromiso comercial previo\n\nsale.order\n  -> venta estandar de Odoo\n\nLa conversion a venta llegara cuando la importacion este completada." },
  { id: "standard", label: "3) Estandar", title: "Reutilizar sale.order", subtitle: "No creamos una venta propia porque Odoo ya resuelve precios, impuestos, facturacion, entregas y estados.", chip: "Odoo", content: "Preventa custom\n  -> conversion confirmada\n  -> sale.order estandar\n\nEvitar trade.sale mantiene la integracion con los modulos oficiales de Odoo." },
  { id: "addon", label: "4) Addon", title: "Crear trade_presale", subtitle: "El addon declara las dependencias necesarias para modelar preventas y preparar su integracion con ventas.", chip: "Modulo", content: "trade_presale/\n  +-- __init__.py\n  +-- __manifest__.py\n  +-- models/\n      +-- trade_presale.py\n      +-- trade_presale_line.py\n\n'depends': ['trade_import', 'sale']" },
  { id: "model", label: "5) Modelo", title: "La preventa conecta cliente e importacion", subtitle: "La cabecera representa el compromiso comercial sobre una importacion concreta.", chip: "ORM", content: "class TradePresale(models.Model):\n    _name = 'trade.presale'\n\n    name = fields.Char(required=True, default='New')\n    import_id = fields.Many2one(\n        'trade.import', required=True, ondelete='restrict')\n    customer_id = fields.Many2one(\n        'res.partner', required=True)\n    line_ids = fields.One2many(\n        'trade.presale.line', 'presale_id')" },
  { id: "restrict", label: "6) Restrict", title: "No borrar una importacion con preventas", subtitle: "ondelete='restrict' protege la trazabilidad y obliga a resolver los compromisos antes de eliminar la cabecera.", chip: "Integridad", content: "import_id = fields.Many2one(\n    'trade.import',\n    required=True,\n    ondelete='restrict',\n)\n\nSi existen preventas relacionadas, la importacion no puede desaparecer accidentalmente." },
  { id: "lines", label: "7) Lineas", title: "Cada linea representa un producto reservado", subtitle: "Las lineas guardan producto, cantidad y el vinculo con la preventa.", chip: "Relaciones", content: "class TradePresaleLine(models.Model):\n    _name = 'trade.presale.line'\n\n    presale_id = fields.Many2one(\n        'trade.presale', required=True, ondelete='cascade')\n    product_id = fields.Many2one(\n        'product.product', required=True)\n    quantity = fields.Float(required=True)" },
  { id: "rule", label: "8) Regla", title: "Solo productos de la importacion", subtitle: "Una preventa no puede reservar un producto que no haya sido cargado en su importacion.", chip: "Invariante", content: "Preventa.import_id\n  -> Importacion.line_ids.product_id\n\nPreventa.line.product_id\n  debe pertenecer a esos productos.\n\nLa relacion es parte de la regla de negocio, no solo una comodidad de interfaz." },
  { id: "domain", label: "9) Domain", title: "El Domain ayuda a elegir correctamente", subtitle: "El formulario puede filtrar productos disponibles segun la importacion seleccionada.", chip: "UX", content: "<field name='product_id'\n  domain=\"[('id', 'in', parent.import_id.line_ids.product_id)]\"/>\n\nEl Domain reduce errores del usuario, pero no protege el modelo desde shell, RPC o importaciones." },
  { id: "constraint", label: "10) Constraint", title: "La constraint protege en servidor", subtitle: "La validacion real confirma que cada producto exista en las lineas de la importacion.", chip: "Validacion", content: "@api.constrains('product_id', 'presale_id')\ndef _check_product_belongs_to_import(self):\n    for line in self:\n        allowed = line.presale_id.import_id.line_ids.mapped('product_id')\n        if line.product_id not in allowed:\n            raise ValidationError(\n                'El producto no pertenece a la importacion.')" },
  { id: "quantity", label: "11) Cantidad", title: "La cantidad reservada debe ser positiva", subtitle: "Las reservas con cero o valores negativos no representan una operacion comercial valida.", chip: "Constraint", content: "@api.constrains('quantity')\ndef _check_quantity(self):\n    for line in self:\n        if line.quantity <= 0:\n            raise ValidationError(\n                'La cantidad debe ser mayor que cero.')\n\nLa siguiente regla es controlar que el total reservado no exceda lo importado." },
  { id: "overpresale", label: "12) Sobrepreventa", title: "No vender mas de lo disponible", subtitle: "La disponibilidad debe considerar todas las preventas activas de una importacion, no solo la linea actual.", chip: "Aggregate", content: "Importado: 100 TV\nPreventa A: 20 TV\nPreventa B: 30 TV\nDisponible: 50 TV\n\nUna nueva reserva de 60 TV debe fallar.\n\nLa comprobacion agrega lineas activas y excluye la linea actual al actualizar." },
  { id: "state", label: "13) Estado", title: "El estado controla el ciclo de vida", subtitle: "La preventa necesita estados claros antes de poder convertirse en una venta de Odoo.", chip: "Workflow", content: "draft\n  -> confirmada\n  -> convertida a venta\n  -> cancelada\n\nSolo las preventas confirmadas deben participar en los calculos de reserva y conversion." },
  { id: "stock", label: "14) Stock", title: "Preventa no es stock", subtitle: "La reserva comercial se vincula a la importacion; el movimiento de inventario sigue siendo responsabilidad de los modulos estandar.", chip: "Arquitectura", content: "trade.presale\n  -> compromiso comercial\ntrade.import\n  -> mercancia esperada\nstock.picking\n  -> movimiento fisico\nsale.order\n  -> venta\n\nSeparar conceptos evita mezclar estados incompatibles." },
  { id: "qa", label: "15) QA", title: "Probar las reglas de preventa", subtitle: "Las pruebas deben demostrar que la interfaz y el servidor mantienen la consistencia del flujo.", chip: "QA", content: "Casos minimos:\n- producto valido de la importacion\n- producto ajeno rechazado\n- cantidad cero rechazada\n- cantidad negativa rechazada\n- sobrepreventa rechazada\n- importacion con preventas no se elimina\n- cambio de importacion revalida lineas\n- solo estados activos reservan unidades" },
  { id: "closing", label: "16) Cierre", title: "La preventa conserva contexto y control", subtitle: "TradeOps puede vender antes de recibir sin duplicar ventas ni perder el vinculo con la mercancia real.", chip: "Cierre", content: "Regla mental:\n\nModelar el compromiso comercial antes de convertirlo en venta.\nUsar Domains para guiar.\nUsar Constraints para proteger.\nUsar agregados para impedir sobrepreventa.\n\nEl proximo paso sera la conversion controlada hacia sale.order." },
];

export default function Daily168Client() {
  const [activeSection, setActiveSection] = useState("problem");
  useEffect(() => {
    const nodes = sections.map((section) => document.getElementById(section.id)).filter((node): node is HTMLElement => Boolean(node));
    if (!nodes.length) return;
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && setActiveSection(entry.target.id)), { rootMargin: "-45% 0px -50% 0px", threshold: 0.01 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => { const target = event.target as HTMLElement | null; if (target && (target.tagName === "INPUT" || target.tagName === "TEXTAREA")) return; if (event.key.toLowerCase() === "p") window.location.href = "/daily/166"; };
    window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown);
  }, []);
  const tocLinkClass = useMemo(() => (id: string) => `${styles.tocLink} ${activeSection === id ? styles.active : ""}`, [activeSection]);
  return <div className={styles.page}>
    <header className={styles.topbar}><div className={styles.topbarInner}><div className={styles.brand}><div className={styles.logo} aria-hidden="true" /><div><h1>Daily Backend</h1><div className={styles.brandSub}>Preventas e Importaciones en TradeOps</div></div></div><nav className={styles.nav} aria-label="Navegacion"><Link className={styles.pill} href="/daily">Archivo</Link><Link className={styles.pill} href="/calendar">Calendario</Link></nav><div className={styles.actions}><Link className={styles.btn} href="/daily/166"><span className={styles.kbd}>←</span> Dia 166</Link><Link className={`${styles.btn} ${styles.primary}`} href="/calendar">Ver calendario <span className={styles.kbd}>→</span></Link></div></div></header>
    <main className={styles.container}><div className={styles.grid}><article className={styles.card}><div className={styles.bd}><div className={styles.dailyHero}><div className={styles.createdAt}>03/09/2026</div><div className={styles.badge}>Daily #168 • Odoo TradeOps</div><h2 className={styles.title}>Preventas vinculadas a Importaciones</h2><p className={styles.lead}>Modelar compromisos comerciales sobre mercancia importada sin duplicar la venta estandar de Odoo.</p></div><nav className={styles.toc} aria-label="Indice">{sections.map((section) => <a key={section.id} href={`#${section.id}`} className={tocLinkClass(section.id)}>{section.label}</a>)}</nav>{sections.map((section) => <section className={styles.section} id={section.id} key={section.id}><div className={styles.shd}><div><h3>{section.title}</h3><p className={styles.sub}>{section.subtitle}</p></div><span className={styles.chip}>{section.chip}</span></div><div className={styles.sbd}><pre>{section.content}</pre></div></section>)}<div className={styles.footerNav}><Link className={styles.btn} href="/daily/166"><span className={styles.kbd}>←</span> Dia 166</Link><Link className={styles.btn} href="/calendar">Ver calendario</Link></div></div></article></div></main>
  </div>;
}
